### ISSUE TITLE
Crashed with error : Extended attributes (EA) are inherent

### ISSUE THREAD

**Issue by crazy-max** [upx/upx#136]
## What's the problem (or question)?

Error message while launching an exe compressed with UPX : `Extended attributes (EA) are inherent`

## What should have happened?

Exe must not crashed i think ^^

## Do you have an idea for a solution?

No :(

## How can we reproduce the issue?

* Download the latest release of WindowsSpyBlocker.exe written in Golang here : https://github.com/crazy-max/WindowsSpyBlocker/releases
* Compress with UPX : `upx.exe -f WindowsSpyBlocker.exe`
* No error from UPX but then run `WindowsSpyBlocker.exe`, crashed.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Windows 10 Pro x64 1703 (15063.674)
* Host CPU architecture: x64
* Target Operating System and version: Windows 7 / 8.1 / 10
* Target CPU architecture: x86 & x64

**Comment by markus-oberhumer** [comment]
BTW, using `upx --force` is not officially supported -it **may** work for some exes.

**Comment by Mattiwatti** [comment]
I can't reproduce this in any way whatsoever, on any version of Windows from XP through 10, using both UPX 3.94 and the latest `devel` checkout, 32 bit and 64 bit versions of Windows, and 32 and 64 bit versions of UPX. I'm even trying both the latest version of the tool on the download page and v4.9.0, which was released a few days before this issue was posted. Furthermore the output files work on all of these combinations with no use of `--force` required. (_Adding_ the flag doesn't cause any issues either.)

I was curious about this issue because
- EAs are a filesystem concept, which means they have nothing to do with UPX whatsoever;
- [assuming NTFS or even FAT]: "EAs are inherent" doesn't make sense to begin with. You can set, edit and wipe EAs on file objects just like any other attribute. "Kernel EAs" do exist, but that just means you need to be in ring 0 to modify them, not that they are 'inherent' in any way.

In a final act of desperation I did a simultaneous physical text search (ASCII+UTF-8+UTF-16 LE) on both Windows 7 and Windows 10 disks to check for the existence of the error message anywhere at all, with no result. I know that doesn't rule out encryption, but that's too far fetched a theory even by MS standards.

Are you still having the issue OP? I'm not saying I don't believe you, but IMO it's a lot more likely you've got some crap on your PC that you wanna uninstall than that this is somehow a UPX bug.

**Comment by crazy-max** [comment]
@Mattiwatti Since i have changed some piece of code it seems to work now :) Thanks!
