### ISSUE TITLE
Pack mips so file failed 

### ISSUE THREAD

**Issue by pcheng74** [upx/upx#137]
## What's the problem (or question)?

upx can't pack the mips so file

## What should have happened?

It will return the following information:
upx: libtest.so: UnknownExecutableFormatException

## Do you have an idea for a solution?

The so file has the following informatoin:
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           MIPS R3000
  Version:                           0x1
  Entry point address:               0x4e0
  Start of program headers:          52 (bytes into file)
  Start of section headers:          2340 (bytes into file)
  Flags:                             0x70001007, noreorder, pic, cpic, o32, mips32r2
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         5
  Size of section headers:           40 (bytes)
  Number of section headers:         26
  Section header string table index: 23

## How can we reproduce the issue?

1. Execute "upx libtest.so" it will return upx: libtest.so: UnknownExecutableFormatException
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.94w
* Host Operating System and version: Win 10
* Host CPU architecture: Intel 64-bit
* Target Operating System and version: 32-bit 
[mips.zip](https://github.com/upx/upx/files/1404722/mips.zip)
Arm Linux
* Target CPU architecture: MIPS R3000

**Comment by jreiser** [comment]
The ability to compress a MIPS shared library was added to the <tt>devel</tt> branch just last week.  Please try that.

Thank you for Attaching the mips.zip file containing libtest.so.  The libtest.so is too small to compress.
```n
$  readelf --segments libtest.so
Program Headers:
  LOAD           0x000000 0x00000000 0x00000000 0x007a0 0x007a0 R E 0x10000
  LOAD           0x0007a0 0x000107a0 0x000107a0 0x00060 0x00070 RW  0x10000
```
That is less that 2KiB of .text, and only the instructions in that segment can be compressed in a shared library.  The .data, plus symbol tables and string tables and relocation tables in .text, cannot be compressed because the dynamic linker needs to access them before calling DT_INIT, which is when de-compression occurs.  Here is an example of a shared library that can be compressed:
```
int const x[10000] = {1,2,3};
int my_sub(int j)
{
	return x[j];
}
```
as long as the static linked version has a DT_INIT (readelf --dynamic libtest.so), which most C/C++ builders supply these days.  If not, then add an empty function which has the <tt>constructor</tt> attribute.

**Comment by pcheng74** [comment]
Hi Jreiser,

Thanks for your explaining. I will try to build the new sample to test UPX again.

Thanks,

**Comment by jreiser** [comment]
Using the <tt>devel</tt> branch, UPX does compress shared libraries for MIPS that are compressible.
