### ISSUE TITLE
SIGSEGV checking corrupted Mach-O file canPack

### ISSUE THREAD

**Issue by fanrong1992** [upx/upx#146]
## What's the problem (or question)?

SIGSEGV in upx when packing the segfault-macho input file in the attached 
[segfault-macho.tar.gz](https://github.com/upx/upx/files/1473545/segfault-macho.tar.gz).
PackMachBase<N_Mach::MachClass_64<N_BELE_CTP::LEPolicy> >::canPack (this=0x9b7030) at p_mach.cpp:1857
1857	        if (lc_seg == segptr->cmd) {
Accessing illegal memory in register rdx.

## What should have happened?

Program received signal SIGSEGV, Segmentation fault.

## How can we reproduce the issue?

1.upx segfault-macho
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 3.95-git-7a0514d9b427+
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43
* Host Operating System and version: Ubuntu16.04 linux4.4.0
* Host CPU architecture: x86_64
* Target Operating System and version: Mac OS 
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
<tt>devel</tt> branch now complains  <tt>segfault-macho: CantPackException: bad Mach_command[0]{0x19, 0x800048}</tt>

**Comment by carnil** [comment]
This issue has been assigned CVE-2017-16869

**Comment by jreiser** [comment]
This particular issue is equivalent to a compiler throwing a SIGSEGV instead of generating a polite error message upon detecting a syntax error in random input that was not previously touched by the compiler.  Assigning a CVE to this issue is incorrect; there is <b>NO SECURITY IMPLICATION WHATSOEVER</b>. There is <b>NO DENIAL-OF-SERVICE</b> opportunity that is exacerbated by UPX.  UPX Team <b>REJECTS</b> assigning any CVE for this particular issue https://github.com/upx/upx/issues/146 .
