### ISSUE TITLE
illegal exe header, but runs fine

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#169]
## What's the problem (or question)?

uncompressible exe
## What should have happened?

compressed exe
## Do you have an idea for a solution?

nope
## How can we reproduce the issue?

1.compress attached exe
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.94
* Host Operating System and version:10 64
* Host CPU architecture:x64
* Target Operating System and version:10 64
* Target CPU architecture:x64
[ect.zip](https://github.com/upx/upx/files/1606146/ect.zip)

**Comment by jreiser** [comment]
The file ect.exe has zeroes in bytes 2 and 3, and in bytes 4 and 5 [counting from 0.]  Together these two fields (as two "digits" in base 512) are supposed to give the offset of another header.  An offset of 0 is invalid because the other header would overlap the current header.  Please point to documentation about how to proceed in this case.

**Comment by necros2k7** [comment]
hmm, how can it be dos exe if it runs fine in 10 x64

**Comment by jreiser** [comment]
Apparently the intent is to overlap the MZ and PE headers as much as possible by setting the word at file position 0x3c to 0x10, so that the PE header begins at offset 0x10 and the RVA BaseOfCode at PE+0x2c also is 0x10.  OK, allow that.

**Comment by markus-oberhumer** [comment]
Should be fixed in 3.95.
