### ISSUE TITLE
Segmentation fault in higher compression rates

### ISSUE THREAD

**Issue by teras** [upx/upx#172]
## What's the problem (or question)?

Segmentation fault when compressing executables with option equal or greater than -4

## What should have happened?

When I select -1 -2 or -3, the executable compresses and runs fine. I was exepcting the same behaviour with larger options too.

## Do you have an idea for a solution?
Maybe due to aggressive decompiling?

## How can we reproduce the issue?
The executable was produced with the avian compiler : https://github.com/ReadyTalk/avian
I created a simple command line java application to test this feature, and as it is rather big, i.e. >2MB, and I know that it was used already in the past for similar purpose. I thought it had to do with the binary itself, but then I tried lower compression rates and it didn't work. The java application I was testing was this application: https://github.com/teras/jupidator/tree/master/core

I'll attach the binary as well to have a look if you wish.: [jupidator.zip](https://github.com/upx/upx/files/1617385/jupidator.zip)

## Please tell us details about your environment.
* UPX version used (`upx --version`):

 upx --version
upx 3.94
UCL data compression library 1.03
zlib data compression library 1.2.11

* Host Operating System and version: Arch Linux latest
* Host CPU architecture: intel arm 64

* Target Operating System and version: same
* Target CPU architecture:

**Comment by jreiser** [comment]
Thank you for attaching the jupidator.zip file.
Please try the <tt>devel</tt> branch of upx.  There has been a significant re-write for ET_DYN main programs in order to work correctly at runtime by making fewer assumptions about the layout of the address space.

If you still see a SIGSEGV, then please give the command line which reproduces the crash.  If you can, please run under a debugger such as gdb, and use the debugger to print info about the state at the time of the crash.  Such as:
```
(gdb) x/5i $pc   ## current and next instructions
(gdb) x/12i $pc-0x20   ## likelly previous instructins (heuristic)
(gdb) info reg   ## all registers
(gdb) info proc   ## includes PID process number
(gdb) shell cat /proc/PID/maps   ## address space mappings
```

**Comment by teras** [comment]
Thank you, this worked!
When are your plans to release a new version?
I am afraid the current "stable' version is worse stable than the "development" 😃
