### ISSUE TITLE
UPX wont compile with ucl 1.03 and cannot find any higher version available

### ISSUE THREAD

**Issue by mgood7123** [upx/upx#179]
## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
At least dozens of the 234 Forks (that GitHub reports) have compiled UPX with ucl-1.03; and the original report for this issue #179 gives no evidence and no environment details. 

Please tell us the name and version of the compiler, the host operating system and version where you are attempting to compile, and the CPU hardware architecture.  Please copy+paste a short transcript of a terminal session that shows a compiler error for <b>one</b> of the *.cpp source files. (Put a line containing three bactick characters [decimal 96, octal 0140, hex 0x60; often on the same key as tilde], and no other characters, both above and below the transcript when entering text on the Write tab.  That is the Markdown syntax that will make the transcript appear as a "block quote" so that it is easy to read.)

One layout which works is:
```
$ export UPX_UCLDIR=$HOME/ucl-1.03
$ ls $UPX_UCLDIR
acc         AUTHORS     config.log     COPYING   libtool      make.out  stamp-h1
acconfig    B           config.status  examples  Makefile     NEWS      THANKS
aclocal.m4  config.h    configure      include   Makefile.am  README    TODO
asm         config.hin  configure.ac   INSTALL   Makefile.in  src       upx
$ 
```

**Comment by jreiser** [comment]
Which compiler are you using?
The UPX autobuild harness reports succesful builds across a range of OS and compilers:

Build log for C=msvc-14.1-x64, CL_VERSION=19.12, VS_VERSION=2017:
https://ci.appveyor.com/project/markus-oberhumer/upx/build/job/exnka3vhlcr78a35

Successful outputs for 8 combinations of {x86, x64} x {versions 16, 17, 18, 19, 19.12 of MSVC}:
https://ci.appveyor.com/project/markus-oberhumer/upx

Successful outputs for 41 combinations of OS x {versions of clang(llvm), versions of gcc}:
https://github.com/upx/upx-automatic-builds/tree/devel-20180202-95cedb6-travis

**Comment by jreiser** [comment]
No evidence has been presented to support the claim.
