### ISSUE TITLE
[QUESTION] How to interpret the crash dumps after packed by upx ?

### ISSUE THREAD

**Issue by nezen** [upx/upx#180]
I have a so lib for Android packed by upx. If I'm not wrong, crash dumps will be altered after packed by upx, so my question is how to  interpret these altered crash dumps? Thanks.

**Comment by jreiser** [comment]
First of all, for a .so shared library only the the PT_LOAD .text segment can be compressed.  Even then, Sections at lower addresses than the first one that is marked SHF_EXECINSTR cannot be compressed.  The reason for this is because the runtime linker dlopen() performs relocation processing on a .so before calling the library's DT_INIT, which is the "hook" for decompression.  So anything that the runtime linker touches before calling DT_INIT cannot be compressed.  Everything in the memory image has the same address as it would if the uncompressed .so were used at the same base address.  The symbols that are available to dlopen() are there, too.  Unfortunately, some debuggers and crash analyzers do not deal with DT_SYMTAB; instead they look only at SHT_SYMTAB.  They should learn.  Or, you might be able to (have to) convince them that the uncompressed .so was present at the same base address as the compressed .so.  [The utility command <tt>readelf --headers <i>my_lib.so</i></tt> prints the raw data that is necessary to understand much of what is gong on.]

There is an exception for --android-shlib.  The Android runtime linker does it <b>all wrong</b> by demanding properties of the ElfXX_Shdr, which is a violation of the ELF API: using the <i>linking view</i> (ElfXX_Shdr[])at run time instead of only the <i>execution view</i> (ElfXX_Phdr[]).  In order for compression to work at all in such a broken environment, UPX inserts an extra copy of the ElfXX_Shdr[] as the contents of a 4KiB page in the "middle" of the .text segment, immediately before the first Section that is marked SHF_EXECINSTR.  Of course, this means that UPX must adjust all the relocations.  Again, if the debugger or crash analyzer works from DT_SYMTAB, then there should be no problem.  If it works from SHT_SYMTAB, then it will get lost.  Too bad: fix the broken Android software.

If the crash happens during decompression, then that's a bug in UPX.  Please run under gdb and report:
```
(gdb) x/5i $pc  # current and next instructions
(gdb) x/12i $pc-0x20  # likely preceding instructions
(gdb) info reg  # all general registers
(gdb) x/20xw $sp  # memory at active end of stack
(gdb) info proc  # process information
(gdb) shell cat /proc/PID/maps  # memory maps; PID is process ID from "info proc"
```

**Comment by nezen** [comment]
Thanks for your very detailed explanation !
