### ISSUE TITLE
0CC-FamiTracker.exe failed to launch after upx compressed

### ISSUE THREAD

**Issue by owomomo** [upx/upx#182]
## What's the problem (or question)?

0CC-FamiTracker.exe failed to launch after upx compressed, the OS reports it's not a valid Win32 application.
## What should have happened?

I'm not sure what causes the problem, since it only happens on the newest GIT version of the 0CC-FamiTracker code.
## Do you have an idea for a solution?

No, I don't.
## How can we reproduce the issue?

1. Compile the newest git code of 0CC-FamiTracker with Visual Studio 2017 (15.5.3). 
2. Compress the created 0CC-FamiTracker.exe with UPX 3.94
3. Try to run the compressed exe file.
4. The system responses "not a valid Win32 executable"
I have tried from Windows XP to 10, they all have the same result. 
The newest code of 0CC-FamiTracker can be found on [https://github.com/HertzDevil/0CC-FamiTracker](url), it uses Visual Studio 2017, the Window SDK version is set to 8.1 and v141_xp.
## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version:Windows 10
* Host CPU architecture:x86
* Target Operating System and version:Windows 10
* Target CPU architecture:x86

**Comment by Mattiwatti** [comment]
This was fun to debug :)

The kernel (the actual kernel, not `kernel32.dll`) fails the process create system call with `STATUS_INVALID_IMAGE_PROTECT`, which translates to the Win32 error `ERROR_BAD_EXE_FORMAT`.

ntstatus.h:
```

// The specified image file did not have the correct format,
// it did not have a proper e_lfarlc in the MZ header.
//
#define STATUS_INVALID_IMAGE_PROTECT	 ((NTSTATUS)0xC0000130L)
```

Well that's a pretty clear error right? Hm, wait, `e_lfarlc` is `0x40` as it should be (and it is the same in the original exe)...

It turns out there are actually at least 15 different code paths in various functions in the kernel that can return `STATUS_INVALID_IMAGE_PROTECT`! Most of them have nothing to do with `e_lfarlc` or even the DOS header. And I even cheated by using Windows XP for easier debugging, there are probably more in newer Windows versions.

Anyway, to make a long BSOD story short, the actual cause is an exception that occurs when probing the `IMAGE_LOAD_CONFIG_DIRECTORY` (the kernel does this to validate user space buffers) - specifically, an alignment exception. The kernel expects the load config directory to be DWORD-aligned, but it is only aligned to a word boundary. See the attached ZIP, where the RVA of the broken exe (itself stored at `+0x1E8`) is `0x4B13FA`. The second exe has a fixed load config RVA of `0x4B13FC`, and of course the directory itself (`0xA0` bytes at offset `+0x12E7FA`) moved forward by 2 bytes. Now it works.

[0CC-FamiTracker-x86.upx.zip](https://github.com/upx/upx/files/1756881/0CC-FamiTracker-x86.upx.zip)

Above file is 32 bits and compressed with UPX 3.94, but this also happens with the x64 version of the same program using the latest UPX sources from `devel`.

OP, if you're looking for a quick and dirty way to fix this, you can simply remove the configuration directory with CFF Explorer before running UPX. This will break SEH support on x86, but is essentially harmless on x64 unless you care about stuff like stack cookies and CFG.

**Comment by owomomo** [comment]
The problem was mysteriously solved after recompile the newest updated code... it seems the bug was quite random and it's so hard to catch.

**Comment by Mattiwatti** [comment]
Yeah... unfortunately I don't know enough specifics about UPX internals to say anything about what the cause might be there. But it is definitely some edge case, because if UPX frequently misaligned directories in PEs, there wouldn't be a whole lot of UPX code running in the wild ;)
