### ISSUE TITLE
why rebuildTls is do nothing

### ISSUE THREAD

**Issue by yajiedesign** [upx/upx#188]
## What's the problem (or question)?
my compress some dll.when i load it,some  access error in LdrpAllocateTlsEntry
I see the rebuildTls is empty.

## What should have happened?
DLL should be loaded normally.

## Do you have an idea for a solution?
no

## How can we reproduce the issue?
download dll in https://github.com/yajiedesign/mxnet/releases
upx it.
load it.

## Please tell us details about your environment.
* UPX version used (`upx --version`):upx 3.94
* Host Operating System and version:windows 10
* Host CPU architecture:x64
* Target Operating System and version:windows 10
* Target CPU architecture:x64

**Comment by jreiser** [comment]
Please provide a test case.

**Comment by yajiedesign** [comment]
@jreiser you can download error dll in https://github.com/yajiedesign/mxnet/releases

**Comment by Mattiwatti** [comment]
[For reference, I used [20180315_mxnet_x64_vc141_gpu_cu90.7z](https://github.com/yajiedesign/mxnet/releases/download/20180315/20180315_mxnet_x64_vc141_gpu_cu90.7z) to reproduce this - SHA1 hash of `libmxnet.dll` is `a622be344caeaecde8bd3f482718e74286a29449`.]

Firstly I have to say I am extremely impressed with this file. Not only is it the biggest PE file I have ever seen by an order of magnitude - it's bigger than many operating systems, and a number of hard disks I owned as a kid! I should also mention I actually had to recompile UPX to remove the safety limits on memory usage to even be able to reproduce this issue; it plain refused to compress the file otherwise.

Anyway, as much as I'd love to blame your **740 (seven-hundred-and-forty) MB DLL file**, the problem is actually related to the use of TLS. (Specifically the TLS initializers used by the MSVC runtime, not thread-local storage itself.) You can verify this by using CFF Explorer to open the file (note that it will warn you when it discovers that the file is _bigger than 40 MB_ - it may be trying to subtly tell you something...) and removing the TLS directory. The access violation will now be gone. You can do this before or after compressing with UPX, either will work. This will almost certainly kill your DLL regardless by causing some other crash later on due to the TLS variables not being properly initialized, but that's to be expected.

I cloned your repository to compile a less insane version than the one in the link above, and arrived at a 37 MB DLL that had the same issue, so as far as I can tell it's not related to filesize but something else to do with the TLS callbacks. Note that several other DLLs in the dependency chain of your... thing... (`libgcc_s_seh-1.dll` x2, `libquadmath-0.dll` x2, `libgfortran-3.dll` x2 and `libopenblas.dll` x2) have TLS callbacks of their own that all run before your planet-sized DLL gets a chance, so UPX may be triggering some unwanted interactions or a change of callback order between these. That's just a guess though.

TLS callbacks are a really unfortunate hack in the Windows loader that have pretty much always been around, but either the UCRT or VS2015 (I forget which) is responsible for adding this to PE files as a 'legitimate' way to safely initialize `thread_local` variables when those were introduced. The guilty source files actually ship with MSVC: they are `tlssup.cpp`, `tlsdyn.cpp` and `tlsdtor.cpp`. As you can see they don't actually do anything at all during the initial callback - the callbacks are only there for the purpose of making sure the PE has a TLS directory that references them. The functions are called a second time for the 'real' TLS initialization once normal CRT startup is already well on the way.

My advice is to steer clear from MSVC CRTs newer than VS2015, and the UCRT even more so. If you absolutely must use them, don't use `thread_local` or any of the variants that mean the same thing. It might not fix this bug but it'll save you a ton of headaches in the future.

###### ...740 MB...

**Comment by yajiedesign** [comment]
Thank you very much. It was learned from the companion that TLS was used in large quantities.
I'm now thinking about self compression.
