### ISSUE TITLE
Can some one add support Android .so libraries to UPX

### ISSUE THREAD

**Issue by ChD1** [upx/upx#191]
## What's the problem (or question)?

When upx packing android .so library without init section it drop exception ( https://github.com/upx/upx/issues/74 ). But it very small count .so libraries have init section. And if i want decrease size of application without source code i can't. 

I try add _init section without sources to so library, but upx don't work with it.
I put my work to cloud: 
https://cloud.mail.ru/public/FbAq/X3WctdDRm
elf.py - Python script to add init section to so file without sources.
There is 3 lib:
lib0 - library without init
lib1 - library with init
lib0__ - library with added init section. (Upx can't handle it)
*.txt - readelf output.

## What should have happened?

Maybe some one can add upx support libraries without _init section? (Android so have "Java_*...*_initsectio") Maybe it possible to find and use this section for packing?   

## Do you have an idea for a solution?

I think upx can use Java_*...*_initsectio for compression

## How can we reproduce the issue?

Not issue.

## Please tell us details about your environment.

latest

**Comment by jreiser** [comment]
Here's one possibility.  The PT_DYNAMIC segment (same memory as the SHT_DYNAMIC Section) often ends with 5 struct Elf32_Dyn having .d_tag==DT_NULL; this is an un-advertised default (with no option to change it) in the static binder /bin/ld.  One DT_NULL is required for convenience in detecting the end, and this is used by all processing.  The other four are for pre-linking (/usr/bin/prelink) which reserves them to keep track of assumptions and to record what happened (DT_GNU_PRELINKED, etc.)  However, pre-linking often is unused because it is somewhat cumbersome and in conflict with ASLR (Address Space Layout Randomization to deter malware.)  So take the first DT_NULL and change it to DT_INIT; set .d_val to the address of some existing RETurn instruction in .text.
Of course upx could do this. I'll add it to the list of things to do, but someone else might do it sooner.
If DT_INIT_ARRAY is present (or DT_PREINIT_ARRAY) then upx could "hook" the first element; I'll put that on the list of things to do, too.

**Comment by jreiser** [comment]
For a shared library, the runtime dynamic loader performs some work before the upx stub in the library has a chance to run.  Therefore anything that the runtime dynamic loader might modify (relocate) cannot be compressed.  In practice only [most of] the .text, and none of the .data, can be compressed.  For the 100KB lib0.so that you posted, then the savings will be about 35KB to 40KB.

**Comment by ChD1** [comment]
This is normal. Even if the library size after the upx is larger than the original, this is very good. Upx is not only an excellent packer of executable files, but also a tool for obfuscating the code. Some protection against reverse and analysis. This function is very necessary. Especially lib0.so is a test library with a minimum of code. In other applications, libraries are larger.

**Comment by jreiser** [comment]
Please try the <tt>devel</tt> branch.  Remember to use <tt>--android-shlib</tt>.

**Comment by ChD1** [comment]
Everything is working! I checked on several libraries, no problems! Thank you very much!

**Comment by twlkyao** [comment]
> Please try the devel branch. Remember to use --android-shlib.

The size of the so files are smaller by using upx, but after compiled to apk, the size of so files are bigger than those without upx, is this is the default of using upx.

**Comment by jreiser** [comment]
@twlkyao Please upload ("Attach files by ...") an actual shared library which fails.  Give the details of the apk crash: the log, the messages, the register values, the traceback.  Show the sizes before and after upx compression, and "after compiled to apk".
If you cannot upload a shared library, then show the output from "readelf --headers --segments --sections my_lib.so".  To make the output readable here in github, then place a line which contains three backtick characters only (decimal 96, octal 0140, hex 0x60) just before and just after the pasted output.
