### ISSUE TITLE
Can not find dynamic dependence after modifying RPATH of an executable

### ISSUE THREAD

**Issue by rhuab** [upx/upx#202]
## What's the problem (or question)?
On Centos-4,  I use UPX to pack an executable whose rpath is modified by pathelf-0.9, then I find that this executable can not find the libraries at that rpath.

## What should have happened?
This executable should find the libraries at that rpath because I can not reproduce this bug on Ubuntu16.04, CentOS-5, CentOS-6, CentOS-7.

## Do you have an idea for a solution?
None

## How can we reproduce the issue?
1. Download pathelf-0.9 and compile this project, then a "patchelf" command is generated.
2. Prepare an executable "E" that have dynamic libraries (Glibc libraries should not be counted in).
3. Execute "patchelf --set-rpath /path/to/directory1:/path/to/directory2 /path/to/E" to modify E, the new rpath must be longer than the original and it can not be system default library searching path.
4. Put dynamic dependence of E in directory1 or directory2 and executable E, then E should crash because it can not find the libraries it needs.
5. All above procedures is taken on Centos-4.

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.95
* Host Operating System and version: CentOS-4
* Host CPU architecture: x86_64
* Target Operating System and version: CentOS-4
* Target CPU architecture: x86_64

**Comment by jreiser** [comment]
Same as https://github.com/upx/upx/issues/47 .
Add your voice to the request of /bin/ld to implement --padXYZ=nnn.

**Comment by rhuab** [comment]
I don't know what you mean by "--padXYZ=nnn". My ld is binutils-2.26, it does not have this option or something like that. Could you explain further?

**Comment by jreiser** [comment]
As in https://github.com/upx/upx/issues/47#issuecomment-271091431 : 
If you're really interested in compressing -pie executables that have been modified by patchelf, then you should ask the maintainers of /usr/bin/ld to support three new options: "--pad-PHDR=number", "--pad-DYNAMIC=number", and "--pad-STRTAB=number" which leave space at the end of the indicated regions. [Compare "-headerpad=number" on MacOS.] Then patchelf won't have to turn handsprings, and UPX can be less complex. [Note that already /usr/bin/ld silently implements the equivalent of --pad-DYNAMIC=4*sizeof(ElfXX_Dyn)" so that prelink can work.]
