### ISSUE TITLE
flashplayer_29_sa.exe works after first compression but not when decompressed

### ISSUE THREAD

**Issue by FRex** [upx/upx#204]
## What's the problem (or question)?
The flashplayer_29_sa.exe (standalone 32 bit Flash player from Adobe) works after being compressed with upx with no flags for the first time but then stops working after the first decompression with a seg fault (further compressions and decompressions don't change that).

## What should have happened?
It should decompress into a working exe or refuse to pack it in the first place if it can't then unpack it back into a file (even if it still runs when packed for the first time).

## Do you have an idea for a solution?
No.

## How can we reproduce the issue?
1. Go to [https://www.adobe.com/support/flashplayer/debug_downloads.html](https://www.adobe.com/support/flashplayer/debug_downloads.html).
2. Under Windows section pick "Download the Flash Player projector" to download `flashplayer_29_sa.exe`.
3. Run `upx flashplayer_29_sa.exe -o comp.exe`
4. Run `upx -d comp.exe -o decomp.exe`
5. `flashplayer_29_sa.exe` and `comp.exe` work, `decom.exe` causes a seg fault.

## Please tell us details about your environment.
* UPX version used (`upx --version`): upx 3.94 NRV data compression library 0.84 UCL data compression library 1.03 zlib data compression library 1.2.3 LZMA SDK version 4.43
* Host Operating System and version: Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
* Host CPU architecture: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 CPUs), ~2.8GHz
* Target Operating System and version: same.
* Target CPU architecture: same, but flashplayer_29_sa.exe is a 32-bit exe.

**Comment by Mattiwatti** [comment]
This is caused by the relocation directory being removed (regardless of any `--strip-relocs` setting). The UPX stub has its own tiny relocation directory, which is enough to prevent the compressed executable from crashing, although the unpacked image will always have the same base address.

When the packed exe is decompressed, the stub relocation directory too is removed and now there isn't one left. Except for very simple executables, a relocatable PE will always have a relocation directory, so this is a sure sign something is going to go wrong when running the file.

Note: you can 'fix' this manually with a hex editor if you really need to for some reason, but keep in mind that this will not actually make the image relocatable like the original, it will merely stop it from crashing.
1. In the PE file header, set `Characteristics |= IMAGE_FILE_RELOCS_STRIPPED` aka `0x1`.
2. In the PE optional header, set `DllCharacteristics &= ~IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE` aka `0x40`.

Either of those will work (one is enough). I don't think there's any benefit to either method, so I would go with the one that best describes what actually happened (1).

**Comment by FRex** [comment]
I don't need it but I ran across this problem when playing with UPX to see how well it compressed various exes and reported it because I thought it's not normal/intended behavior and that the bug might interest the developers.

**Comment by necros2k7** [comment]
Have a side problem of compressing latest resulting Projector.exe - white screen instead of SWF playing.)
