### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by floion** [upx/upx#212]
## What's the problem (or question)?
Are there any plans for a new release anytime soon?

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by floion** [comment]
@markus-oberhumer the problem is that when using the latest version, 3.94, and compressing a rust binary on x86 architecture, when running that compressed rust binary it segfaults.
Instead, if using the devel branch of UPX then the binary runs fine. So the fix for the issue is in the devel branch

**Comment by floion** [comment]
Re-ping on this please?

**Comment by jreiser** [comment]
What is so important to you about having an official release versus just using current <tt>devel</tt>?  The default compression in a release is NRV;  in a built-by-you <tt>devel</tt>, you get UCL, and the difference usually is a couple percent larger in space with no difference in run speed or inter-operability. (NRV tends to provide more evidence if someone tampers with the output.) If the space matters, then <tt>--lzma</tt> compression usually is at least 5% to 10% smaller than NRV; but de-compression at runtime is slower.

**Comment by agherzan** [comment]
@jreiser we experience a very strange issue where on two identical machines the same rust binary behaves differently when compressed with UPX: it segfaults on one and it works fine on another. Both run exactly the same BSP. The userspace has the same version for packages but different distro (custom set of packages based on yocto).

The binary is a rust one and using the devel branch fixes the issue. gdb says:

```
(gdb) r
Starting program: /usr/bin/os-config 
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dd2e40 in ?? ()
```

Do you have any idea what would be the issue here? It is important for us to work on a stable version because we use this in production and that's why we requested a new version.

**Comment by jreiser** [comment]
Please clarify the environment.  For this comment I assume: "two identical machines" means that the hardware is the same;  "same rust binary" means that the two main programs and any shared libraries <b>cmp</b> equal; "same BSP" means "same Board Support Package firmware"; "the userspace has the same version for packages" means that the package names including version numbers are the same, but they may have been compiled by different compilers [different compilation ofthe run time dynamic linker ld.so (part of glibc) might make a difference]; "different distro" means the Linux kernel is different.  Please run "uname -a" in each case, then copy+paste the results here.  Also please copy+paste the entire output from "cat /proc/self/maps" on each machine.  Also please copy+paste the output of "readelf --headers <i>compressed_rust_binary_executable</i>".

Different kernels implement different strategies for placement of kernel-supplied regions such as [stack], [vdso], [vvar], [vsyscall].  In the past upx made some assumptions that those pages would not interfere with upx.  The <tt>devel</tt> branch no longer makes such assumptions, so is more robust across different Linux kernels.

It is unpredictable when there will be a new release of upx.  If some particular commit on <tt>devel</tt> branch works for you then use it.

**Comment by agherzan** [comment]
As well when it segfaults, process memory map looks like this:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dd2e40 in ?? ()
(gdb) info proc       
process 1499
cmdline = '/tmp/os-config.upx'
cwd = '/tmp'
exe = '/tmp/os-config.upx'
(gdb) shell cat /proc/1499/maps
00400000-00600000 rwxp 00000000 00:00 0 
7ffff7773000-7ffff7a28000 r-xp 00000000 00:00 0 
7ffff7a28000-7ffff7c27000 ---p 00000000 00:00 0 
7ffff7c27000-7ffff7c39000 rwxp 00000000 00:00 0 
7ffffffde000-7ffffffff000 rwxp 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

**Comment by jreiser** [comment]
I notice that working image was run on Linux resin 4.12.21-yocto-standard #2 SMP PREEMPT Mon Aug 6 15:31:39 UTC 2018, while the broken image was run on Linux localhost.localdomain 4.12.21-yocto-standard #3 SMP PREEMPT Wed Aug 8 16:33:27 UTC 2018, so there is a difference of "#2" versus "#3" which was built 2 days later.  Perhaps more significant, the working <tt>cat</tt> is /bin/cat.coreutils while the broken one is /bin/busybox.nosuid which is not the same.  The different <tt>cat</tt> still should be a minor consideration for now.

In the segfault, notice that [var] and [vdso] are missing in contrast to the memory mappings of the two <tt>cat</tt>.  Also notice that the $pc of 0x00007ffff7dd2e40 has no mapping at all.  An early Comment says that upx-3.94 was used.  The <tt>devel</tt> branch has some fixes for bugs of erasing kernel-provided regions such as [var] and [vdso].  Please try running the tip of <tt>devel</tt> branch.

**Comment by agherzan** [comment]
The changes in the broken image in terms of tools are just due to the fact that I added a lot of debugging tools on that image to be able to investigate. They in turn dragged other tools but nothing change any behavior. As well, the kernel was just recompiled at some point. Can't remember why but again, nothing changed the behavior. If you want to be sure, I can retest with exactly the same tools and kernel version and provide logs. 

We did try the devel branch and it works fine. The idea was to use a stable version or find the issue and patch 3.94. We use this tool on many architectures/boards and we don't want to risk breaking any of them due to using a development branch.

Another interesting fact. When using gdb both of the images fail. They segfault at an unmapped address. Which makes me think that the runtime segfault when using the debugger and when not using it, might be completely different.

**Comment by jreiser** [comment]
@agherzan   If you are interested in patching v3.94 to deal with this particular problem, then look at the commits that modify src/stub/src/amd64-linux.elf-entry.S, particularly including  402c88598754efa41828734f149600ef5bf34d72 of 2017-10-14 14:26:11, "Merge branch 'jreiser-elfsub' into devel":
```
New stub strategy on Linux:  Linux adds too many other segments
    to the address space: [vdso], [sigpage], ...; and qemu might
    arrange them differently.  Thus the only reliable mappings
    are the PT_LOAD of the compressed file itself; all other
    address space is unknown!  [snip]
```
@limburgher  Please try branch <tt>devel</tt> which contains fixes for problems with the layout of address space during run time de-compression, which can vary according to the whim of the Linux kernel. If <tt>devel</tt> does not work then please upload a test case ("Attach files by ..."), or otherwise give info such as the output from <tt>readelf --headers a.out</tt>, plus the contents of machine registers <tt>(gdb) info reg</tt> and address-space mappings <tt>(gdb) info proc; (gdb) shell cat /proc/PID/maps</tt> at the time of a crash.

**Comment by limburgher** [comment]
When I tar up devel and try to use it in the rpm build, the build fails:
+ UPX_LZMA_VERSION=0x465
+ UPX_LZMADIR=/usr/include/lzma465
+ make -C src
make: Entering directory '/home/limb/fedora/git/upx/upx-devel/src'
../src/stub/src/c/Makevars.lzma:12: *** ERROR: missing directory src/lzma-sdk/; visit https://github.com/upx/upx-lzma-sdk .  Stop.

**Comment by jreiser** [comment]
@limburgher Yes, lzma is an external dependency of upx, and the message tells where to find it.  For convenience I attach the indicated version, compressed again with gzip to please github.
[lzma465.tar.bz2.gz](https://github.com/upx/upx/files/2278583/lzma465.tar.bz2.gz)

**Comment by limburgher** [comment]
We already ship it in Fedora, and use the packaged version. The build commands reflect this.

**Comment by jreiser** [comment]
The <tt>devel</tt> branch works for me when running Fedora-Workstation-Live-x86_64-Rawhide-20180808.n.1.iso (2 days old).  I took /bin/date from Fedora 28, compressed it, copied it to Live-Rawhide, and ran it successfully.
Please upload (or point to) a failing test case.

**Comment by limburgher** [comment]
I tested /usr/bin/curblaster, and others.

*disclaimer, it's in Fedora but I'm also upstream.

**Comment by jreiser** [comment]
upx from the tip of <tt>devel</tt> branch now works for me on /usr/src/curblaster from current "rawhide" for Fedora 29.

**Comment by DanielRuf** [comment]
Last release was almost a year ago. Would love to see some beta releases so we can test prepackages / prebuilt releases.

Can this be automated using CI?

**Comment by jreiser** [comment]
There is CI; see https://github.com/upx/upx-automatic-builds .  Every commit which mentions an Issue is auto-posted to that Issue, with a link to the build status.  For example, see https://github.com/upx/upx/commit/90eb68b3b9da914d5e1bdcb532eec2a1ff110533 of https://github.com/upx/upx/issues/212#issuecomment-412713969 on Aug.13.

**Comment by limburgher** [comment]
I can't use a CI binary for Fedora. If there won't be a release soon, what process should I use to make a git clone into the equivalent of a release src tarball?

**Comment by jreiser** [comment]
Set the shell environment variables UPX_LUADIR, UPX_LZMADIR, UPX_LZMA_VERSION, and UPX_UCLDIR, where each *DIR variable names a directory in which the corresponding external component has been built already.   For instance:
```
export UPX_LUADIR=$MYDIR/lua-5.1.1
export UPX_LZMADIR=$MYDIR/lzma457
export UPX_LZMA_VERSION=0x457
export UPX_UCLDIR=$MYDIR/ucl-1.03
```
In the top-level upx directory (the directory that contains the file 'NEWS') do <tt>make all</tt>.  The result you want is src/upx$(exeext) which for a Linux system is src/upx.out.  The result will be functionally equivalent to an official release [<tt>upx.out --version</tt> will report a git commit], but the unofficial default compression algorithm of UCL produces slightly larger executables than the offical default compression NRV; the explanation is in README.SRC.  (Optional <tt>--lzma</tt> compression will be the same.)

There are rumblings of an official release soon, probably in a small number of weeks.

**Comment by limburgher** [comment]
../src/stub/src/c/Makevars.lzma:12: *** ERROR: missing directory src/lzma-sdk/; visit https://github.com/upx/upx-lzma-sdk .  Stop.
I still get: ../src/stub/src/c/Makevars.lzma:12: *** ERROR: missing directory src/lzma-sdk/; visit https://github.com/upx/upx-lzma-sdk .  Stop.

**Comment by markus-oberhumer** [comment]
A new release will happen soon.

Also please don't forget about https://github.com/upx/upx-automatic-builds if you want to test pre-built binaries of the latest devel version.

**Comment by markus-oberhumer** [comment]
Release 3.95 is done.

**Comment by floion** [comment]
Thanks @markus-oberhumer
