### ISSUE TITLE
newest version still unusable for executes created by Embarcadero RAD Studio

### ISSUE THREAD

**Issue by mdlem** [upx/upx#223]
## What's the problem (or question)?

It is still impossible to use upx (3.95) to compress executables created by Embarcadero RAD Studio:
**upx: test.exe: InternalError: should not happen** 

## What should have happened?

current version should be able to compress these executables as upx version til 3.91 did.

## Do you have an idea for a solution?

no.

## How can we reproduce the issue?

1. Download https://1drv.ms/u/s!AqWTfvr8SckDg9A-_VcY6lDcy2GYog
2. Try to compress it by upx
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.92 - 3.95
* Host Operating System and version: Windows 10 Prof.
* Host CPU architecture: x86_64
* Target Operating System and version: Windows 10 Prof.
* Target CPU architecture: x86_64

**Comment by Mattiwatti** [comment]
This is caused by:

1. Embarcadero's embarrassingly broken linker, which outputs PE files with empty import directory entries. This is not invalid per se, just pointless and a complete waste of space.
2. Commit [9cb639b](https://github.com/upx/upx/commit/9cb639b5059e3b05b2a90dc7952b4aa9aa4990b6), which added the exception you are seeing. Versions of UPX before this commit will work with these files.

There are two ways to fix this:
1. Throw away the empty import directory entries. Implemented in [https://github.com/Mattiwatti/upx/tree/fix-0imports-destructive](https://github.com/Mattiwatti/upx/tree/fix-0imports-destructive).
2. Keep the empty import directory entries. Implemented in [https://github.com/Mattiwatti/upx/tree/fix-0imports-preserve](https://github.com/Mattiwatti/upx/tree/fix-0imports-preserve).

Here is a zip containing binaries for both: [upx-0imports-fix.zip](https://github.com/upx/upx/files/2568912/upx-0imports-fix.zip).
And a test file with 32 and 64 bit exes of a sample I compiled with the garbage linker: [broken-inputs.zip](https://github.com/upx/upx/files/2568915/broken-inputs.zip).

**Comment by joachimmarder** [comment]
@mdlem: Which RAD Studio version are you using?

**Comment by mdlem** [comment]
@joachimmarder : XE3 and 10.2.2

**Comment by photo4print** [comment]
> This is caused by:
> 
> 1. Embarcadero's embarrassingly broken linker, which outputs PE files with empty import directory entries. This is not invalid per se, just pointless and a complete waste of space.
> 2. Commit [9cb639b](https://github.com/upx/upx/commit/9cb639b5059e3b05b2a90dc7952b4aa9aa4990b6), which added the exception you are seeing. Versions of UPX before this commit will work with these files.
> 
> There are two ways to fix this:
> 
> 1. Throw away the empty import directory entries. Implemented in https://github.com/Mattiwatti/upx/tree/fix-0imports-destructive.
> 2. Keep the empty import directory entries. Implemented in https://github.com/Mattiwatti/upx/tree/fix-0imports-preserve.
> 
> Here is a zip containing binaries for both: [upx-0imports-fix.zip](https://github.com/upx/upx/files/2568912/upx-0imports-fix.zip).
> And a test file with 32 and 64 bit exes of a sample I compiled with the garbage linker: [broken-inputs.zip](https://github.com/upx/upx/files/2568915/broken-inputs.zip).

but it doesn't work...

**Comment by Mattiwatti** [comment]
@photo4print What doesn't work? Do the exes in the zip not work (they do for me) or do the fixed UPX versions not work on some other executable of yours? If the latter, please attach the input file so I can have a look.

**Comment by alank2** [comment]
I too have the issue with Embarcadero 10.3.1 with UPX newer than 3.91.

I tried your two executables (destructive/preserve) and both work on an empty forms application and both work on a complete forms application.

How to best move forward?  Could an option be added to preserveimports or something in future releases for this case?

**Comment by jreiser** [comment]
Same as https://github.com/upx/upx/issues/375 .
