### ISSUE TITLE
Windows binaries compiled with the LDC compiler cannot be executed

### ISSUE THREAD

**Issue by LaurentTreguier** [upx/upx#228]
## What's the problem (or question)?

For a bit of background to the problem:
The D programming language mainly has 2 compilers to compile Windows D programs: the reference compiler, DMD, and another one using LLVM, LDC.
On Linux, compressing binaries with either compiler poses no problem (which is great already, kudos to all the contributors for this project !). On Windows however, while compressing an executable that was compiled with DMD works fine, compressing an executable that was compiled with LDC results in an executable that Windows refuses to launch (at least, on my system).
Windows simply shows this message, "This application cannot be executed on your PC", seemingly as if Windows didn't recognize the binary format:
![upx-issue](https://user-images.githubusercontent.com/7602755/47445011-2173ed80-d7b8-11e8-9c14-15cf16b78c30.PNG)
I have tried compiling both a x86 and a x86_64 binary, with the same result.

## What should have happened?

Compressing an executable that was compiled with the LDC compiler should provide a binary that can be executed by Windows.

## Do you have an idea for a solution?

None, other than adding this to the `BUGS` file

## How can we reproduce the issue?

1. Download the latest version of LDC (https://github.com/ldc-developers/ldc/releases)
2. Create a simple Hello World program in D by saving the following code in a file named `hello.d`
```d
import std.stdio;
void main()
{
    writeln("Hello, UPX !");
}
```
3. Compile the file using LDC on the command line: `C:\path\to\ldc\installation\bin\ldc2.exe hello.d`
4. Check that the produced executable does work beforehand, just to be sure: `.\hello.exe` should output `Hello, UPX !` (obviously)
5. Compress with upx: `C:\path\to\upx\installation\upx.exe hello.exe`
6. Try to run the `hello.exe` executable once again

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95
* Host Operating System and version: Windows 10 Home (build 17763.104)
* Host CPU architecture: x86_64
* Target Operating System and version: Windows 10 Home
* Target CPU architecture: x86_64

**Comment by Mattiwatti** [comment]
I don't know the solution for this (sorry), only the cause :)

I reproduced your sample and the RVA of the load configuration directory of the PE file (the UPX'd one, that is) is misaligned. For me, the RVA is `0x84FE9` which corresponds to file offset `0x271E9`. Fortunately, the load config directory of the file is completely empty except for the size, so I adjusted the RVA by `-1` to `0x84FE8` and put the size field there as well. This fixed the error.

For the UPX devs: the PE directory RVAs must be dword aligned on x86, and quadword aligned on x64. Otherwise you will get this error. (On Windows 7, I get "hello.upx.exe is not a valid Win32 application". Very helpful...)

As for why this happens for files produced by the LDC compiler in particular... I can't say. There is nothing wrong with the original PE file as far as I can detect.
