### ISSUE TITLE
Latest autobuild regression - doesn`t support wildcards (ie. pack all *)

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#239]
subj

**Comment by jreiser** [comment]
The Description lacks:
1) A complete statement of the problem, including the actual command line, the actual results, and the expected results.  (For instance, "pack all *" is not a valid command line to invoke UPX.)
2) Details of the target system (what kind of files are in "*") and host system (where was upx run?)

The UPX Issue template provides prompts.  Please use it and respond appropriately, so that Issues are worth investigating.
