### ISSUE TITLE
Can UPX pack .ko files which are kernel modules?

### ISSUE THREAD

**Issue by hitsjt** [upx/upx#255]
## What's the problem (or question)?

I tried to use upx3.9.5(amd64version) to pack .ko files from both intel and mips platform.But both failed.
upx reported "UnknownExecutableFormatException".

## What should have happened?

I think upx should also work on .ko files.

## Do you have an idea for a solution?

Sorry,I don't.

## How can we reproduce the issue?

1.Just use upx to pack any .ko file for example "8021q.ko".
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.9.5
* Host Operating System and version:Ubuntu 16.04 x86_64
* Host CPU architecture:Intel
* Target Operating System and version:linux
* Target CPU architecture:MIPS  and MIPSEL

**Comment by jreiser** [comment]
A .ko file has Elf32_Hdr.e_type==ET_REL (/usr/include/elf.h) but UPX handles only ET_EXEC and ET_DYN files.  Also, the run-time de-compression mechanism requires a transfer of control to the module, and at an "opportune" time. Although the __init function of a .ko meets some of that  requirement, the kernel module loader already has processed all the ElfXX_Rel information, which results in touching quite a lot of the rest of the file.  In order to compress those bytes, then the upx-de-compressor would have to emulate most of the functionality of the Linux kernel module loader.  This is a large effort, and unlikely to happen soon.
It is imagined that most practical uses would be specific to individual machines.  Therefore it would be better to work on a way to un-compress and statically bind a "stock" vmlinuz kernel with the specific .ko modules for that machine, producing a new vmlinux which could be compressed by any one of multiple kernel compressors into a machine-specific vmlinuz.

**Comment by jreiser** [comment]
Besides, the kernel module loading eco-system already handles .ko.gz; see `CONFIG_MODULE_COMPRESS=y` and search the 'net for `linux .ko.gz`.
