### ISSUE TITLE
Using upx for ramdisk binaries

### ISSUE THREAD

**Issue by axos88** [upx/upx#263]
## What's the problem (or question)?

Is using upx for executables that are stored in a ramdisk (embedded system that boots to RAM) a good idea? Obviously the image size is going to be reduced, but won't the system need to store the compressed and decompressed version of the binary in RAM in order to be able to run it? Or it can decompress as pages from the binary become required, store it as buffer, and then page it out? 

I'm asking because I'm not entirely sure what "in-place decompression" means.

## Please tell us details about your environment.

* UPX version used 3.95
* Host Operating System and version: OS X
* Host CPU architecture: x64
* Target Operating System and version: raspberry pi running NARD linux
* Target CPU architecture: armhf

**Comment by jreiser** [comment]
`in-place decompression` means that the total RAM that is required to invoke an executable that has been compressed by UPX is no more than (1 + epsilon) times the total RAM that is required just before executing the first instruction of the de-compressed (expanded) program.  The RAM needed is `not` the `sum` of the compressed and the de-compressed program; instead it is [perhaps slightly more than] the `maximum` of those two sizes (which will be the expanded size.)

Storing one program compressed by UPX in a `RAM`disk, then executing it, requires RAM equal to the sum of the two sizes, (the compressed copy in the filesystem is not replaced by the expanded copy) which is more than the never-compressed original.  But storing 100 programs compressed by UPX in a RAM disk, and executing any subset of at most 5 of them at a time (counting multiplicity if the same program is executed more than once simultaneously), probably does save space.  If many concurrent processes execute simultaneously the same program compressed by UPX, then total space probably increases because the results of each UPX dynamic de-compression is not shared.

Then there is the complication that the UPX de-compression stub expands only those portions that are required for execution: the stub does not expand the debug symbol tables, etc.  The non-executed contents have been compressed and stored, and may be recovered by `upx -d`; but for most purposes this is an off-line activity.

If smallest total RAM is what you want, then put the never-compressed programs  into a compressed filesystem, and store that in ROM.  The compressed filesystem typically uses a blocksize that is 32X as large as the hardware pagesize, such as: blocks of 128KiB when expanded, if the pagesize is 4KiB.  The Linux kernel de-compresses each 128KiB block as needed on demand, and caches the result.  The net "static" compression ratio can be either better or worse than UPX, depending on the amount of cross-program commonality [which UPX cannot see, but the compressed filesystem can] and the typical offset of repeated substrings [the compressed filesystem is limited to 128KiB with quantization, but UPX is not].  In most cases the dynamic de-compression, and cached sharing of those "temporary" pages, is a significant advantage, even though the low-level compression might not be as tight.

**Comment by axos88** [comment]
@jreiser thanks for this informative write-up. So basically it's counter-productive for to compress binaries that are going to be running for the lifetime of the system, but might make sense to compress other stuff that are only going to be executed on boot / once in a while (although their sizes are insignificantly low compared to the daemon that I wanted to compress).

Btw, I'm copying the whole filesystem into RAM from ROM (so that the SD card can be hotswapped while the system is running), so compressing the disk image doesn't make sense in this case.

**Comment by jreiser** [comment]
```
I'm copying the whole filesystem into RAM from ROM
(so that the SD card can be hotswapped while the system is running),
so compressing the disk image doesn't make sense in this case.
```
If the static savings from compression is larger than the expanded size (and probably even the [smaller] working set size) of the programs which will be running simultaneously, then using a compressed filesystem will save RAM.  This often is true when a large fraction of the programs in the filesystem are used infrequently.  The cost is the overhead for de-compression (which may be repeated several times for various subsets of pages, due to paging [a de-compressed page that is read-only may be paged out by discarding it, because it can be re-created again by de-compression), both cycles and pages due to quantization (fragmentation inside a compressed block.)

**Comment by jreiser** [comment]
Also consider the "Live USB" systems that Fedora and Debian and others produce.
