### ISSUE TITLE
[Question]Interplay with embedded resources

### ISSUE THREAD

**Issue by SairesArt** [upx/upx#266]
I constantly use "ld -r -b binary img.jpeg img.o" + "gcc main.c img.o" to append all kinds of resources to executable and access it with _binary_filename_filextension_start[]
In this scenario UPX is really awesome, as for instance font files get LZMA compressed to a fraction of their original size, without me having to do anything.

However, how does this play into memory management? For instance:
I have a 1mb JPEG appended. I pipe that into a JPEG decode function and get my RGB array. Now I don't need that JPEG ever again. However, I cannot free() it, as at no point I allocated the it.

As I understand it, Without UPX:
On program launch the JPEG file gets memory mapped, but not uploaded to RAM. With some form of demand paging the first time the JPEG gets accessed it is uploaded to RAM by the OS. After the function completes the JPEG is stuck in RAM and I cannot free() it. I hope that the OS is smart enough to deallocate it... somehow...

With UPX:
The whole executable lands in RAM and gets in-memory extracted. Now The JPEG is stuck in RAM. So does that mean that I have essentially wasted 1MB of RAM, as I never access the file again?
Would extraction to a temp file change this dynamic? Or am I misunderstanding here something on a fundamental level?

**Comment by jreiser** [comment]
The Description above confuses RAM with address space.  The address space with UPX (after de-compression) is the same as the address space without UPX.  In both cases, after converting the JPEG to RGB, then the 1MB of address space occupied by the JPEG cannot be used for anything else (unless by munmap() and so on, which is a VERY "dirty" hack) but gradually the operating system will reclaim the RAM, as long as the address space never is referenced again.  "Losing" the 1MB of address space (the JPEG) hardly matters on a 64-bit machine because the address space is so large.  On a 32-bit machine there are only 4K chunks of 1MB (and typically a normal program can reference only 3GB, 2.5GB, or 2GB anyway), so that 1MB of address space _might_ matter.  If so, then putting the JPEG into a file would be one way to recoup the address space.

**Comment by SairesArt** [comment]
@jreiser Thanks for clearing it up! That's great news actually! I was indeed recommended to look at mmap, but all that is OS specific, as I understand it.
How can the OS reclaim the address space if the 1mb JPEG was unpacked in RAM? If the OS reclaimed that 1MB and I reference that JPEG again after a year of run time... where did the JPEG go? It can't simply get it from the binary again. Was it downloaded to the Page file or something?

BTW, to that extent there is somewhat of a "bug" in UPX.
If a program is too small, upx fails with the rather undescriptive "NotCompressibleException".
Even if you attach Megabytes worth of stuff to a small dynamically linked program, upx won't even try to compress it, even though it may have great success in doing so. (attached GLSL shader source compress really well). Tried attaching 100MB worth of stuff to hello world and upx still fails.

**Comment by jreiser** [comment]
`How can the OS reclaim the address space if the 1mb JPEG was unpacked in[to] RAM?` If not referenced, and if there is "memory pressure" (demand by the same or other processes to increase the system-wide total working set size) then the JPEG (unpacked contents in RAM) will be paged out to the backing store device (paging file). The address space will continue to be reserved, so that the contents of the pages can be paged back in if/when referenced in the future.  The address space (and any RAM that still is present in the range) may be reclaimed by munmap().  Consult any textbook on demand paging.

Workaround for NotCompressibleException when .text is too small: compile and add to the static binding step (/usr/bin/ld) a file such as
```
int const make_compressible_for_UPX[10000] = {1};  /* initialized and 'const' ==> .text segment */
```
which itself compresses about 10,000:1 (one data byte, 2 bytes of repetition count, encoding overhead), and greatly increases the savings for compressing .text.
