### ISSUE TITLE
Intercepted Message Box

### ISSUE THREAD

**Issue by JubaDZ** [upx/upx#269]
```
function InterceptedMessageBoxA(Wnd: HWND; lpText, lpCaption: PAnsiChar; uType: UINT): Integer; stdcall;
type
  TOrigMessageBoxA = function(Wnd: HWND; lpText, lpCaption: PAnsiChar; uType: UINT): Integer; stdcall;
begin
  if (lpCaption <> 'blablablablabla......')  then
    Result := TOrigMessageBoxA(OrigAddr)(Wnd, lpText, lpCaption, uType);
end;
 
function Intercept(const OldProc, NewProc: FARPROC): Boolean;
var
  ImportEntry: PImageImportDescriptor;
  Thunk: PImageThunkData;
  Protect: DWORD;
  ImageBase: Cardinal;
  DOSHeader: PImageDosHeader;
  NTHeader: PImageNtHeaders;
begin
  Result := False;
  if OldProc = nil then Exit;
  if NewProc = nil then Exit;
  ImageBase := GetModuleHandle(nil);
  DOSHeader := PImageDosHeader(ImageBase);
  NTHeader := PImageNtHeaders(DWORD(DOSHeader) + DWORD(DOSHeader^._lfanew));
  ImportEntry := PImageImportDescriptor(
    DWORD(ImageBase)+
    DWORD(NTHeader^.OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT].VirtualAddress)
  );
  while ImportEntry^.Name <> 0 do begin
    Thunk := PImageThunkData(DWORD(ImageBase) + DWORD(ImportEntry^.FirstThunk));
    while Pointer(Thunk^._function) <> nil do begin
      if Pointer(Thunk^._function) = OldProc then begin
        if VirtualProtect(@Thunk^._function, SizeOf(DWORD), PAGE_EXECUTE_READWRITE, Protect) then
        try
          InterlockedExchange(Integer(Thunk^._function), Integer(NewProc));
          Result := True;
        finally
          VirtualProtect(@Thunk^._function, SizeOf(DWORD), Protect, Protect);
          FlushInstructionCache(GetCurrentProcess, @Thunk^._function, SizeOf(DWORD));
        end;
      end else Inc(PAnsiChar(Thunk), SizeOf(TImageThunkData32));
    end;
    ImportEntry := Pointer(Integer(ImportEntry) + SizeOf(TImageImportDescriptor));
  end;
end;
 
begin
  OrigAddr:=GetProcAddress(GetModuleHandle(user32), 'MessageBoxA');
  Intercept(OrigAddr, @InterceptedMessageBoxA);

```
win 64bits
upx 3.95
cpu intel

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") an actual executable file which reproduces the problem. (Compress with zip before uploading, so that github will accept the file.)  Please state the exact command line that triggers the problem.

**Comment by Mattiwatti** [comment]
Given that you have given absolutely no description of what the problem even is, no executable to reproduce the problem, and so on... I'm going to use my mind reading skills here and guess at what you tried to say:
> I am using this function to hook MessageBoxA via IAT patching, but it no longer works when the executable is compressed with UPX.

Did I get it right?

`MessageBoxA` is (probably) not in the import address table because it is (probably) not in the import directory. The chance of `MessageBoxA` being in the import directory and thus the IAT is `(1 / num_user32.dll_imports)`, because one import per DLL always survives to ensure the DLL gets loaded. All other imports are resolved via `GetProcAddress`, see [here](https://github.com/upx/upx/blob/bdd97fe0b24aaba8e82becdad3e94ceaaba5bd77/src/stub/src/amd64-win64.pep.S#L291).

Is this a bug? Maybe. It depends on whether you expect a packer to not compress imports to accommodate things like IAT patching. Personally I would have been surprised if UPX **didn't** compress imports, given what it is. But I guess you could make the purist argument that the import directory is not preserved exactly in compressed files.

This is unrelated to the bug, but things like this are exactly why IAT patching is so useless. Processes can resolve functions at runtime via `GetProcAddress` or an equivalent function and bypass this with minimum effort.

**Comment by JubaDZ** [comment]
[upx_test.zip](https://github.com/upx/upx/files/3268294/upx_test.zip)

> upx_test.zip\Win32\Release\Project1.exe
