### ISSUE TITLE
Is it possible to debug original .dll after UPX compression ?

### ISSUE THREAD

**Issue by tapika** [upx/upx#276]
## What's the problem (or question)?

Intrested in Windows & Linux upx compressed .dll & .so. Is it possible to debug them after they were compressed by upx, using some magical command line parameter for this purpose.

If not possible - how difficult it would be possible to change upx to support such scenario.

What I have briefly tried 
    upx.exe -1 --strip-relocs=0 --compress-exports=0 SampleDLL.dll

command - debugging of original .dll cannot be performed even thus .dll itself works.

**Comment by jreiser** [comment]
De-compress (`upx -d`) the .dll, and debug using that.  Or, run using the compressed .dll, but tell the debugger "use the symbols from this other file, which is the original never-compressed .dll".  The gdb command `add-symbol-file FILE ADDR` will do this on some other systems; perhaps there is an analogous command in your debugger.

**Comment by tapika** [comment]
Using Visual Studio for windows debugging, I have even disabled "Require source codes to exactly match the original version", but it does not help.

For linux I'm using also Visual studio at the moment, which in a turn uses gdb, but gdb as command prompt is not available. (Except some commands can be ran from .gdb-init).

I suspect that .pdb gets loaded during LoadLibrary, which also performs read of .dll. .dll does not match .pdb, and that is a problem in itself. Suspect if I could intercept windows API's FileOpen/FileRead, and perform .dll extraction during that point of time - then .pdb would match .dll and debugger could proceed further.

But then need to have reliable / portable ways of hooking windows api & linux dlopen.

I guess for linux something like this could be used:
https://github.com/scumjr/idontgiveashell

and for windows something like this:
https://github.com/TsudaKageyu/minhook

But recombining all pieces of puzzle together sounds bit complex.

**Comment by Mattiwatti** [comment]
No hooking is required, but Visual Studio is definitely ill-equipped to do this. I doubt it is possible to be honest. Use WinDbg instead. It probably comes with the Windows SDK which you can select in the Visual Studio installer (not 100% sure about this). If not, install the WDK to get it.

1. Assuming you have `original.exe`, `original.pdb` and `compressed.exe`, copy `original.pdb` to `compressed.pdb` first, or WinDbg will get confused. Start WinDbg.
2. File -> Symbol File Path... -> append `C:\Path\To\OutputFiles`
3. File -> Source File Path... -> append `C:\Path\To\Sources`
4. File -> Open Executable... -> open `C:\Path\To\OutputFiles\compressed.exe` -> WinDbg breaks at `ntdll!LdrpDoDebuggerBreak`
5. `bp VirtualProtect`, `g`
6. Your breakpoint will be hit, `gu` to return to caller
7. `bc *` so the breakpoint won't be hit again
8. In the disassembly view, scroll down a bit until you see a `jmp` instruction. Click on it and press F9 to set another breakpoint. I've highlighted it here:
![jmp](https://i.imgur.com/sXKDn8h.png)
9. `g`, the breakpoint will be hit. Press F11 to step into.
10. You are now at the original (uncompressed) entry point. Run
  `.symopt- 0x100` to remove `SYMOPT_NO_UNQUALIFIED_LOADS`
  `.symopt+ 0x40` to set `SYMOPT_LOAD_ANYTHING`
  `.reload /f *`
11. `bp compressed!main` (or whatever the name of your entry point is) should now work since you have PDB symbols loaded.
12. `g` to run again, and voila:
![main](https://i.imgur.com/45pkcEG.png)
