### ISSUE TITLE
Support Zstd compression support

### ISSUE THREAD

**Issue by alphaonex86** [upx/upx#295]
Hi,

Can you support Zstd compression support, compared to lzma, it will be:
**VERY** faster decompression speed (then .exe startup time).
For my .exe it's 10x startup time.

Cheers,

**Comment by bitraid** [comment]
Zstd doesn't provide better compression ratio than lzma.

**Comment by alphaonex86** [comment]
On various data set and with compression level 22, it provide at least similar compression ratio.
You can have more data into: https://quixdb.github.io/squash-benchmark/

**Comment by bitraid** [comment]
No, it doesn't. Not even compared to the fastest lzma setting. Zstd is designed to be fast with better compression than zlib, but won't beat lzma (which is slow).

**Comment by alphaonex86** [comment]
Well I have other result with my specific case. Forgot this part. Just better decompression speed.

**Comment by jreiser** [comment]
For your application, please give the `measured` times for de-compression when the compression was done using upx -9 --lzma, upx -9 [default NRV/UCL compression], gzip -9, xz "max" but limited to 64KiB working storage, and Zstd 22 [How large was the working storage?].  Run each case 3 or 5 times consecutively, and report the median (not the mean.)

Please run `ls -l my_app; readelf --segments my_app`, then Copy+Paste the output into a Comment here.  Surround the pasted output with a line before and after that has three backtick characters (hex 0x60, octal 0140, decimal 96; often near the `1` key in the upper left on a keyboard) only, so that the Markdown processing results in constant-width characters with columns that are preserved; check the Preview.

**Comment by jreiser** [comment]
`readelf `: sorry, I missed the part where you said `.exe`.  Please run some tool which lists the PE sections and their sizes, and report that.

**Comment by alphaonex86** [comment]
No problem, my software work under Linux too:
Original size: 3227304
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  INTERP         0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000028cd60 0x000000000028cd60  R E    0x1000
  LOAD           0x000000000028d440 0x000000000028e440 0x000000000028e440
                 0x0000000000008b40 0x000000000000d7dc  RW     0x1000
  DYNAMIC        0x0000000000293290 0x0000000000294290 0x0000000000294290
                 0x00000000000002a0 0x00000000000002a0  RW     0x8
  NOTE           0x0000000000000254 0x0000000000000254 0x0000000000000254
                 0x0000000000000020 0x0000000000000020  R      0x4
  GNU_EH_FRAME   0x000000000028622c 0x000000000028622c 0x000000000028622c
                 0x0000000000006b34 0x0000000000006b34  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x000000000028d440 0x000000000028e440 0x000000000028e440
                 0x0000000000006bc0 0x0000000000006bc0  RW     0x20

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .interp 
   02     .interp .note.ABI-tag .dynsym .dynstr .gnu.hash .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .qtversion .gcc_except_table .eh_frame .eh_frame_hdr 
   03     .data.rel.ro.local .fini_array .init_array .data.rel.ro .dynamic .got .got.plt .data .bss 
   04     .dynamic 
   05     .note.ABI-tag 
   06     .eh_frame_hdr 
   07     
   08     .data.rel.ro.local .fini_array .init_array .data.rel.ro .dynamic .got

upx -9 ultracopier: 1191844
time upx -9 --lzma ultracopier: 1060772B 1.406s
time upx -d ultracopier: Exception: compressed data violation
Then *I will continue with raw compression*:
time xz -9 -e ultracopier: 994424B 0m0.354s
time unxz ultracopier.xz: 0m0.054s

time gzip -9 ultracopier: 1160503B 0.567s
time gunzip ultracopier.gz: 0.028s

time zstd -22 --ultra ultracopier: 956258B 1.027s
time unzstd ultracopier.zst: 0.024s

I have similar result with all my software.

**Comment by jreiser** [comment]
The zstd code for de-compression is huge:
```
 $ size $(find . -name '*.o')  # on x86_64
   text	   data	    bss	    dec	    hex	filename
  24866	      0	      0	  24866	   6122	./lib/decompress/zstd_decompress.o
  62995	      0	      0	  62995	   f613	./lib/decompress/huf_decompress.o
  24842	      0	      0	  24842	   610a	./lib/decompress/zstd_decompress_block.o
   2787	      0	      0	   2787	    ae3	./lib/decompress/zstd_ddict.o
```
The UPX stub for de-compressing, which must be bound into each compressed executable, is less than 3KB on all platforms for any compression method, and around 2KB or less on x86\* and arm\*.  The subroutine to expand the data format is around 200 to 300 bytes for NRV/UCL (interfacing with the OS accounts for the rest), and even lzma can be decoded in around 1.2KB to 2KB  using by-hand unification of tails.  zstd requiring around 25KB is a very large increase.

**Comment by alphaonex86** [comment]
Yes, you are in right for this simple test, but this code include lot of not used stuff (API, legacy code) or like mentioned dictionary.
25KB is not so large for 1MB+ software.

**Comment by mniehren** [comment]
i would also like to see zstd support in upx. It would increase the startup time of the
application a lot.
I used it for image decompressing at boot time and it's rigorous faster, especially on slow
machines.

**Comment by jreiser** [comment]
@alphaonex86 25KB is 2.5% of 1MB. 
It looks like this decoder in the zstd repository has very little extraneous code, yet still is 25KB when compiled at `gcc -O2` for x86_64:
```
   text	   data	    bss	    dec	    hex	filename
  24974	      0	      0	  24974	   618e	doc/educational_decoder/zstd_decompress.o
```
@mniehren You commented: ` It would increase the startup time of the application a lot.`   I suppose you mean `decrease` the startup time.  But any compression tends to decrease startup time because smaller size decreases total time for accessing disk storage.  How much of an improvement was zstd over anything else?

**Comment by alphaonex86** [comment]
With Qt, I have often dll of more than 8MB... zstd help to reduce lot of the disk access... if it's 500ms (disk + decompression time) win for 20ms lost due to this 25KB overhead, it's well

**Comment by mniehren** [comment]
oh sorry, i mean decrease.

i can not tell the advantage in percent. Before zstd i used lzham, which also has a great decompressing speed, but i think it would be an improvement over 50% against lzham.

**Comment by mudlord** [comment]
It would make more sense to implement a LZ4 decompressor + optimal compressor. 25kb of decompressor is just bloat compared to < 150 bytes

**Comment by alphaonex86** [comment]
LZ4 have worse compression ratio. PS: if you strip decompressor in function of compression level then the decompressor is very lighter.

**Comment by mudlord** [comment]
Oh really? How low can the decompressor for zstd go in terms of size exactly?

**Comment by jreiser** [comment]
As I reported two months ago in https://github.com/upx/upx/issues/295#issuecomment-519519576 above, `educational_decoder/zstd_decompress.o` is 25KB at `gcc -O2` and stripped.

**Comment by mudlord** [comment]
Several demoscene packers try to solve the problem of the size of their stub by compressing decompression code, sorta like those Russian stacking dolls. Maybe UPX could then, in the case of a Zstandard implementation, compress the Zstandard decompressor using NRV+code filters? And then use Zstandard to decompress the executable data (like for instance MAME's executables, which are over 200MB).

kkrunchy for example compresses its x86 code filter which is then depacked before its use. Maybe UPX can do something similar for Zstd?

**Comment by jreiser** [comment]
UPX has done a different "compress the decompressor" trick for many years.  In the case of zstd, then 26KB becomes 18KB, which still is huge.
```
$ gcc main.c zstd/doc/educational_decoder/zstd_decompress.o
$ upx.out -f -o foo a.out
        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     44240 ->     18720   42.31%   linux/amd64   foo   
$ size a.out *.o
   text	   data	    bss	    dec	    hex	filename
  26771	    580	     16	  27367	   6ae7	a.out
  24974	      0	      0	  24974	   618e	zstd_decompress.o
$ ls -l foo
-rwxrwxr-x. 1 user group 18720 Oct 14 14:44 foo
```

**Comment by mudlord** [comment]
Damn. Well there goes that idea.

**Comment by bofhbug** [comment]
i also really like to see a Zstd compression Support in upx

**Comment by jreiser** [comment]
@bofhbug It would help if you could provide some motivations for upx to use zstd; _why_ would you like to see Zstd in upx? `upx --lzma` already is smaller than what a hypothetical `upx --zstd` would do; but lzma de-compressing is slower that zstd de-compressing.  De-compression for the upx default compression method of NRV (or its open-source equivalent UCL) is competitive in speed with zstd, and the de-compressor itself is about 18KB smaller.  How much better (speed and space) do you expect zstd to be?  Compress a few of your executables with upx and  (merely as files) with zip, gzip, zstd; then report the sizes here.

**Comment by mikejsavage** [comment]
Would be nice to have zstd for compressing massive binaries, e.g. [ispc.exe](https://ispc.github.io/downloads.html) which is 75MB

upx compresses it to 20MB, but adds quite a noticable startup time. zstd would presumably be slightly bigger but decompress near instantly

```
> time ./ispc.upx.exe --version
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.13.0 (build date Apr 24 2020, LLVM 10.0.0)
Supported Visual Studio versions: Visual Studio 2015 and later.

________________________________________________________
Executed in  261.16 millis    fish           external
   usr time    0.00 micros    0.00 micros    0.00 micros
   sys time    0.00 micros    0.00 micros    0.00 micros

> time ./ispc.exe --version
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.13.0 (build date Apr 24 2020, LLVM 10.0.0)
Supported Visual Studio versions: Visual Studio 2015 and later.

________________________________________________________
Executed in   18.34 millis    fish           external
   usr time    0.00 micros    0.00 micros    0.00 micros
   sys time    0.00 micros    0.00 micros    0.00 micros
```

**Comment by jreiser** [comment]
@mikejsavage Thank you for that data, however important information is missing.  Please present the space and de-compression time taken by ispc.exe (as a file of uninterpreted bytes) when compressed by Zstd.  Please present the resulting space and de-compression time for `each` of the UPX compression methods --lzma and the UPX default (which is NRV or UCL).

**Comment by mikejsavage** [comment]
Here's a table made with `lzbench -ezstd,0,22/zlib,0,9/lzma,0,9`, and upx at the end (`time upx.exe -1`, `time upx.exe -9`, `time upx.exe -d`)

| Compressor name       |  Compress.  |  Decompress. | Compr. size  | Ratio  |
| ----------------------|-------------|--------------|--------------|--------|
| memcpy                |   8571 MB/s |  8649 MB/s   |  75329904    | 100.00 |
| zstd 1.4.4 -0         |    265 MB/s |  1208 MB/s   |  24130892    | 32.04  |
| zstd 1.4.4 -22        |   3.14 MB/s |   919 MB/s   |  18478421    | 24.52  |
| zlib 1.2.11 -0        |   1920 MB/s |  8687 MB/s   |  75329904    | 100.00 |
| zlib 1.2.11 -9        |     13 MB/s |   325 MB/s   |  27511960    | 36.52  |
| lzma 19.00 -0         |     30 MB/s |    67 MB/s   |  24385787    | 32.38  |
| lzma 19.00 -9         |   3.10 MB/s |    98 MB/s   |  16991781    | 22.56  |
| upx 3.96w -1          |   1.50 MB/s |   159 MB/s   |  32613744    | 43.29  |
| upx 3.96w -9          |  87.90 MB/s |   177 MB/s   |  20335472    | 27.00  |

**Comment by bofhbug** [comment]
in my case i hope to get Packer and Terraform smaller with a faster startup time.
some info about the filesize:
Packer v1.6.0 on windows is 117.6M
Terraform v0.12.28 on windows is 66.5M

**Comment by Piqlet** [comment]
Linux test, xz vs. zstd : [https://lists.archlinux.org/pipermail/arch-dev-public/2019-March/029542.html](https://lists.archlinux.org/pipermail/arch-dev-public/2019-March/029542.html)

Minor explanation : zstd decompression memory(last column) same window size.
8 MB window -> 10.xx MB RAM,
32 MB window -> 34.xx MB RAM,
64 MB window -> 66.xx MB RAM.

**Comment by jreiser** [comment]
@mikejsavage Thank you (and others) for more data.  In the past, UPX has been more concerned with smaller executables (say, up to a few tens of megabytes) where 20KB for a zstd decompressor is a significant expense, especially in contrast to 2KB to 3KB for all others.  Another significant expense is temporary working storage during decompression, both the absolute size in bytes and the management protocol.  The UPX default NRV and UCL de-compressors require no working storage at all.  UPX has tuned --lzma to require at most 28KB of working storage, obtained in one chunk on the stack via the equivalent of alloca().  @Piqlet data says that zstd with common parameters expects to use 11MB to 67MB, and it is managed by malloc()+free().  The default Linux stack limit is only 8MB, and that includes the shell environment variables.  Those constraints raise the complexity of implementing in UPX a de-compressor for zstd.

The blazing speed of inexpensive nvme storage (often > 2GB/s) or even SATA SSD (> 500MB/s) tends to erase much of the speed advantage that UPX de-compression has over traditional rotating disk storage (< 100 MB/s; often < 20 MB/s.)

**Comment by richarddd** [comment]
What about LZ4?

> It would make more sense to implement a LZ4 decompressor + optimal compressor. 25kb of decompressor is just bloat compared to < 150 bytes

Would it make sense?

**Comment by alphaonex86** [comment]
LZ4 have sense only for small binaries. For big binaries, the size gain for 99.99% is due to compression ratio.

**Comment by xqdoo00o** [comment]
It will be very glad if zstd could add to upx.

**Comment by jreiser** [comment]
So far, Zstd has not considered de-compression in embedded environments such as required by UPX: no builtin malloc+free, and constrained by memory space and address space.  The Zstd compression context structure does not even consider constraints that may be imposed by de-compression, such as an absolute limit on working storage (perhaps 32kB, 64kB, 1MB, 8MB, or any other fixed amount), or saving space by overlapping the compressed input with the tail of the buffer for de-compressed output.  The nearest I can find is https://github.com/facebook/zstd/issues/2093   "Minimizing memory requirements for Decompression?" which seems to say that general overlap is not possible because literals and sequences occupy separate tables, and there is no consideration of putting the literal table last, and giving its size as an output from the compression stage, which would enable partial overlap. There are many input parameters in ZSTD_initStaticCCtx, but I can find no higher-level interface which allows specifying "de-compression must use at most 2MB of space; choose compression parameters (and strategy) accordingly."

Also the source code contains comments such as  `/* must be 8-aligned */` (ZSTD_initStaticCCtx  in lib/compress/zstd_compress.c) with no explanation why.  Is it natural alignment of contained `double`, using the low-order 3 bits of a pointer as tags or a 0-to-7 counter, or some other specific explicit constraint?  This is low-quality code.

**Comment by markus-oberhumer** [comment]
zstd decompressor is *way* too large.

**Comment by z3cko** [comment]
I suggest for everyone who really wants this feature to donate to this project. This would be the easiest solution. If there is enough budget it could be potentially worked on.

**Comment by markus-oberhumer** [comment]
zstd used FSE which processes symbols in reverse order - this is fine for a file compressor but very inappropriate for an executable packer which needs to do `in-place decompression`.

**Comment by jreiser** [comment]
Many (most?) modern compiled binary apps have more than one page-aligned "section" (PE), PT_LOAD (ELF), or "segment" (Mach-O) that makes in-place decompression cumbersome.  Aligning each compressed piece to a page boundary in the generated file suffers fragmentation which costs space in the file, typically kilobytes per piece (4KiB pages on x86*, 16KiB pages on Apple ARM*, 32KiB pages on MIPS, 64KiB pages on PowerPC)

If a copied substring is 4 bytes or longer, then the current x86* decompressor uses copy-by-word that might overrun the destination by 3 bytes.  Forcing copy-by-byte would cost time everywhere. Mapping an overflow page costs time when it occurs.

The net effect of the current implementations is that the compressed pieces are byte-concatenated in the file (to save space), and mapped as one page-aligned contiguous extent into a region that is outside all the target pages (to reduce complexity.) Decompression reads from the single region and distributes to the target pages. So there is no overlapping.  If the OS would do lazy allocation of physical RAM pages to support the Read of compressed bytes, and reclaims that RAM aggressively soon after it has been read, then in theory that requires only one page of "extra" RAM compared to optimal overlapping.  In practice the OS is not that perfect, and there has been a complaint about the "pulse" of demand for additional RAM at decompression.

If overlapping is required, then

1. Each compressed piece would get its own separate pages in the generated file, at a cost of page fragmentation.  (The fragmentation would be at the _beginning_ of each piece; see next point.)
2. The decompression algorithms would have to be certified to require no overhead: the input would end at a page boundary, and the output would end at the same page boundary, with no access (neither Read nor Write) beyond the boundary, and (obviouslly) no Read after Write of any byte.
3. The interface to the OS regarding protection of generated pages is fragile.  Generating new pages and marking them eXecutable is Just-In-Time compilation, which is somewhat simple for the OS to understand and support.  In contrast,  at first glance taking an exising eXecutable page, making it Writeable, overwriting the page, and making it eXecutable+noWrite looks like a malware attack.

With a new strategy for the decompression stubs of always using NRV2B to decompress the actual decompressor**S**, then the Zstd decompressor becomes not so large (~20KB of code, IF its source can be separated from the rest of the Zstd source;  Zstd did not plan on embedded, decompress-only usage.)  Many use cases can tolerate the "pulse" of used pages at decompression time, so FSE is not ruled out for them.

**Comment by parasew** [comment]
Well, there is [RFC 8878: Zstandard Compression and the 'application/zstd' Media Type](https://www.rfc-editor.org/rfc/rfc8878) - so in the worst case (if the source cannot be separated from the rest of Zstd source) we could create our own decompressor, no?

**Comment by Cyan4973** [comment]
Well, that's a timely coincidence : 
https://github.com/facebook/zstd/pull/3421
Add support for in-place decompression #3421

**Comment by markus-oberhumer** [comment]
@Cyan4973 Indeed - perfect timing, many thanks! :-)

Still, we have to think about the LICENSE implications: https://github.com/facebook/zstd/blob/dev/LICENSE

In particular, for any hypothetical zstd-upx-compressed exe the following would apply:

```
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.
```

**Comment by Cyan4973** [comment]
Good point,

what is the solution selected by LZO ? A special exception ?

**Comment by markus-oberhumer** [comment]
UPX does not use LZO, it uses UCL (with special exception granted by be)  and LZMA-SDK (public domain).

**Comment by ghtm2** [comment]
Sorry to bump this issue yet again, but I'm also quite interested in this.
Can I ask what this got hung up on? The LICENSE implications metioned above?
There appears to be an implementation as of 9f830e0, but I don't think that it can currently be selected.
Am I reading this right?

**Comment by jreiser** [comment]
The current state of [zstd](https://github.com/facebook/zstd.git) is: poorly implemented, and inadequately documented, for use in "embedded" environments.  Specifically, the zstd memory management during de-compression assumes malloc+free with infinite resources.  The fact that zstd compression does not take a parameter which specifies the maximum byte size that is to be allowed for working storage during de-compression, is a very strong hint that zstd is not ready for embedded environments.

Until zstd is enhanced so as to be hospitable for use in resource-constrained de-compression environments, then progress will be slow or blocked. See https://github.com/facebook/zstd/issues/3453 .

Edit: The working storage required for de-compression of NRV/UCL by current implementation in UPX  is 2*NBPW bytes: two return addresses on the subroutine call stack, and nothing else.  Because of careful control of compression parameters when called by UPX, the working storage required to de-compress `--lzma` is 56KiB, which is placed on the stack by an equivalent to `alloca()`.

**Comment by markus-oberhumer** [comment]
Technical issues aside, the current zstd LICENSE does not work for UPX. 

See above https://github.com/upx/upx/issues/295#issuecomment-1381287255

**Comment by polarathene** [comment]
FWIW Chrome supports zstd content encoding now with a 8MB max window size (_content will fail to decompress if it was compressed with a larger window size_).

> Until zstd is enhanced so as to be hospitable for use in resource-constrained de-compression environments, then progress will be slow or blocked. See [facebook/zstd#3453](https://github.com/facebook/zstd/issues/3453) .

The last activity there suggests that stack usage is around 1KB? The larger stack size concerns you mentioned were deemed not relevant as DCE should remove them?

**Comment by jreiser** [comment]
The primary request (complaint) of https://github.com/facebook/zstd/issues/3453 "Request For Enhancement (RFE): Please **document**, ..." still applies.  WTF is "DCE"?  Searching the web for "DCE software" yields https://en.wikipedia.org/wiki/Distributed_Computing_Environment whose applicability to this situation is very unclear.

re: 8MB stack.  Laughable.  That won't fit in today's Linux, where the default maximum total stack size is 8MiB. If there is **anything** else on the stack (such as a single return address, actual parameter, frame pointer, **any** environment variables [for the main thread], ...), then a default thread which demands 8MiB on-stack allocation will fail.

UPX has figured out how to employ LZMA such that the maximum memory allocation (including both explicit malloc and stack excursion) during decompression is less than 64KiB, while retaining most of the size reduction advantage of LZMA in contrast to other deflate-based compression methods.  Of course the time required for de-compression of LZMA still is (appoximately) an order of magnitude larger than for several other compression methods.

Zstd still is unfit for use in a resource-constrained de-compression environment.  For starters, Zstd compression doesn't even consider the most important input parameter: the space available for eventual **de**-compression.  Either make that an explicit input parameter, or **document** how to adjust the several existing input parameters, and run-time allocation strategies for malloc and stack, so as to fit an explicit numeric constraint on space available during de-compression.


Edit: For example: The run-time de-compression environment can provide an interval of 86.5 kilobytes (86,500 bytes) of space for use by the de-compressor.  What input parameters to Zstd  provide the smallest compressed output that fits, and if the de-compressor uses malloc then what strategy should malloc use for placement of blocks?

**Comment by polarathene** [comment]
> WTF is "DCE"?

_Dead Code Elimination_. Sorry I thought that was obvious in the context but if you've never heard of that compile time feature I guess it wouldn't click?

Basically the compiler knows your compiled program won't ever call some method it doesn't redundantly include/link it in the build.

---

> re: 8MB stack. Laughable.

This was just a reference of the window size buffer for decompression that the RFC suggests and what Chrome chose to cap it at for their client. Since this can technically be something like 3.75TB for zstd if the client wanted to support that, I'm pretty sure this isn't stack memory but heap? 🤷‍♂️ 

It's a maximum limit btw, if the content is compressed with a smaller window size, that information is known by the client IIRC and the buffer will be allocated at the smaller size AFAIK. I've not looked into the technical details that deeply myself, from your replies here I just assumed you'd be more familiar with what I was referring to.

Caddy has zstd configured with 128KiB as it's hard-coded encoder window size presently, specifically to support embedded clients apparently. At some point that may be configurable, just citing it as an example.

---

> For starters, Zstd compression doesn't even consider the most important input parameter: the space available for eventual de-compression.

I don't quite follow why you need that upstream? Isn't UPX handling both encode and decode responsibilities? You could just as easily use information you'd have available of the original decompressed content size, prior to UPX encoding it? Seems like an odd blocker?

---

> Zstd still is unfit for use in a resource-constrained de-compression environment.

I don't know why that is an issue with UPX? I'm sure it's a very valid use-case, but how many users of UPX rely on it for distributing an executable that's compressed? It's still useful for that convenience in plenty of environments for deployment that aren't so severely resource constrained?

I'm not claiming zstd is necessarily better or worthwhile to add to UPX, just that the current reasons cited to block on it seem a bit overly restrictive. I get that the context you're having an issue with it may very well not be suitable but that isn't the only environment that UPX would be used in?

Perhaps there is a misunderstanding here for me regarding "environment". If a desktop system for runtime is not what you'd qualify as an environment (_one that isn't resource constrained like some SBC or similar_), but rather the environment is UPX itself and it's own constraints at runtime.. then disregard this section.

**Comment by jreiser** [comment]
> the environment is UPX itself and it's own constraints at runtime

Yes.  A UPX-compressed ELF file is completely standalone. It uses no helper programs or libraries of any kind, only stack and system calls. All code is included in the 2.5KB to 4KB de-compressor. One useful analogy is that the ELF de-compressor of UPX is a user-mode `execve()` which fills pages with de-compressed bytes instead of a `mmap()`ed file.

The target audience for UPX is distributors of network-delivered self-contained executable programs (smaller size leads to lower charges/time/throttling), and end-user appliances or systems with limited storage (often smaller flash memory: think of OpenWRT routers, low-end tablets or game consoles, etc.)

**Comment by crueter** [comment]
> The target audience for UPX is distributors of network-delivered self-contained executable programs (smaller size leads to lower charges/time/throttling), and end-user appliances or systems with limited storage (often smaller flash memory: think of OpenWRT routers, low-end tablets or game consoles, etc.)

That's an excellent case for zstd then.

**Comment by jreiser** [comment]
Zstd is **unfit for use** in environments that do not have abundant RAM space readily available. First of all, both the documentation and the reference implementation of both the zstd compressor and de-compressor do not quantify the space required.  For example, given a .zstd file (the result of zstd compression), there is no means to tell in advance how much RAM is (or will be) required. Second, the actual amount of RAM required typically  is **large**.  An embedded appliance with less than 256KiB of free RAM may or may not work for de-compressing zstd files or streams that are reasonable for the appliance to process.  Contrast with zlib, whose RAM requirements are a small multiple of 32KiB, or with LZ4, which needs even less.  Or take MNP5, popularly used by affordable consumer telephone modem **hardware** of 40 years ago, for which several dozen bytes suffice. The NRV/UCL de-compressors used by UPX need at most a few hundred bytes of instructions and fewer than one dozen bytes of working storage.

**Comment by crueter** [comment]
> An embedded appliance with less than 256KiB of free RAM may or may not work for de-compressing zstd files or streams that are reasonable for the appliance to process

It can be made optional then--embedded systems/appliances are **not** the only applications for upx. Programs that target desktop platforms don't have nearly the same ridiculous RAM requirements, and in fact would rather significantly benefit from zstd, as it is dramatically faster than lz4 while maintaining around the same compression level.

On the Linux side of things, AppImages have already adopted this for both SquashFS and DwarFS and it's proven to be incredibly reliable (even for very low-resource systems--the RAM overhead of DwarFS + zstd is a rounding error)

If you continue to be adamant about not supporting zstd *as an option* at the very least (for rather asinine reasons, as has been proven), then you should:
- Mention this on the README so users know that your software is unfit for desktop platforms that want fast decompression
- Show me an alternative not named Crinkler that isn't bound by such silly requirements

**Comment by xqdoo00o** [comment]
The criticism that Zstd is "unfit" for modern embedded environments is largely an outdated perspective that ignores the deterministic controls and hardware realities of 2026. By utilizing the ZSTD_d_windowLogMax parameter and the ZSTD_getFrameHeader API, developers can precisely calculate or cap memory usage before a single byte of the payload is processed, effectively eliminating the "unpredictability" mentioned. If a file exceeds the set resource limits, the system can reject it safely, maintaining the same level of stability as legacy algorithms.

Furthermore, we are no longer in the era of 40-year-old telephone modems; the trade-offs of 2026 prioritize throughput and energy efficiency over the extreme minimization of RAM. Allocating 256 KiB of memory is a negligible cost for modern microcontrollers when it buys significantly faster decompression speeds and higher compression ratios. This speed allows the CPU to return to sleep mode sooner, saving more power than "lightweight" ancient algorithms ever could. In a modern context, sacrificing a small amount of cheap RAM to gain massive performance and battery longevity is not just "viable"—it is superior engineering.

**Comment by markus-oberhumer** [comment]
Technical issues aside, the current zstd LICENSE does not work for UPX.

See above https://github.com/upx/upx/issues/295#issuecomment-1381287255

**Comment by jreiser** [comment]
> return to sleep mode sooner

For Linux, there is a good chance that the shortest wall-clock latency from `execve` to `sleep mode` (and other similar paths of application execution) can be achieved using `squashfs`.  Only the actual on-demand working set is de-compressed, not the whole blob.  The de-compressed pages are shared and managed just like any other read-only pages, including by discarding when page pressure is high, then regenerated upon demand.  The dynamic footprint of such pages can be substantially less than the entire de-compressed blob.

> a small amount of cheap RAM

In 2026 RAM is no longer inexpensive, due to demand by datacenters running LargeLanguageModels.  The street price has risen dramatically (in some cases by whole integer factors) in only a few months, and price rises are expected to continue for the rest of 2026.  Some finished packages are no longer available at any price, and manufacturers have no plans to resume supply.

> the current zstd LICENSE does not work for UPX.

A so-called "smart TV" purchased new in the last few years probably incorporates pieces of open-source software that are licensed under GNU GPL, often for communication using the Internet.  The license may appear in printed material that accompanies the packaging, or in the user manual, or even as an obscure item of the on-screen Help menu.  It's equivalent to **advertising**: available and displayed, but often unseen, ignored, not comprehended, effectively meaningless to the vast majority of users.

For UPX on Linux, here is an implementation of the Zstd LICENSE requirement to "reproduce the above copyright notice,
   this list of conditions and the following disclaimer".  Compress the LICENSE file using `nrv2b`, and include the compressed text in the file generated by UPX. Those 1549 bytes compress to about 800 bytes.  The `nrb2b` de-compressor  already is present  in each UPX-compressed ELF output, due to the strategy of "de-compress the de-compressor":   Near the beginning of execution, then de-compress those bytes, `write` the output to file descriptor 26 [`037 & 'Z'`], `close` fd 26, and ignore any errors.  At every execution of the compressed file, then the Zstd LICENSE is available and displayed on fd 26, as proven by re-directing fd 26 to stderr using shell syntax `26>&2` .  If the end user does not notice the "advertising", well then too bad.

**Comment by richarddd** [comment]
@markus-oberhumer @jreiser regarding the legal requirement for binary redistribution, I think we might "overthink" it: rather than trying to hide the license in an obscure file descriptor (which might not satisfy the "notice" requirement of the BSD/GPL licenses), why not handle this like a standard compiler or build tool?

When a user packs a binary, UPX is essentially acting as a linker for the decompression stub. UPX could simply:

1. Emit a CLI Warning: During the packing process, print a clear message:

```
[Notice] This executable now contains Zstd decompression code. To comply with Zstd’s license, you must include the Zstd copyright notice in your software's documentation or 'About' materials.
```

2.  UPX could drop a ZSTD_LICENSE.txt in the output directory alongside the packed binary to make compliance "one-click" for the developer.

This effectively forwards the compliance requirement to the person actually distributing the final package. It’s the same way gcc or clang works, as they don't bake the licenses of every statically linked library into the binary's execution flow: they rely on the developer to include a THIRDPARTY_LICENSES file in their distribution.

This solves the "where does the text go?" problem by putting it exactly where the license says it should be: in the documentation and/or other materials provided by the person distributing the software.

Does this approach satisfy the Zstd team's requirement for "reproducing the notice" without requiring a technical overhaul of how the decompressor stub handles I/O?

**Comment by markus-oberhumer** [comment]
https://github.com/facebook/zstd/issues/4604

**Comment by jreiser** [comment]
> wall-clock latency from `execve` to `sleep mode`

For this specific execution path, I wrote a paper 34 years ago that still applies:
```
@inproceedings{DBLP:conf/c++/Reiser92,
  author       = {John F. Reiser},
  title        = {Static Initializers: Reducing the Value-Added Tax on Programs},
  booktitle    = {Proceedings of the {C++} Conference. Portland, OR, USA, August 1992},
  pages        = {171--180},
  publisher    = {{USENIX} Association},
  year         = {1992},
  timestamp    = {Thu, 15 May 2014 18:36:26 +0200},
  biburl       = {https://dblp.org/rec/conf/c++/Reiser92.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org/}
}
```
Subroutines that implement static initialization should not be declared in `.h` header files that are `#include`d (including transitively) from many places.  By default such an implementation bloats the working set of code pages at app startup.  Either don't do that (avoid static inits in `.h`) or collect such subroutines into their own compact region of pages, such as by using a separate code Section for static inits, and/or other facilities of the static binder ("loader" or "static linker") build tool.

**Comment by crueter** [comment]
> In 2026 RAM is no longer inexpensive

zstd uses up so little that this is inconsequential. For reference ARM Cortex-A9 hardware with 256MB of RAM (and only 1/3 of that free) is able to comfortably run AppImages compressed with dwarfs + zstd. If the user can't afford 80MB of RAM (of which <5MB is taken up by dwarfs + zstd, and well below 1MB by zstd alone), that's on them. Especially given that desktop targeting apps almost always use more than that.

**Comment by markus-oberhumer** [comment]
Technical issues aside, the current zstd LICENSE does not work for UPX.

See above https://github.com/upx/upx/issues/295#issuecomment-1381287255 and https://github.com/facebook/zstd/issues/4604
