### ISSUE TITLE
Can't use compressed linux .so file for building application with GCC, "File format not recognized"

### ISSUE THREAD

**Issue by martijintro** [upx/upx#303]
## What's the problem (or question)?
GCC on Debian Stretch returns me that message when i use a upx-compressed linux .so file as a dependency.

```
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libxxx.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
CMakeFiles/xxx_master.dir/build.make:302: die Regel für Ziel „xxx_master“ scheiterte
make[2]: *** [xxx_master] Fehler 1
make[2]: Verzeichnis „/root/deployment/Temp/PF_CPPP/xxx_master“ wird verlassen
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/xxx_master.dir/all“ scheiterte
make[1]: *** [CMakeFiles/xxx_master.dir/all] Fehler 2
make[1]: Verzeichnis „/root/deployment/Temp/PF_CPPP/xxx_master“ wird verlassen
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
make: Verzeichnis „/root/deployment/Temp/PF_CPPP/xxx_master“ wird verlassen
```

(i used the -9 parameter...)

## What should have happened?
It should compile without any problems, also if a library (linux .so file) was compressed with upx (-9) before!

## Do you have an idea for a solution?
No, otherwise i would not ask here! ;-)

## How can we reproduce the issue?

1. Compress any Linux .so files with upx (so i already said, i used the -9 option) and try to compile an application with them.

## Please tell us details about your environment.

Debian 9.x, must current version, kernel "4.19.0-0.bpo.5-amd64" from Debian stretch-backports-Repository.

**Comment by martijintro** [comment]
And there are no options like "amd64-shlib" or "linux-shlib", similar to -> https://github.com/upx/upx/issues/116

???

**Comment by martijintro** [comment]
Same problem with freshly compiled 3.96

**Comment by martijintro** [comment]
Is it fixed with the new version 3.95?

If not 100%, it makes no sense for me to compile the 3.95 version too...

**Comment by jreiser** [comment]
@martijintro  I do not understand the error message
```
/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib/libxxx.so: file not recognized: File format not recognized
```
in the Description. How was `libxxx.so` generated?

Please post a complete test case that contains a literal Makefile which causes the problem.  If necessary, then please use something like a compiled `hello.c` or /bin/date (etc.) as a dependency.

**Comment by jreiser** [comment]
This problem is due to a mis-feature of libbfd.  The compressed output from UPX is optimized for small space in the filesystem while preserving executability at run time.  Section headers (ElfXX_Shdr records) are not needed for execution.  All the information that is required at run time is in ElfXX_Phdr records.  Therefore UPX maintains only enough information to re-construct the original input (via `upx -d`), and in particular ElfXX_Shdr records are compressed.  When libbfd tries to find ElfXX_Shdr records in a shared library that was compressed by UPX, then libbfd fails.  All the symbol information that is necessary for linking is preserved in ElfXX_Phdr records.  The runtime linker (whose generic name is `ld-linux.so`) has no trouble finding the information it needs.  Yet libbfd does not make use of that information (which is enough information, just in a different format) and so the static binder /usr/bin/ld, which is implemented using libbfd, gives up.  Complain to the maintainers of libbfd.  This is not a bug in UPX.

**Comment by martijintro** [comment]
OK thx, problem solved by not-using upx for libraries! ;-)

**Comment by w1252675615** [comment]
> OK thx, problem solved by not-using upx for libraries! ;-)
may i ask you how to shrink the linux .so file in the end?

**Comment by martijintro** [comment]
**"may i ask you how to shrink the linux .so file in the end?"**

Leave them umcompressed, that's the solution in my specific case!! ;-)

**Comment by jreiser** [comment]
@w1252675615 Run upx on the .so after /usr/bin/ld is done using the un-compressed .so for linking (static binding) other executables.
