### ISSUE TITLE
Program compressed with upx 3.96 crashes on arm64

### ISSUE THREAD

**Issue by roblub** [upx/upx#351]
## What's the problem (or question)?
It looks like any application compressed with upx 3.96 or later from devel branch crashes on arm64 machines

```
(sid_arm64-dchroot)robert@amdahl:~/upx$ cp /bin/ls  .
(sid_arm64-dchroot)robert@amdahl:~/upx$ src/upx.out ./ls
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-b72eac  Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    138848 ->     67100   48.33%   linux/arm64   ls                            

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
(sid_arm64-dchroot)robert@amdahl:~/upx$ ./ls
Segmentation fault
```

Strace output:
```
(sid_arm64-dchroot)robert@amdahl:~/upx$ strace ./ls
execve("./ls", ["./ls"], 0xffffd19e2f30 /* 19 vars */) = 0
openat(AT_FDCWD, "/proc/self/exe", O_RDONLY) = 3
mmap(NULL, 66748, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffffac628000
mmap(0xffffac628000, 66210, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xffffac628000
mprotect(0xffffac637000, 5308, PROT_READ|PROT_EXEC) = 0
readlinkat(AT_FDCWD, "/proc/self/exe", "/home/robert/upx/ls", 4095) = 19
mmap(0xffffac639000, 208896, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xffffac639000
mmap(0xffffac639000, 128288, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xffffac639000
mprotect(0xffffac639000, 128288, PROT_READ|PROT_EXEC) = 0
mmap(0xffffac669000, 5664, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0x20000) = 0xffffac669000
mprotect(0xffffac669000, 5664, PROT_READ|PROT_WRITE) = 0
mmap(0xffffac66b000, 2288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xffffac66b000
openat(AT_FDCWD, "/lib/ld-linux-aarch64.so.1", O_RDONLY) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\200\20\0\0\0\0\0\0"..., 1024) = 1024
mmap(NULL, 204800, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffffac5f6000
mmap(0xffffac5f6000, 127152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 4, 0) = 0xffffac5f6000
mmap(0xffffac625000, 8312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 4, 0x1f000) = 0xffffac625000
close(4)                                = 0
mmap(NULL, 4096, PROT_READ, MAP_PRIVATE, 3, 0) = 0xffffac5f5000
close(3)                                = 0
munmap(0xffffac628000, 66748)           = 0
brk(NULL)                               = 0xaaaad8ee7000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x6313ac65aab8} ---
+++ killed by SIGSEGV +++
Segmentation fault
```
## What should have happened?
The compressed program should not crash...

## Do you have an idea for a solution?
git bisect shows that the issue is caused by commit d4e2d7e8a80e0e3d95e17bbc0bcf649bad3da19a

I'm also attaching  [binaries.tar.gz](https://github.com/upx/upx/files/4331837/binaries.tar.gz) file which contains original uncompressed ls, and ls compressed by good, and bad versions of upx.

## How can we reproduce the issue?
On arm64 machine:
```
cp /bin/ls .
upx ./ls
./ls

```
However I've just checked the issue does not appear with your precompiled upx binaries.

## Please tell us details about your environment.
```
(sid_arm64-dchroot)robert@amdahl:~$ upx --version
upx 3.96
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

(sid_arm64-dchroot)robert@amdahl:~$ uname -a 
Linux amdahl 4.19.0-8-arm64 #1 SMP Debian 4.19.98-1 (2020-01-26) aarch64 GNU/Linux
```

**Comment by roblub** [comment]
I've just looked at issue #254 referred by the commit that causes the crashes, and I can provide additional information about page size:
```
robert@amdahl:~$ getconf PAGE_SIZE
4096
robert@amdahl:~$ grep 64K /boot/config-4.19.0-8-arm64 
# CONFIG_ARM64_64K_PAGES is not set
```
Unfortunately I cannot check if it would work with 64K pages or not.

**Comment by jreiser** [comment]
This issue is caused by a bug in the Linux kernel system call `execve`().
```
$ readelf --segments ls.bad-upx-4e2d7e8

Elf file type is DYN (Shared object file)
Entry point 0xf87c
There are 3 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000102b2 0x00000000000102b2  R E    0x10000
  LOAD           0x0000000000000000 0x0000000000020000 0x0000000000020000
                 0x0000000000000000 0x00000000000128f0  RW     0x10000
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
```
Notice that the second [PT_]LOAD has `0 == FileSiz` and `0x128f0 == MemSiz`; this segment is all .bss.  The bug is that `execve` does not create those .bss pages in the address space.
This can be seen by making a copy of the file, changing the Elf64_Ehdr.e_entry at offset 0x18 from 0xf87c to 0, and running under the gdb debugger.  That makes the first instruction be an undefined instruction `0x464c457f`, so gdb will catch SIGILL before the program can change anything.
```
$ gdb ls.foo
(gdb) run
Starting program: /home/user/github-issue351/ls.foo 

Program received signal SIGILL, Illegal instruction.
0x0000fffff7fcd000 in ?? ()
(gdb) x/i $pc
=> 0xfffff7fcd000:	.inst	0x464c457f ; undefined
(gdb) info proc
process 23612
cmdline = '/home/user/github-issue351/ls.foo'
cwd = '/home/user/github-issue351'
exe = '/home/user/github-issue351/ls.foo'
(gdb) shell cat /proc/23612/maps
fffff7fcd000-fffff7fde000 r-xp 00000000 b3:03 664969                     /home/user/github-issue351/ls.foo
fffff7feb000-fffff7fec000 r--p 00000000 00:00 0                          [vvar]
fffff7fec000-fffff7fed000 r-xp 00000000 00:00 0                          [vdso]
fffff7fed000-fffff8000000 rw-p 00000000 00:00 0                          [heap]
fffffffdf000-1000000000000 rw-p 00000000 00:00 0                         [stack]
(gdb)
```
Notice that there are no pages with protection` rw-p` between the mapping of ls.foo and the `[vvar]` segment.  `execve` saw `0 == .p_filesz` and decided `there is nothing to do`, forgetting about the .bss  `0x128f0 == .p_memsz`.  Also notice that [in this case] there is unused address space from 0xfffff7fde000 to 0xfffff7feb000 which is a span of 0xd000 bytes.  The UPX run-time decompression stub knows that UPX compressor set PT_LOAD[1].p_memsiz so that the span of reserved pages from PT_LOAD[0].p_vaddr to (PT_LOAD[1].p_memsz + PT_LOAD[1].p_vaddr) is long enough for all the de-compressed PT_LOAD to fit.  But the Linux kernel bug makes that false.  The space left by Linux (0xd000 in this case) is random over a small number of pages, as one of the attempts to foil malware.  If the space is large enough, then the un-compressed code will fit and run correctly.  If not, then the `[vvar]` and `[vdso]` mappings will be removed so that it does fit.  But the [PT_]INTERP  /lib/ld-linux-aarch64.so.1 depends on those mappings, and this causes SIGSEGV or other badness.
The UPX stub wants to re-use the original address space that Linux chose for a -fPIE ET_DYN file in order to avoid fragmentation of the address space.
It may be possible to workaround the kernel bug by setting .p_filesz to some small non-zero value; the UPX de-compression stub will just overwrite the bytes.  This worked in the past on some other architectures.

**Comment by markus-oberhumer** [comment]
Is this fixed in current git or Linux kernel?

**Comment by tmm1** [comment]
This seems to still be happening with golang binaries (for example https://github.com/abtreece/confd/releases/tag/v0.18.1 and https://github.com/hadolint/hadolint/pull/665#issuecomment-871188169). Is there any fix possible?

**Comment by jreiser** [comment]
Please try the amd64 upx from https://github.com/upx/upx/suites/11354265989/artifacts/583733494 , or from any recent successful ContinuousIntegration build listed on https://github.com/upx/upx/actions.  UPX itself is toally cross-platform, so any UPX can process executables for arm64-Linux (or any other supported platform.)

When I use UPX git-f30266+ to process the arm64 executable in https://github.com/abtreece/confd/releases/download/v0.18.1/confd-v0.18.1-linux-arm64.tar.gz [I picked arm64 because that is named in the title of this https://github.com/upx/upx/issues/351], then I can run the compressed output:
```
$ gdb confd.upx
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
(No debugging symbols found in confd.upx)
(gdb) run
Starting program: /home/jreiser/github-issue351/confd.upx 
[New LWP 556]
[New LWP 557]
[New LWP 559]
[New LWP 558]
[New LWP 560]
2023-03-05T23:40:06Z rpi4-20220121 /home/jreiser/github-issue351/confd.upx[553]: INFO Backend set to etcd
2023-03-05T23:40:06Z rpi4-20220121 /home/jreiser/github-issue351/confd.upx[553]: INFO Starting confd
2023-03-05T23:40:06Z rpi4-20220121 /home/jreiser/github-issue351/confd.upx[553]: INFO Backend source(s) set to http://127.0.0.1:2379
[New LWP 561]
2023-03-05T23:40:06Z rpi4-20220121 /home/jreiser/github-issue351/confd.upx[553]: WARNING Cannot load template resources: confdir '/etc/confd' does not exist
[New LWP 562]
[New LWP 563]
^C
Thread 1 "confd.upx" received signal SIGINT, Interrupt.
0x000000000007854c in ?? ()
(gdb) bt
#0  0x000000000007854c in ?? ()
#1  0x0000000000000080 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info proc
process 553
cmdline = '/home/jreiser/github-issue351/confd.upx'
cwd = '/home/jreiser/github-issue351'
exe = '/home/jreiser/github-issue351/confd.upx'
(gdb) shell ps
    PID TTY          TIME CMD
    533 pts/0    00:00:00 bash
    547 pts/0    00:00:00 gdb
    553 pts/0    00:00:00 confd.upx
    564 pts/0    00:00:00 ps
(gdb) shell ps axl | grep confd
0  1000     547     533  20   0 375000 31952 do_wai Sl+  pts/0      0:00 gdb confd.upx
0  1000     567     565  20   0   2904   656 pipe_r S+   pts/0      0:00 grep confd
```
and it looks like the app is waiting for input.

I cannot identify any actual executable that is referenced from https://github.com/hadolint/hadolint/pull/665#issuecomment-871188169  Please specify the URL to an actual executable.
