### ISSUE TITLE
I/O failure reading contents of the bundle, on MacOS

### ISSUE THREAD

**Issue by thomasd3** [upx/upx#397]
## What's the problem (or question)?

```
Failure processing application bundle; possible file corruption.
I/O failure reading contents of the bundle.
```

This error is from .net core trying to unpack the application (when it is published as a single file). This means that the integrity of the executable can't be verified by .net core after it has been decompressed by UPX.

## What should have happened?

the app should have run :)

## Do you have an idea for a solution?

The decompression through the command line is working, so I would guess the execution, after decompression, is probabl where there is something to look at.
It looks like some antivirus have caused the exact same problem in the past.

## How can we reproduce the issue?

This is happening on .net core 3.1 applications. The test application is built with:

```
dotnet publish --nologo -r osx-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
```

It builds a self contained (single file) app. The app will compress properly and UPX will also be able to decompress it properly with the command line, but the app will not decompress when executed.

What is interesting is that if you compress the app with upx and then decompress with with -d, the app passes .net core's integrity check, but not when self decompressed.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: MacOS Catalina
* Host CPU architecture: x64
* Target Operating System and version: MacOS Catalina
* Target CPU architecture: x64

**Comment by MouriNaruto** [comment]
I have found the same issue, but my case is under Windows.

**Comment by bitraid** [comment]
> I have found the same issue, but my case is under Windows.

This is the same as #274. You shouldn't compress these executables with upx: The actual exe size is a just a few kilobytes - the rest are overlay data which can't be compressed by upx (they are copied by default). The overlay data are not loaded in memory when the exe is run -  the exe reads them from disk and extracts its contents in `%TEMP%\.net` on first run (and then the main program is started from there). Because the exe expects to find the overlay at a specific offset (it doesn't calculate it at runtime), changing the size of the exe (compressing) will fail to do so (but even if it did, the gains would be miniscule).

**Comment by caesay** [comment]
> The actual exe size is a just a few kilobytes
I can't speak for net5, but in net6, the native windows singlefilehost exe is 8MB+. The "overlay data" (ie. the managed assemblies) that gets added to the end, no longer need to be extracted to a temporary directory, and also supports compression. The ideal upx behavior would be to compress the 8mb native binary, but leave the compressed managed assemblies at the end alone.
