### ISSUE TITLE
Feature Request: Any plan to FAT Binary / Universal Binary for Windows ?

### ISSUE THREAD

**Issue by metarutaiga** [upx/upx#403]
## What's the problem (or question)?
Could it merges x86/x64/arm/arm64 into one executable files?

## What should have happened?
I want to reduce file counts.

## Do you have an idea for a solution?
1. The entry is x86 binary
2. Extract the specific arch segments
3. Check system native arch
4. Call switch mode system call
   * http://blog.rewolf.pl/blog/?p=102
   * https://blogs.blackberry.com/en/2019/09/teardown-windows-10-on-arm-x86-emulation

## How can we reproduce the issue?
I don't have any example.
But I see the similar idea https://github.com/sjmulder/fatpack
My multi-platform files is there https://github.com/metarutaiga/xxImGui/releases/tag/20200808

## Please tell us details about your environment.
OS : macOS 11.0 beta 5

**Comment by jreiser** [comment]
Please upload ("Attach files by ...") or provide the URL to an actual file of the kind alluded to here.  Compress the upload using zip, gzip, or .tgz in order to save space on github.

**Comment by metarutaiga** [comment]
> Please upload ("Attach files by ...") or provide the URL to an actual file of the kind alluded to here. Compress the upload using zip, gzip, or .tgz in order to save space on github.

Ok, My multi-platform files is there https://github.com/metarutaiga/xxImGui/releases/tag/20200808

**Comment by jreiser** [comment]
I'm looking for one file that is FAT: contains "the same" executable for two or more architectures/OS_environments, etc; but I do not see any such file.  At that URL, I see xxImGui_20200808.{dmg,.apk,.zip} which are all containers: .dmg for MacOS, .apk for Android, .zip for Windows; but the contents of any container are all non-FAT: for only one architecture.  Please point me to an actual FAT file.

**Comment by metarutaiga** [comment]
> I'm looking for one file that is FAT: contains "the same" executable for two or more architectures/OS_environments, etc; but I do not see any such file. At that URL, I see xxImGui_20200808.{dmg,.apk,.zip} which are all containers: .dmg for MacOS, .apk for Android, .zip for Windows; but the contents of any container are all non-FAT: for only one architecture. Please point me to an actual FAT file.

Oh, the FATPACK builder is FAT Binary.  https://github.com/sjmulder/fatpack/releases/tag/1.0

**Comment by bitraid** [comment]
What this tool does, is to include the different architecture exes in its resource section, and on start, extract each exe in temp and try to run it (if one fails it tries the next - that’s why the least compatible must be first). This is very different than what upx does - you can still use upx to pack this *fat* exe though.

**Comment by bitraid** [comment]
Also, your files are multiplatform - not multiarchitecture of the same platform (and, of course, you can’t have an executable that runs on different operating systems).

**Comment by bitraid** [comment]
And finally, if this was going to be done in the upx way, how could you switch to native ARM when running on x86 emulation?

**Comment by jreiser** [comment]
UPX already handles "fat" binaries on MacOS; see `__packed_struct(Mach_fat_header)` (which is just the Apple definition), and `class PackMachFat` (the UPX class) in src/p_mach.{h,cpp}.  Essentially `Mach_fat_header` is a directory at offset 0 in the file, and it contains the type, offset, and length of each of the "thin" binaries in the rest of the file.  Because UPX is totally cross-architecture at compress time, then UPX handles Mach "fat" somewhat easily, compressing each binary separately (and natively for the architecture of that binary), then "shelving" the compressed binaries consecutively under a new `Mach_fat_header`.

The "FAT" binary for Windows that is described by @metarutaiga above in this Issue, appears to be somewhat crude. Windows knows "nothing" about the idea of the container or its contents.  The "fat" executable simply tries to execute each contained `Resource` in turn, recovering from the "bad format" error if the selected format is not supported by the current operating system.  UPX already supports compression for such an executable, at least to the degree that `Resource`s can be the subject of compression as "plain old data" (not recognized as an executable format in itself).  Even more, the FATPACK builder could send each `Resource` to UPX separately for compression, then FATPACK the compressed results.  So it appears that UPX should do nothing special for this FATPACK idea; the onus is on the FATPACK builder.
