### ISSUE TITLE
Add support for 'Mach-O 64-bit dynamically linked shared library arm64'

### ISSUE THREAD

**Issue by JuunChen** [upx/upx#404]
## What's the problem (or question)?

Add support for `Mach-O 64-bit dynamically linked shared library arm64` (de)compression.

## What should have happened?

I know that [#57](https://github.com/upx/upx/issues/57) and [#219](https://github.com/upx/upx/issues/219) added " Mach-O 64-bit executable x86_64" and "Mach-O 64-bit dynamically linked shared library x86_64".

I can also compress the [plugin](https://github.com/upx/upx/files/2355379/plugin.zip) mentioned in #219 sucessfully. But I can't compress the `Mach-O 64-bit dynamically linked shared library arm64` file.

The follow is the error:
```
$ ./src/upx.out /Users/Desktop/App
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-642829  Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: /Users/Desktop/App: UnknownExecutableFormatException

Packed 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.
```
Here is my file:  [App.zip](https://github.com/upx/upx/files/5148143/App.zip)

## How can we reproduce the issue?

1. download  [App.zip](https://github.com/upx/upx/files/5148143/App.zip)
2. unzip the App.zip
3. `upx app`

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.0.0-git-6428292477e0 (devel branch)
* Host Operating System and version:macOS Catalina 10.15.5 
* Host CPU architecture:x86_64
* Target Operating System and version:iOS
* Target CPU architecture:arm64

**Comment by whisper-bye** [comment]
+1

**Comment by sptndc** [comment]
+1

**Comment by fine-00** [comment]
is this work in progress? I had the same question as above and was wondering if this feature will be added soon.

**Comment by jreiser** [comment]
@fine-00  `Work in progress? ` It's not forgotten, but the priority is low (Android is higher), and there are significant barriers.  Towards the goal of "secure execution (no malware)", MacOS keeps adding hurdles (can be yearly!)  for executing de-compressedof code.  Apple's documentation in this area is sparse to non-existent. Apple's open-source version of the Darwin operating system kernel (derived from BSD) does not compile, and thus cannot be run under a user-mode debugger as a runtime "accelerator" (faster and more reliable than visual inspection of source code) to determine what are the actual hurdles for de-compressed code.

Then there is your specification of `Target Operating System and version:iOS`.  iOS is even less friendly to UPX than MacOS.

`Soon?` If there is a breakthrough or two, then it could happen in calendar 2023, but otherwise probably not.  It is an intriguing possibility that a shared library `dlopen()` could be easier than a main program `execve()`, but this has not been examined.

**Comment by brainexcerpts** [comment]
+1 to support MacOS in general and shared libs especially 🙇
