### ISSUE TITLE
Memory leaks caused by new() and fuzzer

### ISSUE THREAD

**Issue by liamjm** [upx/upx#428]
## What's the problem (or question)?
The code currently throws exceptions and exits when errors are found in the packing/unpacking process. Memory is allocated used new() and freed up using delete.
The fuzzer created in https://github.com/upx/upx/pull/420 disables the exiting because this would break the fuzzing process.
As a result, the fuzzer detects leaks. These aren't a problem when run as a standalone executable. However, this will be a problem if create a sandbox (https://github.com/upx/upx/issues/427), and also disable the exiting. 

Example: https://github.com/liamjm/upx_fuzzing_corpus#testcase-5924189438607360

## What should have happened?
No memory leaks.

## Do you have an idea for a solution?
a) Still exit in the sandbox: this makes the sandbox slower as the sandboxee process will need to restarted
b) Manually manage the memory in the cases when we throw(), by adding delete calls to each appropriate site
c) Migrate to managed memory, such as unique_ptr<> 

## How can we reproduce the issue?
1. download https://github.com/liamjm/upx_fuzzing_corpus/raw/master/testcase-5924189438607360
2. build UPX with  `export BUILD_TYPE_SANITIZE=1; make all`
3. run UPX to decompress: `upx -d  testcase-5924189438607360`

## Please tell us details about your environment.

* UPX version used (`upx --version`): `upx 4.0.0-git-ae607f61a04e+`
* Host Operating System and version: linux
* Host CPU architecture: x64
* Target Operating System and version: win32
* Target CPU architecture: x86

**Comment by liamjm** [comment]
re (c): I am not aware of what the version of C++ this code base aims to work with, but unique_ptr<> is c++11 onwards:

https://en.cppreference.com/w/cpp/memory/unique_ptr

So this might not be an option if the code is supposed to work with earlier versions.

**Comment by jreiser** [comment]
The upx-stubools https://github.com/upx/upx-stubtools for each supported architecture (to make sure that the build of the run-time decompression stubs (src/stub/src/*-main.c, etc.) is reproducible by each developer) uses (on x86_64, for instance):
```
$ amd64-linux/gcc-3.4.3.20050507-glibc-2.3.5/bin/x86_64-unknown-linux-gnu-gcc-3.4.4
x86_64-unknown-linux-gnu-gcc-3.4.4 (GCC) 3.4.4 20050507 (prerelease)
Copyright (C) 2004 Free Software Foundation, Inc.
```
so that would be too early to support unique_ptr.  However, that is just for compiling the code of the **run-time** de-compression stub, which cannot use any run-time language support libraries anyway.  The upx.exe executable can use anything that is reasonably expected to be available to those who run the compressor.  Even this is open to question on Windows: just in the last few years MSVC runtime environments have differed as to whether command-line processing includes globbing (expansion of meta characters such as '`*`' in filenames) or not.

On to specific proposals:
0) If the BUILD_TYPE_SANITIZE=1 does not have a means omit leak detection (or at least reporting and reaction) then that is a **DESIGN ERROR** in the sanitizer.  They didn't learn from valgrind/memcheck.
c) unique_ptr is ugly and expensive in both space and time.  It's also an indication of bad programmer laziness when usage is as simple as the upx compressor.
b) Adding code just before each instance of throwCantPack() [etc.] is tedious, error-prone, and a maintenance nightmare.
a) Aim for correctness before optimization: exit() as usual works.  And if something other than process exit is desired, then why not write a new private exit() routine for use when upx is operating in the sandbox?

Finally, upx already has a class MemBuffer (src/mem.h) which implements the idea of unique_ptr, namely "deallocate when going out-of-scope".  This works whenever the managed memory is statically known.  In the case of class `PeFile` (the particular case from `PeFile::Resource::build()` in the testcase of the Description of this Issue), it looks like each `new` within a member function can be associated with a particular member of the class.  So for instance, each member of type `upx_byte *` would become a MemBuffer, and the `new` would become buffer.alloc(), and the existing `delete` (there are no leaks in non-sanitizing operation (!)) would be subsumed by the MemBuffer going out-of-scope, either by natural flow of control, or when the class instance is deleted by going out-of-scope as a result of the `throw` exiting the frame where the class was instantiated.

**Comment by liamjm** [comment]
Thanks for the response.

Replies:
0) Yes, leak detection can be disabled, using -detect_leaks (see https://llvm.org/docs/LibFuzzer.html). However, the fuzzing will have reduced effectiveness if there are leaks as the fuzzer process will eventually run out of memory.
c) I don't share your concerns of unique_ptr being expensive, but agree it can lead to some extra casting which makes things more ugly. I also don't share your opinion that it is bad programmer laziness - I would argue that using the compiler to ensure memory safety is an indication of an adept programmer.
b) Agreed, this approach is not ideal, it was included for completeness
a) A custom exit() sounds good, I'm just not sure how it would fix the memory leaks.

#432 implements the suggested approach of using MemBuffer. There are plenty more calls to New(), but this is a start.

**Comment by liamjm** [comment]
For the purposes of tracking progress on this clean up, as of d4881223249f2aaec74fbb950cd57e8f7d597dbf, there are 47 uses of New(). As of b19f5f3282316a7b9a0bd063fce9e657e09114fb, this is down to 40.

Numbers from:
```find src -name "*.cpp" | xargs grep  " New("  | wc -l ```

**Comment by jreiser** [comment]
Blindly reducing the lexical instances of `new` and `delete` seems to be a scam ... because it **is** a scam! If the result of a lexical `new` becomes owned by a member of a class, and if the destructor of the class performs a lexical `delete` of that class member, then the overall effect is equivalent to some "auto-managed" member (via `unique_ptr<>` or `MemBuffer`, etc.) going out-of-scope; there is no leak in either case, whether by `throw` or (not) calling `exit`.  Thus the only good thing about blind reduction of lexical `new`+`delete` is that it becomes easier to find the instances of `new` that lack a corresponding lexical `delete` in the destructor.  "Auto-managed" storage costs more in space, execution time, and development time than "naked" storage which uses lexical `delete` in the destructor, and those costs should be counted when deciding how to implement.
