### ISSUE TITLE
Cannot launch packed file

### ISSUE THREAD

**Issue by malikm** [upx/upx#43]
## What's the problem (or question)?

The attached packed file cannot be executed. Nothing happens.

## What should have happened?

I have used UPX for several other previous versions of the same program and it worked without issues.
Unpacking the same file works and EXE is properly launched.

## Do you have an idea for a solution?

No.

## How can we reproduce the issue?

1. Just launch the linked executable - nothing will happen, the program is not launched.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.91 and 3.92 affected too
* Operating System and version: Windows 10 x64
* CPU architecture: Intel

[HWiNFO64_UPX_fail.zip](https://github.com/upx/upx/files/673896/HWiNFO64_UPX_fail.zip)

**Comment by ml1050** [comment]
This bug is not related to TLS handling, so it's not fixed yet on the devel branch. It seems like it is related to filter handling.

**Comment by ml1050** [comment]
The file works fine when compressed with --no-filter. So this is a filter problem. Looking at it...

**Comment by ml1050** [comment]
John, it seems the amd64 assembly unfilter code has some problems here. My guess is that in bxx.S:

ckstart:
        subq $4,%rcx

should be changed to

        subq $4,%rcx
ckstart:

Can you confirm this? Using this change, the file was uncompressed and run without problems.

**Comment by jreiser** [comment]
Yes, there is a bug; I'm working on it.

**Comment by AraHaan** [comment]
I have a question about the packer stub to. somewhere close to the entry point does it somehow set some sort of address that the stub looks for and if that address does not exist it crashes? And how can one be able to change that address by hand if they was to like hack the exe into 1 section but yet preserve the same size as if it was not hacked to 1 section and packed? Because this was precisely what I was doing before and the only way I could get it to work was to have the same # of size from the original 1st section to be all null save it on disk then save all the other sections to disk, open MadEdit to merge the data together and then put them back into the exe as 1 section the problem with that is it makes it somewhat larger than the original compiled exe which kinda defeats the purpose of UPX compressing it. And if so mow many bytes after the entry Point or wherever is it? So that way I can dynamically locate that byte or multiple bytes to be able to achieve what I want in this.

**Comment by ml1050** [comment]
@AraHaan, unfortunately I do not understand what you wrote. I have no idea what you mean by "some sort of address that the stub looks for and if that address does not exist it crashes". Can you elaborate on this?

**Comment by AraHaan** [comment]
Remember how UPX generates the 1st section that actually references information from the second section but the size of the first section is 0 Well that is what I mean by it where it literally acts as if it is a dummy section. it is better explained using a picture I know.

![ss 2016-12-31 at 05 40 32](https://cloud.githubusercontent.com/assets/15173749/21577310/1082c8da-cf1c-11e6-8bd3-7e31fd6e845f.png)

Basically the RAW size of the first section is 0 but the second is of another size and the difference in the offset(virtual Address) from the first section to the next is by x(like if the first Virtual Address is 1000 but the other one is B000 bytes the issue with that is I have to factor in that difference by filling the first x bytes (same as that before with all NULL) Basically I would have to take the difference (that being B000 - 1000 = A000) being filled with NULL's only to get it to work wich I would like to just not have A000 bytes fileld with NULLs. Instead I would like to take the addresses of everything that makes it run and move it up by A000 in this case. And yet make it operate as if it was not a hacked compress down to 1 section and makes it harder to decompress with UPX if I dont want them to use UPX to decompress what I compressed with it.

**Comment by ml1050** [comment]
The zero bytes in UPX0 are there for the uncompressed data. The compressed data with the uncompressor code is in UPX1. If they would be combined into one section, then the stub should start with copying the compressed data and the decompressor code upward to make room for the decompressed data, then jump to the copied stub code. This could be done, but it would be slower. 

Then comes the problem of windows' SW DEP - some of microsoft's runtime checks the permission bits of the section it runs in - this means no writeable & executable data in the same section. Finally some internal windows dll/utility wants(wanted) the resource data in a section with the name ".rsrc". 

That's why UPX has 3 sections for the win32/pe and win64/pe formats. 

And finally UPX is a compressor and a protector. And we are not interested in making a protector from it.

**Comment by markus-oberhumer** [comment]
@jreiser : Any news on this?

**Comment by ml1050** [comment]
Please try the devel branch.

**Comment by markus-oberhumer** [comment]
Should be fixed on devel branch.

**Comment by WGH-** [comment]
FWIW, this problem also happened on Linux with some Go binaries. The symptom is the following, and  ba9118aa58 is the commit that fixes it.
```
Program received signal SIGSEGV (fault address 0x6ac000)

          0x400000           0x6ac000 rwxp   2ac000 0      
          0x6ac000           0x9f9000 ---p   34d000 0      [heap]
          0x9f9000           0xfe1000 rwxp   5e8000 0      [heap]
    0x7ffff7ffa000     0x7ffff7ffd000 r--p     3000 0      [vvar]
    0x7ffff7ffd000     0x7ffff7fff000 r-xp     2000 0      [vdso]
    0x7ffffffde000     0x7ffffffff000 rwxp    21000 0      [stack]
0xffffffffff600000 0xffffffffff601000 r-xp     1000 0      [vsyscall]

```
