### ISSUE TITLE
CantPackException: DT_ tag above stub

### ISSUE THREAD

**Issue by pr0fess0r0** [upx/upx#44]
~/Downloads$ ./upx libxul.so
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: libxul.so: CantPackException: DT_ tag above stub

Packed 0 files.
~/Downloads$ ./upx libxul.so 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2016
UPX 3.92        Markus Oberhumer, Laszlo Molnar & John Reiser   Dec 11th 2016

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: libxul.so: CantPackException: DT_ tag above stub
...
same result from windows
libxul.so extracted from this archive:
https://ftp.mozilla.org/pub/firefox/releases/50.1.0/linux-i686/en-US/firefox-50.1.0.tar.bz2
~/Downloads$ file libxul.so 
libxul.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x0070b722ad0795f3e08ed8d9442ef26aaf75d62a, stripped
but i can compress with upx 3.92 libxul.so from this package:
http://security.ubuntu.com/ubuntu/pool/main/f/firefox/firefox_50.1.0+build2-0ubuntu0.14.04.1_i386.deb

**Comment by jreiser** [comment]
This is a very arcane technical situation; I'll assume that you are qualified.
Buf if you are, then you should read the source code to UPX.  p_lx_elf.cpp:
```
        // Heuristic HACK for shared libraries (compare Darwin (MacOS) Dylib.)
        // If there is an existing DT_INIT, and if everything that the dynamic
        // linker ld-linux needs to perform relocations before calling DT_INIT
        // resides below the first SHT_EXECINSTR Section in one PT_LOAD, then
        // compress from the first executable Section to the end of that PT_LOAD.
        // We must not alter anything that ld-linux might touch before it calls
        // the DT_INIT function.
        //
        // Obviously this hack requires that the linker script put pieces
        // into good positions when building the original shared library,
        // and also requires ld-linux to behave.
```
The two shared libraries may have started from the same (or very similar) source code, but they were compiled and linked by very different software tool chains.  Let's call the libraries libxul.so.mozilla and libxul.so.ubuntu.  First, extract the file libxul.so from the mozilla tarball and from the ubuntu .deb.  [I used 'alien' to convert the .deb to a .tgz because I don't know how to pick apart a .deb.]  Run "readelf --all" on both libxul.so  to see the structure of the shared libraries.  libxul.so.mozilla has
```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x00000000 0x00000000 0x16bb28 0x16bb28 R E 0x1000
  LOAD           0x16c2b8 0x0040b2b8 0x0040b2b8 0x3f9813c 0x3f9813c R E 0x1000
  LOAD           0x41043f8 0x043a43f8 0x043a43f8 0x294d68 0x2ceb30 RW  0x1000
  DYNAMIC        0x435c988 0x045fc988 0x045fc988 0x00240 0x00240 RW  0x4
```
while libxul.so.ubuntu has
```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x00000000 0x00000000 0x3d50f94 0x3d50f94 R E 0x1000
  LOAD           0x3d51c40 0x03d51c40 0x03d51c40 0x259e90 0x29163c RW  0x1000
  DYNAMIC        0x3f76650 0x03f76650 0x03f76650 0x00258 0x00258 RW  0x4
```
We see that mozilla has 3 PT_LOAD while for ubuntu just 2 PT_LOAD suffice.  The first two PT_LOAD in mozilla probably could have been contiguous; why aren't they?

Another difference: mozilla has
```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .note.gnu.build-i NOTE            00000134 000134 000024 00   A  0   0  4
  [ 2] .hash             HASH            00000158 000158 011a50 04   A  3   0  4
  [ 3] .dynsym           DYNSYM          00011ba8 011ba8 026810 10   A  4   1  4
  [ 4] .dynstr           STRTAB          000383b8 0383b8 09b444 00   A  0   0  1
  [ 5] .gnu.version      VERSYM          000d37fc 0d37fc 004d02 02   A  3   0  2
  [ 6] .gnu.version_d    VERDEF          000d8500 0d8500 000038 00   A  4   2  4
  [ 7] .gnu.version_r    VERNEED         000d8538 0d8538 000550 00   A  4  13  4
  [ 8] .elfhack.text.v0  PROGBITS        000d8a88 0d8a88 00007a 00  AX  0   0  1
  [ 9] .elfhack.data.v0  PROGBITS        000d8b08 0d8b08 08a920 08   A  0   0  8
  [10] .rel.dyn          REL             00163428 163428 001678 08   A  3   0  4
  [11] .rel.plt          REL             00164aa0 164aa0 007088 08  AI  3  13  4
  [12] .init             PROGBITS        0040b2b8 16c2b8 000030 00  AX  0   0  4
  [13] .plt              PROGBITS        0040b2f0 16c2f0 00e120 04  AX  0   0 16
  [14] .text             PROGBITS        00419410 17a410 2f17418 00  AX  0   0 16
  [15] .fini             PROGBITS        03330828 3091828 00001c 00  AX  0   0  4
```
(note that .elfhack.text.v0 at 0d8a88 has eXecutable Flg [flag])
while ubuntu has
```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .note.gnu.build-i NOTE            00000134 000134 000024 00   A  0   0  4
  [ 2] .gnu.hash         GNU_HASH        00000158 000158 002be0 04   A  3   0  4
  [ 3] .dynsym           DYNSYM          00002d38 002d38 010090 10   A  4   1  4
  [ 4] .dynstr           STRTAB          00012dc8 012dc8 02299a 00   A  0   0  1
  [ 5] .gnu.version      VERSYM          00035762 035762 002012 02   A  3   0  2
  [ 6] .gnu.version_d    VERDEF          00037774 037774 000038 00   A  4   2  4
  [ 7] .gnu.version_r    VERNEED         000377ac 0377ac 000590 00   A  4  13  4
  [ 8] .rel.dyn          REL             00037d3c 037d3c 32b698 08   A  3   0  4
  [ 9] .rel.plt          REL             003633d4 3633d4 006850 08   A  3  11  4
  [10] .init             PROGBITS        00369c24 369c24 000023 00  AX  0   0  4
  [11] .plt              PROGBITS        00369c50 369c50 00d0b0 04  AX  0   0 16
  [12] .text             PROGBITS        00376d00 376d00 2944d74 00  AX  0   0 16
  [13] .fini             PROGBITS        02cbba74 2cbba74 000014 00  AX  0   0  4
```
and the first eXecutable section is .init at 00369c24.  The fact that these addresses are so far apart is a clue.  Another clue is ubuntu's .rel.dyn of Size 32b698, while mozilla's .rel.dyn has Size just 001678.

Looking at ubuntu's .rel.dyn, there are 415443 entries, but the first 405810 are R_386_RELATIVE to consecutive addresses.  That's a failure of the compiler and linker to avoid using the ProgramLinkageTable when resolving a CALL to a file-scope 'static' function.  Ubuntu has a .gnu.hash Section which usually indicates a newer linker than mozilla's corresponding .hash Section.  The indications are that ubuntu used a newer linker but an older compiler.

When compressing shared libraries, UPX depends on the exact arragement of the code.  These two libxul.so have arrangements that are different, and that explains UPX's differing behavior.

**Comment by jreiser** [comment]
This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=894267#c0 .  The consecutive locations being relocated are C++ virtual function tables.
