### ISSUE TITLE
Unity libil2cpp.so crash on arm64-v8a platform

### ISSUE THREAD

**Issue by ysuiboli** [upx/upx#458]
## What's the problem (or question)?

As the title said , it crashed after using upx compressed.  On armeabi-v7a , it works fine.

## What should have happened?

It should not crash after using upx compressed on arm64-v8a platform.

## Do you have an idea for a solution?

No solution here.

## How can we reproduce the issue?

1.A Unity demo apk needed, and it should inlcude arm64-v8a platform.
2.Upack the apk, and then replaced the libil2cpp.so in the arm64-v8a's folder, last repack it.
3.Run the apk on Android phone which support arm64-v8a platform. After launching , it will show you crash.

![image](https://user-images.githubusercontent.com/5533498/107022334-371e4d00-67e0-11eb-9959-14f124985b81.png)

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.0.0-git-319b97711e74+
* Host Operating System and version: Linux 5.4.0-58-generic
* Host CPU architecture: 64-Ubuntu
* Target Operating System and version: Android 6.0
* Target CPU architecture: arm64-v8a

**Comment by jreiser** [comment]
Please upload ("Attach files by ..."), provide the URL, or email an actual apk which suffers the crash. Apply zip or gzip to reduce the size.  Exhibiting an actual apk which crashes, enables the shortest time-to-reproduce the problem, which is the key to debugging.

**Comment by ysuiboli** [comment]
tks for reply.

Here is the original libil2cpp.so on arm64-v8a platform from the apk.
[libil2cpp.zip](https://github.com/upx/upx/files/5938172/libil2cpp.zip)

How to reproduce: 
1.Writing a demo to 'System.loadLibrary("il2cpp");' ,  put it under arm64-v8a platform folder. 
2.Generating a apk by above. And then, it will crash which happened just at the moment of  'System.loadLibrary("il2cpp")', no more invoking method in libil2cpp.so needed.

**Comment by Ficing** [comment]
@jreiser Any update for this case?

**Comment by ysuiboli** [comment]
@jreiser Did you reproduce it in the above way? Any progress?

**Comment by jreiser** [comment]
One problem is shown by `readelf --segments libil2cpp-compressed.so`:
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000001ca4410 0x0000000001ca4410  R E    0x10000
  LOAD           0x0000000001cb0608 0x0000000004571608 0x0000000004571608
                 0x00000000005d1450 0x00000000008a3538  RW     0x10000
```
In the second [PT_]LOAD, the difference (.p_vaddr - .p_offset) of 0x28c1000 is divisible only by 0x1000 (4kB) and not by by .p_align which is 0x10000 (64kB).

**Comment by jreiser** [comment]
Notice the size of the files, which are in approximate ratio 4:2:1 :
```
 78848744 libil2cpp.so
 36182652 libil2cpp.so.upx
 19488842 libil2cpp.zip
```
The .zip is so much smaller because it can compress the relocation information.  The dynamic loader performs relocation before calling the DT_INIT, so UPX cannot compress the relocation information:
```
Relocation section '.rela.dyn' at offset 0xa800 contains 598900 entries:
Relocation section '.rela.plt' at offset 0xdbfae0 contains 379 entries:
```
The 598,900 relocations are for several tables.  Many of the locations are consecutive, and most of the entries are the addresses of subroutines. Each Elf64_Rela uses 24 bytes, so the dynamic loader must plow through about 14.3 MB of information, writing almost 4.8MB.  This takes time, too!  An alternative encoding and code generation should be considered.  One aarch64 instruction can generate any constant in the interval (-64K, +64K), and a subroutine entry point is divisible by 4.  So 1MB/2 of address space can be covered by direct enumeration.
