### ISSUE TITLE
Noticeable memory footprint increase when using upx with GraalVM

### ISSUE THREAD

**Issue by jvican** [upx/upx#459]
## What's the problem (or question)?

I've made some measurements to check the memory footprint of a Scala application compiled to native through GraalVM with and without UPX. It looks like when the binary is passed through upx, the memory footprint is increased substantially (not 2x but close to it). For example, my native app takes 50MB when it doesn't use upx and 100MB when it does at startup.

## What should have happened?

The memory footprint should be the same regardless if I'm using upx or not because it's one of the goals of the project: "Programs and libraries compressed by UPX are completely self-contained
and run exactly as before, with no runtime or memory penalty for most of the supported formats".

## Do you have an idea for a solution?

No, I don't. I'm not sure what might be at play here. I've thought about the possibility of a bug in upx.

## How can we reproduce the issue?

This is happening with an application that's closed source. I cannot provide a reproduction for this issue and I'm yet to try this is an open source version of my application that uses similar dependencies. I understand this might make this ticket not actionable. I have created it mostly to let people having a similar issue find this ticket.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.96
* Host Operating System and version: Linux 5.3.0-1023-aws #25~18.04.1-Ubuntu 
* Host CPU architecture: x86_64
* Target Operating System and version: Linux 5.3.0-1023-aws #25~18.04.1-Ubuntu
* Target CPU architecture: x86_64

Thanks for your work with this library.

**Comment by jreiser** [comment]
There's a difference between memory footprint (RAM consumption after demand paging has been satisfied) and address-space footprint (page table size).  For a ET_EXEC executable, then the de-compressed region must overlap the same address space as the original compressed region.  This can be implemented by allocating some new pages adjacent to the high end of the original space, physically copying the compressed region to the high end (typically writing into both new and original page space), then de-compressing "in place".  Or, "double map" /proc/self/exe to somewhere that does not overlap the de-compressed region, munmap() the original pages, allocate new pages which cover both the original and extended region, then de-compress into the extended original address space, then unmap the double.  This avoids a physical copy, which takes time.
For a ET_DYN executable (position-independent -fPIE) then in general UPX must use the double-mapping anyway, because the kernel easily can place other mappings (such as the PT_INTERP, [vdso], [vsyscall]) so that the original ET_DYN mapping cannot be extended without overlapping.
At the point of increased usage, please examine /proc/PID/maps to see if this *shared* double mapping of /proc/self/exe accounts for the increased page table usage.
