### ISSUE TITLE
upx binaries crashes on Linux systems without /proc (regression)

### ISSUE THREAD

**Issue by WGH-** [upx/upx#465]
## What's the problem (or question)?
upx binaries crash on Linux systems without `/proc`.

This is a regression. It didn't crash on the version included in Debian Stretch (3.91 with Debian patches), and started to crash on Debian Buster (3.95 with Debian patches). It still crashes as of ef9809c4885315a220a89aa9124c9bad555204db (`devel`) and d7ba31cab8ce8d95d2c10e88d2ec787ac52005ef (`master`).

I've bisected, and the first bad commit is 7f905724b1b993ec6a3555201bb7fb59a3fdc0d0.

## How can we reproduce the issue?
```bash
upx /bin/true -o /tmp/true.upx
unshare -r -m sh -c 'mount -t tmpfs none /proc && /tmp/true.upx'
```

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.96 (but see above)
* Host Operating System and version: Linux
* Host CPU architecture: amd64
* Target Operating System and version: Linux
* Target CPU architecture: amd64

**Comment by jreiser** [comment]
No, it is not a regression.  Requiring /proc is a deliberate choice encouraged by limited developer resources.  It is much easier to support and maintain all the flavors of executables when /proc is present.  The vast majority of x86_64 systems and users have and enjoy /proc; even Linus himself disdains a system without /proc. This Issue is the only one in three years of UPX requiring /proc, which illustrates the low prevalence of systems without it.
If no /proc is a requirement then you are welcome to use (and maintain!) the older version of UPX.

**Comment by WGH-** [comment]
Technically, it's still a regression, even if deliberate one :)

Sounds fair though.

**Comment by necros2k7** [comment]
if it wontfix close issue pls
