### ISSUE TITLE
Can't decompile compiled file

### ISSUE THREAD

**Issue by kmko1337** [upx/upx#467]
## What's the problem (or question)?
I can't decompile something compiled with upx

## What should have happened?
I can't decompile something compiled with upx

## Do you have an idea for a solution?
Nope

## How can we reproduce the issue?
I compiled something some times ago and i can't decompile it

## Please tell us details about your environment.
not needed.
https://transfer.sh/11QSCk/brute (this is the file)

**Comment by jreiser** [comment]
The `brute` file was packed by a hacked version of UPX that tried to disguise the packing.  Edit the file to find the strings:
```
^@$Info: This file is packed with the AAA executable packer http://upx.sf.net $
^@$Id: AAA 3.91 Copyright (C) 1996-2013 the AAA Team. All Rights Reserved. $
```
This is the modified UPX copyright notice (note that "upx.sf.net" still appears), where "AAA" has replaced "UPX" in three places.
In order to unpack, then the proper UPX markings (and packing) must be restored.
