### ISSUE TITLE
unable to compress after adding a runpath  header with patchelf --set-rpath

### ISSUE THREAD

**Issue by ytrezq** [upx/upx#47]
[Linux localhost 4.8.0-0.bpo.2-rt-amd64 #1 SMP PREEMPT RT Debian 4.8.11-1~bpo8+1 (2016-12-14) x86_64 GNU/Linux](http://mindonmind.github.io/notes/linux/change_rpath.html)

This happens on Linux x86_64 binaries and latest stable x86_64 upx for Linux version.

example step to reproduce as root :

    patchelf --set-rpath /bin/bash
    upx --best --ultra-brute /bin/bash
Then upx will fails and suggest the`--force-execve`but of course this is only valid for 32 bits targets.

**Comment by jreiser** [comment]
This patch works for me.  (Integration with 'devel' branch will follow.)
```
diff --git a/src/p_unix.cpp b/src/p_unix.cpp
index dca7000..f2153c7 100644
--- a/src/p_unix.cpp
+++ b/src/p_unix.cpp
@@ -242,8 +242,14 @@ PackUnix::patchLoaderChecksum()
     set_te32(&lp->l_checksum, upx_adler32(ptr, lsize));
 }

-void PackUnix::pack3(OutputFile *fo, Filter &/*ft*/)
+void PackUnix::pack3(OutputFile *fo, Filter &ft)
 {
+    if (0==linker) {
+        // If no filter, then linker is not constructed by side effect
+        // of packExtent calling compressWithFilters.
+        // This is typical after "/usr/bin/patchelf --set-rpath".
+        buildLoader(&ft);
+    }
     upx_byte *p = getLoader();
     lsize = getLoaderSize();
     updateLoader(fo);
```

**Comment by jreiser** [comment]
@ytrezq Please give the exact invocation of patchelf.  You did not specify the <path> in "--set-rpath <path>".  At least, the length and compressability of <path> is very important.

**Comment by jreiser** [comment]
@ytrezq: Please explain more what the comment "/usr/lib/chromium" means.  I cannot figure out what context is meant.  And, please provide the exact complete command that you used to invoke patchelf, and the exact complete error message from UPX.  When I ran "patchelf --set-rpath /tmp copy_of_bin_bash" it worked just fine for me. UPX did not complain while compressing, and the compressed version ran correctly.  So what did you do differently?

**Comment by ytrezq** [comment]
@jreiser
    invite@localhost /tmp % cp /bin/bash ./
    invite@localhost /tmp % patchelf --set-rpath /usr/lib/chromium bash
    invite@localhost /tmp % upx --best --lzma --ultra-brute --lzma bash
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2016
    UPX 3.92        Markus Oberhumer, Laszlo Molnar & John Reiser   Dec 11th 2016

            File size         Ratio      Format      Name
       --------------------   ------   -----------   -----------
    bash  3/5  [*****************************************************]   14.7%  - zsh: segmentation fault  upx --best --lzma --ultra-brute --lzma bash
    invite@localhost /tmp % 
    invite@localhost /tmp % upx --best --lzma --ultra-brute --lzma bash
                           Ultimate Packer for eXecutables
                              Copyright (C) 1996 - 2016
    UPX 3.92        Markus Oberhumer, Laszlo Molnar & John Reiser   Dec 11th 2016

            File size         Ratio      Format      Name
       --------------------   ------   -----------   -----------
    bash  3/5  [*****************************************************]   14.7%  - zsh: segmentation fault upx --best --lzma --ultra-brute --lzma bash
    invite@localhost /tmp %

If you want the --force-execve suggestion, you should perform such test on a shared object.
Did you really tried it with the 64 bits version of upx on a 64 bits executable ?

**Comment by jreiser** [comment]
Thank you.  Having the exact inputs and outputs enables understanding the issue(s) much easier and sooner.

I acknowledged the SIGSEGV and gave a patch in my first reply ~6 days ago.  I used that patch, then compressed and executed successfully after "patchelf --set-rpath /tmp /bin/date".

For /bin/bash, there are a number of complications.  "file /bin/bash; readelf --header /bin/bash" shows
```
/bin/bash: ELF 64-bit LSB shared object
Type:                              DYN (Shared object file)
```
so it was built -fPIE/-pie, which is different from a regular ET_EXEC executable.  After patchelf, then "readelf --segments --dynamic /bin/bash" shows
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000309000 0x0000000000309000 0x0000000000309000
                 0x0000000000000230 0x0000000000000230  R E    8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000f7db4 0x00000000000f7db4  R E    200000
  LOAD           0x00000000000f7e48 0x00000000002f7e48 0x00000000002f7e48
                 0x000000000000b720 0x0000000000011110  RW     200000
  GNU_RELRO      0x00000000000f7e48 0x00000000002f7e48 0x00000000002f7e48
                 0x00000000000031b8 0x00000000000031b8  R      1
  LOAD           0x0000000000309000 0x0000000000309000 0x0000000000309000
                 0x0000000000009008 0x0000000000009008  RW     1000
  DYNAMIC        0x0000000000309230 0x0000000000309230 0x0000000000309230
                 0x0000000000000220 0x0000000000000220  RW     8

Dynamic section at offset 0x309230 contains 30 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/bin/chromium]
 0x0000000000000005 (STRTAB)             0x309450
```
Notice that a new PT_LOAD has been created at 0x309000 to hold the expanded PT_DYNAMIC and DT_STRTAB.  In particular, the PT_PHDR are no longer adjacent to the Elf64_Ehdr.  So UPX complains
"CantPackException: non-contiguous Ehdr/Phdr; try '--force-execve'".  Handling the non-contiguous case could be done; the code is more complicated and the resulting data is larger.  I'll mark it a possible enhancement.  Notice also that patchelf could have used some of the ~2MiB of address space from 0xf7db4 to 0x2f7e48 instead of making a new PT_LOAD.

If you're really interested in compressing -pie executables that have been modified by patchelf, then you should ask the maintainers of /bin/ld to support three new options: "--pad-PHDR=number", "--pad-DYNAMIC=number", and "--pad-STRAB=number" which leave space at the end of the indicated regions.  [Compare  "-headerpad=number" on MacOS.]   Then patchelf won't have to turn handsprings, and UPX can be less complex.  [Note that already /bin/ld silently implements the equivalent of --pad-DYNAMIC=4*sizeof(ElfXX_Dyn)" so that prelink can work.]

**Comment by jreiser** [comment]
The SIGSEGV is avoided by devel branch commit cfd6ecfd71abddfa123b639ed514a04c70180a2c
