### ISSUE TITLE
Compressing the so file on linux will cause a Segmentation Fault

### ISSUE THREAD

**Issue by naciion** [upx/upx#506]
## What's the problem (or question)?
When the so file is compressed and called again on Linux, a segfault will be prompted.
Whether it is self-compiled so or the so file that comes with the system, it will not be able to be called normally after compression. And when using `upx -d` to decompress, the error `NotPackedException: not packed by UPX` will be reported.

E.g:
```
$ cp /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6.333
$ upx /lib/x86_64-linux-gnu/libc.so.6.333
$ /lib/x86_64-linux-gnu/libc.so.6.333
   :Segmentation fault
$ LD_PRELOAD=/lib/x86_64-linux-gnu/libc.so.6.333 a.out
   :Segmentation fault
```

uname:
Linux 4.9.125-linuxkit #1 2018 x86_64 GNU/Linux

upx:
3.91 - 3.96

**Comment by jreiser** [comment]
Please upload ("Attach files by ..."), give the URL, or email the actual file which fails.  Compress with gzip or zip to reduce transfer size.

**Comment by jreiser** [comment]
Thank you for uploading an actual file which fails.
```
$ readelf --segments upx-506_lib-orig.so   ## before compression

Elf file type is DYN (Shared object file)
Entry point 0x1280
There are 11 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000b50 0x0000000000000b50  R      0x1000
  LOAD           0x0000000000001000 0x0000000000001000 0x0000000000001000
                 0x0000000000013a99 0x0000000000013a99  R E    0x1000
  LOAD           0x0000000000015000 0x0000000000015000 0x0000000000015000
                 0x00000000000008cc 0x00000000000008cc  R      0x1000
  LOAD           0x0000000000015e00 0x0000000000016e00 0x0000000000016e00
                 0x0000000000000f20 0x0000000000000f28  RW     0x1000
```
This style of layout of the address space in the shared library, having 4 [PT_]LOAD segments created by /usr/bin/ld using a recent `libbfd` such as `libbfd-2.35`, requires that the upx runtime de-compression stub be significantly enhanced from the upx stub that handles shared libraries with only 2 PT_LOAD segments (one `R E` and one `RW`). Upgrading the upx stub has been in progress for a while, and the code is getting close, but is not yet complete.

**Comment by prantoran** [comment]
Hello! I guess this is an old issue but is there any update on this problem? 

I am trying to apply UPX on .so files that will auto-decompress during linking. The idea is to convert .so files into self extracting archives (SFX), similar to how upx-compressed executables (ELF based) auto-decompressed when executed.

I am open to debugging this issue since I am already actively trying to figure out a way.

Alternatively, I am looking  into how to generate SFX out of .so files by manually adding an entry-point using `__attribute__((constructor))__` in the cpp files. Is this possible and if so how to convert .so into SFX?

**Comment by jreiser** [comment]
UPX currently requires that an ELF executable be either a main program OR a shared library; UPX cannot deal with both at the same time.  Therefore the original Description which tries to use a compressed libc.so.6.333 as a main program cannot work.

When compressed by UPX, then a main program is started by a JMP instruction (jump) from an operating system call `execve` to the entry point address ElfXX_Ehdr.e_entry.   A compressed shared library is CALLed by the dynamic linker as the first DT_INIT or DT_INIT_ARRAY subroutine for that module.  In neither case is there any mechanism to trigger de-compression by a "mere" `open()` system call.  So if a static binder (such as /usr/bin/ld) would want to de-compress a compressed shared library in order to use it as input to a static binding step, then the static binder must CALL the DT_INIT or first DT_INIT_ARRAY subroutine, or invoke `upx -d` first (and then process the de-compressed output instead of the compressed version of the shared library.)

**Comment by prantoran** [comment]
Interesting observation:

I can compress the libc.so shown the Description but I can't compress an .so I made for practice with UPX version 3.95. But I can do so when I build UPX from source (and have version 4.2.4-devel.42+git-17cf7300).

This works:
```
cp /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6.333
upx /lib/x86_64-linux-gnu/libc.so.6.333
```

But this gets NotCompressibleException:
```cpp
// myclass.h
#ifndef __MYCLASS_H__
#define __MYCLASS_H__
#include<cstdio>

extern "C" void test_print(); 

void __attribute__((constructor))  __attribute__((visibility("default"))) calledFirst() ;

void __attribute__((destructor)) __attribute__((visibility("default"))) calledLast();

#endif
```
```cpp
// myclass.cpp
#include "myclass.h"

void test_print() 
{
  printf("test_print called finally\n");
}

void calledFirst() {
  printf("__attribute__((constructor)) calledFirst() entered\n");
} 

void calledLast() {
  printf("__attribute__((destructor)) calledLast() entered\n");
}
```
```bash
g++ -fPIC -shared myclass.cc -o libmyclass.so

upx libmyclass.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: libmyclass.so: NotCompressibleException: bad e_shstrndx
```

The outputs of the file command:
```bash
file libc.so.6.333 
libc.so.6.333: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0702430aef5fa3dda43986563e9ffcc47efbd75e, for GNU/Linux 3.2.0, stripped
```
```bash
file libmyclass.so
libmyclass.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7720041e8298b723a3223d2c4da54e51dd093534, not stripped
```

UPX version: 3.95
```bash
upx --version
upx 3.95
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```

**Comment by jreiser** [comment]
@prantoran  The `myclass` case is too small; I get
```
$ size libmyclass.so
   text	   data	    bss	    dec	    hex	filename
   1541	    608	      8	   2157	    86d	libmyclass.so

```
.  Add this to the myclass.cpp file:
```
int const x[10000] = {1,2,3};  // make .text 40000 bytes larger, and compressible
```
which gives
```
$ size libmyclass.so
   text	   data	    bss	    dec	    hex	filename
  41541	    608	      8	  42157	   a4ad	libmyclass.so
$ upx -f -o foo libmyclass.so

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
     52784 ->      8244   15.62%   linux/amd64   foo
$ 
```
