### ISSUE TITLE
Please support efi file as target

### ISSUE THREAD

**Issue by bastien-roucaries** [upx/upx#518]
Hi,

It will be nice in order to reduce network use to use upx on efi file. http.efi or even ipxe should be downloaded throught ineficient tftp protocol for boot over network.

It will be nice therefore to have self compressed efi file

Bastien

**Comment by jreiser** [comment]
What is the runtime environment for http.efi and ipxe?  Is it 16-bit DOS for i636?  for i386?  Please state a URL that gives documentation.

**Comment by bastien-roucaries** [comment]
It looks like PE with a small OS over here. Full spec is here:

https://uefi.org/sites/default/files/resources/UEFI_Spec_2_8_final.pdf

**Comment by bastien-roucaries** [comment]
(note that it will be nice to avoid the internal compression system of UEFI that is buggy/insecure)

**Comment by jreiser** [comment]
Help wanted: find the good places in the EFI documentation that correspond to {LoadLibraryA, GetProcAddress, VirtualProtect, ExitProcess}.  Those are the external routines used by the run-time decompressor.  See the code in src/stub/src/amd64-win64.pep.S and i386-win32.pe.S.

**Comment by kornelpal** [comment]
@jreiser, UEFI should be ABI compatible with Windows because [EDK2](https://github.com/tianocore/edk2) binaries can be produced by the same MSVC that is targeting Windows, but the API is completely different. UEFI binaries have no EAT/IAT; UEFI API is available through the system table passed to the image entry point. Advanced platform and user-defined functionality provided by DXE/UEFI drivers and applications are available using protocols that can be accessed via functions in the system table.

UEFI equivalents of the Windows API functions used by the stub:
- `LoadLibraryA`: [`LoadImage` and `StartImage`](https://edk2-docs.gitbook.io/edk-ii-uefi-driver-writer-s-guide/5_uefi_services/readme.2/524_loadimage_and_startimage); not needed as there is no IAT support.
- `GetProcAddress`: No equivalent as there is no IAT support.
- `VirtualProtect`: See [Memory Protection in UEFI](https://edk2-docs.gitbook.io/a-tour-beyond-bios-memory-protection-in-uefi-bios/memory-protection-in-uefi); requires page aligned sections and is optional. The `EFI_CPU_ARCH_PROTOCOL` required to change memory attributes is defined in [UEFI PI](https://uefi.org/sites/default/files/resources/PI_Spec_1_7_A_final_May1.pdf) and should be used by DXE drivers only, not by UEFI drivers. (The format is the same but DXE is part of the firmware and UEFI is the public API.) Might be easier to add writable attributes to the sections that is supported by UEFI.
- `ExitProcess`: [`Exit`](https://edk2-docs.gitbook.io/edk-ii-uefi-driver-writer-s-guide/5_uefi_services/readme.3/5317_exit); but simply returning from the image entry point is easier.

As a conclusion, I think that the stub could be implemented without using any UEFI API.

Difference between UEFI image types (should not affect the stub):
- `EFI_IMAGE_SUBSYSTEM_EFI_APPLICATION`: Image is unloaded when the entry point returns.
- `EFI_IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER`: Image is unloaded when the entry point returns an error, stays loaded otherwise.
- `EFI_IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER`: Same as a boot driver, but stays in memory and available after [`ExitBootServices`](https://edk2-docs.gitbook.io/edk-ii-uefi-driver-writer-s-guide/5_uefi_services/readme.3/5312_exitbootservices) when the OS is running.

Please see the [UEFI](https://uefi.org/sites/default/files/resources/UEFI_Spec_2_9_2021_03_18.pdf) specification for the definition of `EFI_IMAGE_ENTRY_POINT` that is used for all UEFI image types. Normative image format, ABI and API definitions are also available in the same UEFI specification.

Note that [EDK2](https://github.com/tianocore/edk2), the reference implementation that most UEFI implementations are based on, uses 32 byte image and section alignment by default that is not supported by UPX as that requires at least 512 byte alignment. Lowering the limit (at least for UEFI) could greatly expand the range of supported images.

**Comment by kornelpal** [comment]
@jreiser, I created pull request #546 with basic support for EFI images.
