### ISSUE TITLE
new release please?

### ISSUE THREAD

**Issue by alexmyczko** [upx/upx#526]
## What's the problem (or question)?
the last release is from january 2020, which is over 1,5 years ago.

## What should have happened?
please tag a new release more often, so people can use new features like `--lzma`, and also test it.

## Do you have an idea for a solution?
just tag a new release.

## How can we reproduce the issue?
1. current release `upx --lzma` doesn't suppor the option

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.96
* Host Operating System and version: debian and macOS
* Host CPU architecture: x86_64 and arm64
* Target Operating System and version: debian and macOS
* Target CPU architecture: x86_64 and arm64

**Comment by necros2k7** [comment]
close issue cause latest binaries are available in dev section?

**Comment by alexmyczko** [comment]
well the problem is not getting a single latest binary, the problem is getting it distributed: https://repology.org/project/upx/versions

all what is needed is tag a release, then it can be closed. 

happy new year!

**Comment by jreiser** [comment]
@alexmyczko   Looking at https://github.com/upx/upx/releases/tag/v3.96 there were packaged native executables of UPX for 12 different combinations of hardware+OS. A release also involves enhanced testing, not just `cd src; make run-testsuite`.  And right now there is a significant development effort to deal with current-style ELF files on Linux (particularly shared libraries) which have 4 PT_LOAD segments instead of only 2. While individuals or small teams using the most-prevalent environments can use the auto-builds produced by github Actions, downstream distributors desire the cachet of an officlally-versioned release.

**Comment by alexmyczko** [comment]
JFYI: 2 weeks left to get it into 22.04 of Ubuntu: https://discourse.ubuntu.com/t/jammy-jellyfish-release-schedule/23906

**Comment by alexmyczko** [comment]
Half a year for the next Debian freeze...

**Comment by jreiser** [comment]
The development work for handling .exe and .so with 4 PT_LOAD on Linux seems like it has entered the final straightaway before the finish.  So I am getting some hope of being ready for a release in a few months.  It would be really nice to make UPX work on current Android, too.

**Comment by markus-oberhumer** [comment]
New release coming RSN.

**Comment by polarathene** [comment]
Doesn't it make sense to close it once a release is actually made? :thinking:
