### ISSUE TITLE
Extremely bad compression ratio on .NET Core executables

### ISSUE THREAD

**Issue by alex-jitbit** [upx/upx#528]
## What's the problem (or question)?
I have a 18mb exe file that zips to 8 megabytes using Windows built-in zipper. UPX only slices about 100kb, producing almost the same 18mb file.

## What should have happened?
I expected a better ratio

## How can we reproduce the issue?
1. Take a simple "Hello world app" https://www.dropbox.com/s/9ettbawbxzvxb99/HelloWorldConsole.exe?dl=0
2. ` 10963411 ->  10703315   97.63%    win64/pe     HelloWorldConsole.exe`

**Comment by alexmyczko** [comment]
I'm not even able to pack it at all:

`upx: HelloWorldConsole.exe: CantPackException: CFGuard enabled PE files are not supported`

**Comment by bitraid** [comment]
That's because the actual size of the exe is only ~420K. The rest are overlay data which contain the actual .net files (this is not a .net exe - they are not supported by upx) that are extracted on `temp` and run from there. No compression is used for the storage, that's why you can zip it and to such size. The overlay data are not compressed by upx because they are not loaded in memory and are accessed by the program from disk (so they must remain in its original form). Depending on how the program is designed to access those data, it may or may not work when it is compressed by a runtime packer. In this case, it doesn't.

@alexmyczko Use the latest build with `--force` (but the program will fail to run anyway).

**Comment by alex-jitbit** [comment]
Understood.

**Comment by alex-jitbit** [comment]
And thank you.
