### ISSUE TITLE
Poor compression ratio + fail to launch for .net ReadyToRun executables...

### ISSUE THREAD

**Issue by tapika** [upx/upx#533]
Go to:

https://github.com/tapika/swupd/releases

Download choco.exe.

Try to compress using UPX executable - 

```
upx.exe -9 choco.exe
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96w       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  69135167 ->  69029695   99.85%    win64/pe     choco.exe
```

Try to launch after compression:
```
Failure processing application bundle; possible file corruption.
I/O failure reading contents of the bundle.
A fatal error was encountered. Could not extract contents of the bundle
```

Compression ratio could be better - using https://www.hanselman.com/blog/brainstorming-creating-a-small-single-selfcontained-executable-out-of-a-net-core-application

it's possible to compress 168 Mb to 60 Mb, where Rust sfx stub itself weights ~ 1 Mb.

**Comment by jreiser** [comment]
The file choco.exe (69135167 bytes, sha256sum acb21e165f308eb879c7267e6a5979e48b03040a88750c6bead46e5615e8656e) is not a normal PE file.  The .sections cover only a small portion of the file: less than 1/4 MB.  The rest is an un-interpreted "tail" that the run-time PE loader does not load into RAM.  Because the tail is not loaded into RAM, then the UPX run-time de-compressor cannot do anything about it; so the UPX compressor just copies the tail of the input file onto the tail of the output file.  You can verify by comparing the two files backwards, beginning at the high-offset end.  Apparently at run time the choco executing image expects to locate the choco.exe file, find the offset of the tail, and create a .dll that is derived from the tail of the file.  It is unreasonable to expect UPX to "commute" with this strategy.  The posted error messages after launching indicate that the choco implementation does not adjust for the compression that UPX does perform.

In order for UPX to compress some portion of an input PE file, then that portion must be in a .section that the PE run-time loader copies into the address space of the executing image.  UPX will then de-compress the section, and place the de-compressed contents into the executing address space as specified by the information in the .section header.

**Comment by tapika** [comment]
I'm now also wondering if UPX could do something similar to warp-packer - that's is zip entire folder with bunch of .exe and .dll's inside single executable, which could in a turn uncompress them and launch the application. I guess sounds bit complex ?

**Comment by jreiser** [comment]
_You_ could create a .exe with separate .sections whose individual content is a copy of one file, and a "supervisor" which re-creates files from the .sections that the UPX run-time has de-compressed, then jumps to the original entry point of the app.  There would be "loose ends": the .sections could be deleted from the executing image; the files would need to be deleted when execution stops, either at normal exit or at abnormal exit (crash, etc.)

**Comment by Mrgaton** [comment]
And convert the executable to machine code compress it save it as a resource and re-run it injecting it to self-process?
