### ISSUE TITLE
App built with Electron and later compressed with UPX doesn't run on Windows 10

### ISSUE THREAD

**Issue by LTVA1** [upx/upx#535]
## What's the problem (or question)?

App built with Electron and later compressed with UPX (it happens with every compression level -- from lightest to `--ultra-brute`) doesn't run on Windows 10.

## What should have happened?

Up until some point all was working well, I think the problem lies in some modification of index.html (Twine game) after which it started happening.

## How can we reproduce the issue?

1. Use [this](https://gitlab.com/fractalsLTVA/fractals/-/blob/main/src.zip) as electron project source
2. Build it with electron-forge
3. Run upx on [this](https://gitlab.com/fractalsLTVA/fractals/-/blob/main/test1.exe) (as you can see, source `.exe` is running)
4. Try to open resulting app

## Please tell us details about your environment.

* UPX version used (`upx --version`): UPX 3.96w
* Host Operating System and version: Windows 10 Pro 21H1 19043.1288
* Host CPU architecture: x86 64bit (i5-8600)
* Target Operating System and version: Windows 10
* Target CPU architecture: x86 64bit

**Comment by iplaycodex** [comment]
some problem

**Comment by jreiser** [comment]
When I run upx from the tip of `devel` branch on `test1.exe` from Step 3 of "How can we reproduce the issue?", and attempt to run the compressed output from upx on up-to-date Windows 10 Pro, then I see: `System error: test1-upx.exe;  The code execution cannot proceed because ffmpeg.dll was not found.  Reinstalling the program may fix this problem.`  I know nothing about `electron`, or `electron-forge`.
Please copy+paste the exact error that you see.

**Comment by LTVA1** [comment]
Here you are.

Translation: unable to launch this app on your pc.
To find a version suitable for your pc, please contact app's distributor.
![screen](https://cdn.discordapp.com/attachments/771372893123772426/917029948512952420/unknown.png)

**Comment by bitraid** [comment]
This is an issue of Control-Flow-Guard enabled PE files, which are not supported. The release version of UPX does not detect them - this is addressed in `devel` where it denies compression, but you can use `--force` to compress by disabling CFG.

**Comment by iplaycodex** [comment]
您的邮件已经收到,谢谢!

**Comment by LTVA1** [comment]
> This is an issue of Control-Flow-Guard enabled PE files, which are not supported. The release version of UPX does not detect them - this is addressed in `devel` where it denies compression, but you can use `--force` to compress by disabling CFG.

Well it does not work, I get the same error

**Comment by bitraid** [comment]
> Well it does not work, I get the same error

It works here. What UPX version are you using?

**Comment by LTVA1** [comment]
3.96w. Maybe it would work with devel version, but I am afraid I'd need to re-configure my compiler to use it

**Comment by bitraid** [comment]
I though I made it clear that you need the devel version.
Read [here](https://github.com/upx/upx-automatic-builds) on how to download the devel builds.

**Comment by LTVA1** [comment]
oh yeah sorry
for now it works with `--force`, but resulting app launches, but it is just white blank window. I think though it's app's problem, not UPX one now

**Comment by LTVA1** [comment]
And after 1 minute of such state it crashes. Interesting.

**Comment by bitraid** [comment]
I cannot properly test the app (both packed and unpacked complain about missing files) because it is not built as a portable target (see [here](https://www.electron.build/configuration/win.html)). I don't use electron - I must download it and build the app, but I don't know when I'll have the time to do so.

**Comment by LTVA1** [comment]
ok then I'll just search for different app to compress this stupidly large exe

**Comment by iplaycodex** [comment]
您的邮件已经收到,谢谢!

**Comment by markus-oberhumer** [comment]
What is the status of this issue?

**Comment by jreiser** [comment]
The status of this issue is : "Stuck" because:

1. The presentation is not "crisp".  It is cumbersome to setup and run the application build environment: having  just VC++ is not enough.  The inputs and outputs of generating the app from the build environment are not identified explicitly.
2. There are not two corresponding executables (one not compressed, one compressed) with explicit literal URLs, plus a script which runs the app twice, and highlights the difference in behavior.
3. Only members of the UPX user community care about the outcome.  No member of UPX Team is interested.

**Comment by markus-oberhumer** [comment]
Well, if we don't get any links to actual executables we obviously cannot test that. Closing.

**Comment by iplaycodex** [comment]
您的邮件已经收到,谢谢!

**Comment by LTVA1** [comment]
> Well, if we don't get any links to actual executables we obviously cannot test that. Closing.

I provided a link to executable in very first message, maybe the link doesn't work?

**Comment by markus-oberhumer** [comment]
@LTVA1 Please test with the current UPX 4.0.0 version. If it still fails please provide a link to the actual exe with clear instructions how to reproduce.

**Comment by iefsu** [comment]
+1

**Comment by iplaycodex** [comment]
您的邮件已经收到,谢谢!

**Comment by jreiser** [comment]
@iplaycodex:
> 您的邮件已经收到,谢谢!

It would be more polite to provide your own translation into English.  Else you force the developers to use translate.google.com, which says "Your email has been received, thank you!", and which is not appropriate here.
