### ISSUE TITLE
upx packed exe can not run on win10 with error 0xC0000130

### ISSUE THREAD

**Issue by CitrusIce** [upx/upx#556]
## What's the problem (or question)?

the upx packed exe can not run on windows 10 with an error 0xC0000130 return by NtCreateUserProess, which is STATUS_INVALID_IMAGE_PROTECT

## What should have happened?

the packed file should run normally

## Do you have an idea for a solution?

the error is occured in 
nt!CreateUserProcess -> nt!PspAllocateProcess -> nt!MmCreatePeb
the nt!MmCreatePeb call the function RtlImageDirectoryEntryToData and the address returned by the function is not aligned in 8, which leading a ExRaiseDatatypeMisalignment call.
the root cause of the error is because the load config table is not aligned in 8. In normal case, the load config table can be aligned correctly, but in my case, with a tls table, it seems that the tls table disturbed the load config table alignment.

## How can we reproduce the issue?

1. download this file https://anonfiles.com/p898a4Bdx6/test_exe
2. using upx pack it and run

## Please tell us details about your environment.

* UPX version used (`upx --version`):  upx 3.96
* Host Operating System and version: win10 20h2 19042.928
* Host CPU architecture: x64
* Target Operating System and version:win10 20h2 19042.928
* Target CPU architecture: x64

**Comment by CitrusIce** [comment]
the file link this the file after packed
the original file is this [https://anonfiles.com/haB6adBaxb/temp_exe](url)

**Comment by jreiser** [comment]
@CitrusIce  the URL in your comment just above (`https://anonfiles.com/haB6adBaxb/temp_exe`) points to `https://github.com/upx/upx/issues/url` which is a web page, not a PE executable file.  That page also does not have any links to a PE file.

Looking at the compressed file `test_exe` gives the hint that the original file before compression probably is less than 64KB, which is small enough to send directly to GitHub instead of relying on anonfiles.com.  See the line "Attach files by ..." at the bottom of the pane when entering a Comment here on GitHub.  Compress the upload using zip, gzip, or .tgz, which saves space and any restrictions on file type.

**Comment by CitrusIce** [comment]
[temp.zip](https://github.com/upx/upx/files/7875202/temp.zip)
here is the original file
didn't know that github can attach file directly XD

**Comment by jreiser** [comment]
Compressing `temp.exe` using upx built from the tip of `devel` (downloads at https://github.com/upx/upx/actions/runs/1701832011) gives a compressed output whose execution complains about ucrtbased.dll not found, which is not the same  as before.  So please try upx from the tip of `devel`.

**Comment by CitrusIce** [comment]
it works
