### ISSUE TITLE
Compressed Windows Application shows no output

### ISSUE THREAD

**Issue by joerg-wille** [upx/upx#559]
## What's the problem (or question)?
I have created a windows CLI binary with GraalVM Native Image. Without upx it runs on Windows but even if I compress with options "--compress-exports=0 --compress-icons=0 --compress-resources=0 --strip-relocs=0 --overlay=skip" the application just shows no output at all. The application seems to run, but there is no out and then the application quits without any warning or error message.
I am compiling the same application also for Linux and macOS. Both of these versions run after being compresses with UPX.

## What should have happened?
The problem is not a general problem with  GraalVM Native Image. I have created other Java CLI applications with GraalVM Native Image which perfectly run after ebing compressed with upx.
I expect the compressed Windows binary to show the same output as the original applications or the copmressed versions for Linux or macOS.

## Do you have an idea for a solution?
No!

## How can we reproduce the issue?
1. [Download Windows binary](https://github.com/joerg-wille/NativeImageUsingJPMS/releases/download/main/NativeImageUsingJPMS-windows.exe).
2. In Windows CMD run the original version: NativeImageUsingJPMS-windows.exe
3. Use upx to compress: upx.exe NativeImageUsingJPMS-windows.exe -v --compress-exports=0 --compress-icons=0 --compress-resources=0 --strip-relocs=0 --overlay=skip -o NativeImageUsingJPMS-compressed.exe
4.  In Windows CMD run the original version: NativeImageUsingJPMS-compressed.exe

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
* Host Operating System and version: Windows 11
* Host CPU architecture: Intel AMD64
* Target Operating System and version: Windows 11
* Target CPU architecture:  Intel AMD64

**Comment by kornelpal** [comment]
@joerg-wille, [WindowsImageHeapProvider.createImageHeapFileMapping()](https://github.com/oracle/graal/blob/19a4e5d712ae7c4557fcd028b68f42e968b2524e/substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsImageHeapProvider.java#L138) of GraalVM is mapping the executable file into memory without executing the decompressor stub that is incompatible with executable compression in general.

Some ideas to fix it in GraalVM code: 
- Change [WindowsImageHeapProvider.commitAndCopyMemory()](https://github.com/oracle/graal/blob/19a4e5d712ae7c4557fcd028b68f42e968b2524e/substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsImageHeapProvider.java#L81) to always fall back to `super.commitAndCopyMemory`
- Use [CopyingImageHeapProvider](https://github.com/oracle/graal/blob/19a4e5d712ae7c4557fcd028b68f42e968b2524e/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/os/CopyingImageHeapProvider.java#L35) instead of `WindowsImageHeapProvider` in [WindowsImageHeapProviderFeature.duringSetup()](https://github.com/oracle/graal/blob/19a4e5d712ae7c4557fcd028b68f42e968b2524e/substratevm/src/com.oracle.svm.core.windows/src/com/oracle/svm/core/windows/WindowsImageHeapProvider.java#L67)
- Or just remove the `WindowsImageHeapProviderFeature` class that should result in `CopyingImageHeapProvider` being used

**Comment by sadaaithal** [comment]
perfect. removing the WindowsImageHeapProviderFeature class helped with this exact issue I was hitting. 
in case it helps someone else, this issue is seen with native images of graalvm v22x onwards.
it doesn't show up with v21x.

**Comment by yunshouhu** [comment]
您好，邮件我已经收到，我会尽快给您回复。祝你学习进步， 工作顺利！

**Comment by joerg-wille** [comment]
> this issue is seen with native images of graalvm v22x onwards.
> it doesn't show up with v21x.

I can confirm that. The incompatibility arrived from [this commit](https://github.com/oracle/graal/commit/dde224520a79cae2aa6169d7e551e924fbadcbd8) which connects to [this issue](https://github.com/oracle/graal/pull/4051).

**Comment by david-sitsky** [comment]
@sadaaithal - is there a command-line flag to native-image which "removes WindowsImageHeapProviderFeature" or any other workarounds to this issue without resorting to a custom GraalVM distribution?

**Comment by kornelpal** [comment]
@david-sitsky, the com/oracle/svm/core/windows/WindowsImageHeapProviderFeature.class file can simply be deleted from lib/svm/builder/svm.jar that requires no recompilation of GraalVM itself.

Note that jar files are zip files with a different extension, so you should be able to use any zip editing tool to delete the file.

You may want to back up the original svm.jar file before the change.

**Comment by david-sitsky** [comment]
Thanks - that works.

**Comment by zingermax** [comment]
> Thanks - that works.

how is the image performance after this hack? getting a high startup memory (x3 vs original) and gc is really bad

**Comment by kornelpal** [comment]
@zingermax, normally executable files are mapped into memory and read-only sections can be shared between processes and unmodified parts can be reloaded from the executable file without having to be stored in the page file. Because UPX is expanding the executables in memory neither of these optimizations are possible that can explain the x3 memory need.

Neither using UPX nor removing WindowsImageHeapProviderFeature should however affect garbage collection. Is it possible that you run out of RAM and paging is causing the slowness?

WindowsImageHeapProviderFeature was added to GraalVM in 22.0, so you might want to try 21.3 that does not have this feature and should work with UPX without any changes, and see if that version has different performance metrics.

**Comment by zingermax** [comment]
@kornelpal, it seems that its just overall higher memory footprints - comparing it with the original executable

**Comment by jreiser** [comment]
@zingermax Please give the exact measurements and measurement technique that says "overall higher memory footprints".  Please pay particular attention to the difference between RAM being used versus address space being reserved or mapped.

**Comment by zingermax** [comment]
ms perfmon with a working set counter
original:
![ecd-test-mode-original](https://user-images.githubusercontent.com/103928969/180973716-3a123b4b-75b9-4788-b5aa-c38f574fac10.png)

compressed:
![ecd-test-mode-upx](https://user-images.githubusercontent.com/103928969/180973774-0b2ce8bd-f237-4f8c-96d8-c1921012bd74.png)

**Comment by jreiser** [comment]
@zingermax Thank you for the graphs, but more information is required in order to enable a good analysis. 

1. What is the title of the y axis, what are the units, what is the scale? The labels 0 to 100 look suspicious.
2. What was measured?  Windows perfmon can measure several different things.
3. What was the environment?  How much total RAM in the machine, what other processes were running and how much RAM were they using, which version of Windows?

Assuming that the intent was to measure "working set", then there are some complications.  x86_64 has no direct hardware per-process counter of pages "recently" used.  Thus the operating system and/or the perfmon tool must adopt a strategy to determine "working set".  The simplest strategy is to count the number of pages in the process address space whose hardware Present bit is 1;  that is, how many different pages would *not* cause a page fault if referenced?  However there are problems.  The first problem is that this is a lagging measurement that can count a page as Present even if the last access was a long time ago, if the operating system has been lazy about periodically turning off the Present bits in order to maintain a timely indication of the working set.  The second problem is competition for RAM.  If other processes are competing heavily for RAM, then the operating system probably tends to reduce the working set of any process by paging out pages: either by writing a modified page to paging space on secondary storage (HDD or SDD), or by "stealing" an unmodified page that is Present in both RAM and secondary storage.  Even worse for accurate measurement of working set, if there is no competition for RAM then the operating system might decide never to turn off Present bits, so the working set would just grow and never decrease.

Then there is UPX compression. At the start of execution, then  the UPX de-compression stub must read every compressed page, and write every de-compressed page.  This "artificially" tends to make  the working set of the process appear quite large.  I see that the graphs cover about 90 seconds each, with a steady state after about 60 seconds.  If there was no competition for RAM after de-compression, then the operating system will tend not to discard compressed pages, and tend not to page-out unused de-compressed pages.  So if the measurements were made on a machine that is "otherwise idle", then the simple technique for measuring "working set" tends to give a much-inflated answer when running a program that was compressed.

**Comment by markus-oberhumer** [comment]
Reopening, might be related to #670

**Comment by markus-oberhumer** [comment]
Please note this comment https://github.com/upx/upx/issues/559#issuecomment-1032047038 from @kornelpal

**Comment by markus-oberhumer** [comment]
This might be a GraalVM bug introduced in Graal version 22, see https://github.com/oracle/graal/issues/4340

**Comment by markus-oberhumer** [comment]
The UPX team believes this is a GraalVM bug introduced in Graal version 22, so closing.

See https://github.com/oracle/graal/issues/4340

EDIT 1: also see related UPX bug report #670

EDIT 2: also see https://github.com/oracle/graal/issues/7605

**Comment by markus-oberhumer** [comment]
Update: https://github.com/oracle/graal/issues/4340 has been closed, so the problem might be fixed in the latest GraalVM version.

Please retest your binaries and confirm at https://github.com/oracle/graal/issues/4340 (or open a new GraalVM issue).
