### ISSUE TITLE
segmentation fault for when runing compressed elf arm64-v8a

### ISSUE THREAD

**Issue by matrixhax** [upx/upx#565]
## What's the problem (or question)?

excutuble file give an error segmentation fault after i compress it with upx
it is elf arm64-v8a file 
i tried all compresing methods and still give this error after compressing

the same version of this file that compiled with : armeabi-v7a is working fine after upx compression
and there is no faults

i tried writing only main with cout in it  and still the same issue
i hope you give me a sulotion or fix it 

here is a direct link to my excutuble file 
https://discord.com/channels/848624738460762132/848624738460762135/947377447156998164
you can try to comress it with upx

## What should have happened?

it should work normally 
## Do you have an idea for a solution?

no idea

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* 3.29
* Host Operating System and version:
* android 11
* Host CPU architecture:
* support arm64-v8a and armeabi-v7a
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment]
@matrixhax That "dirrect link" designates a page of HTML that invites me to create a Discord channel.  Please post a URL that I can `curl` directly to get a copy of your executable file.  Or, if it is "small" (github can handle at least 1MB) then compress the executable with zip/gzip/.tgz and upload it to github: see the footer "Attach files by ..." at the bottom of the pane when entering any Comment here on github.  github wants the filename to end in .zip, .gz, or .tgz, etc, but the actual contents can be any file format.

**Comment by matrixhax** [comment]
sorry for this mistake 
here is new link : 
https://cdn.discordapp.com/attachments/848624738460762135/947377446624329778/MX

**Comment by matrixhax** [comment]
> @matrixhax That "dirrect link" designates a page of HTML that invites me to create a Discord channel. Please post a URL that I can `curl` directly to get a copy of your executable file. Or, if it is "small" (github can handle at least 1MB) then compress the executable with zip/gzip/.tgz and upload it to github: see the footer "Attach files by ..." at the bottom of the pane when entering any Comment here on github. github wants the filename to end in .zip, .gz, or .tgz, etc, but the actual contents can be any file format.

friend will you look at my issue please

**Comment by jreiser** [comment]
Thank you for the direct pointer to an executable ELF file, which is built for Android 11 operating system.  Running on Android is cumbersome for me.  For instance, Android Studio fails to install on my Fedora 34 x86_64: I suspect that some Windows developer of Android Studio doesn't understand Linux symlinks.  So I try to run on RaspberryPi arm64 under Linux, which requires a forest of symlinks to arrange for /system/bin/linker64 and the shared libraries libz.so, liblog.so, libc.so, libm.so, libdl.so, for which I substitute the Linux versions.

**Comment by jreiser** [comment]
UPX supports shared libraries, which for *nix-like systems means ELF ET_DYN format.  There are some differences in contrast to main programs.  For a main program, the UPX de-compression is the first code that runs, immediately after a successful `execve` syscall.  For a shared library, the UPX de-compression is the first "initialization" code (DT_INIT, etc.) for the library, but this is _after_ the relocation that is performed by the run-time loader `dlopen`. So for a shared library, then nothing that `dlopen` reads or writes can be compressed; and this can be a substantial portion of the library.  Compression of a shared library is somewhat heuristic, because determining what `dlopen` does not touch is not necessarily simple.  Nevertheless, many developers do use UPX to compress shared libraries.

Then there is Android.  Android does not follow the documented and historical conventions for executable files, particularly the separation of ElfXX_Phdr information [relating to run-time execution] versus ElfXX_Shdr information [relating to build-time linking and "out-of-band" debugging, and perhaps self-introspection]; see </usr/include/elf.h> and the ABI documentation for Elf files.) So you must use the flag `--android-shlib` when compressing a shared library for Android.  And recent versions of Android have introduced more undocumented incompatibilities which cause further problems.

In order for UPX to be a useful tool, then system administrators must trust that UPX is not being used to hide malware, else _every_ UPX-compressed file would be banned without exception. Therefore one of the goals of UPX is that de-compression (`upx -d`) must be enough to reveal the original file, so that the original file can be analyzed for malware.  Therefore UPX never will support encryption.  Anyone can run `upx -d` and look at the original not-compressed code.

**Comment by jreiser** [comment]
@matrixhax _> if you dont have rooted android you can run it on any rooted x64 android emulator on PC_

Please give a specific literal example of how to debug UPX run-time de-compression in the target environment.  I downloaded and installed Android Studio for Linux x86_64.  By fumbling through Device Manager commands I managed to install `androidstudio/Android/Sdk/emulator/emulator` and devices:
```
$ $EMULATOR -list-avds
Pixel_C_API_30
arm8_Pixel_4a_API_30
x86_Pixel_4a_API_30_2
$ 

$ $EMULATOR -avd arm8_Pixel_4a_API_30
INFO    | Android emulator version 31.2.8.0 (build_id 8143646) (CL:N/A)
PANIC: Avd's CPU Architecture 'arm64' is not supported by the QEMU2 emulator on x86_64 host.
```
So it seems to me that I cannot do anything useful because the emulator cannot run arm64 code for Android on x86_64 Linux host.

How can I use qemu-system-aarch64 [or some specific program] on Linux x86_64 to run your MX app under a single-stepping debugger in an Android arm64 environment?  I want something like
```
$ qemu-aarch64 -g 1234 -strace MX &  # Start the emulator, and use gdbserver protocol on TCP port 1234
$ gdb-multiarch  # a single-stepping debugger running on x86_64, but uses gdbserver protocol to debug an arm64 target
(gdb) file MX
(gdb) target remote :1234
(gdb)  Stopped at <entry_point_address>
(gdb) stepi
```
except that the compressed MX should see itself running on Android instead of on Linux.

**Comment by jreiser** [comment]
@matrixhax I dug up an old phone running Android 7.1.1, and have set up Developer mode over USB, and will see if `adb` can provide enough of an environment to debug UPX startup.
