### ISSUE TITLE
UPX failing to compress anything

### ISSUE THREAD

**Issue by VerstreuteSeele** [upx/upx#573]
## What's the problem (or question)?
When using UPX I always get the error "no such file or directory". Not for upx itself, but for every file it tries to compress.
Screenshot uploaded on my host: [Image](https://cloud.cynthiaai.de/s/MKnXsi2yz7ySTzB/preview)

## What should have happened?
It should work just fine

## Do you have an idea for a solution?
I wish I had one

## How can we reproduce the issue?
1. If I would know, I could fix the issue, haha

## Please tell us details about your environment.
* UPX version used (`upx --version`): 3.96
* Host Operating System and version: Win 10 Home Build 19044.1586
* Host CPU architecture: x86 Intel i5
* Target Operating System and version: not applicable
* Target CPU architecture: not applicable

**Comment by jreiser** [comment]
@VerstreuteSeele Please check that system commands can find the same pathnames, such as:
```
C:\Users\fisch>   dir C:\Users\fisch\AppData\Local\pyinstaller\bincache01_py39_64bit\numpy\random\_mt19937.cp39-win_amd64.pyd
C:\Users\fisch>  copy C:\Users\fisch\AppData\Local\pyinstaller\bincache01_py39_64bit\numpy\random\_mt19937.cp39-win_amd64.pyd %TEMPDIR%
```
Also, for text please use Copy+Paste instead of screenshots.  Even in CMD: highlight text using the left mouse button (button_down-drag-button_up), then &lt;Ctrl&gt;C to copy what is highlighted.  Then click left button at the desired desination, and &lt;Ctrl&gt;V to Paste.  For a Comment in GitHub, put the pasted text between two lines that each contain only three backticks (on many PC keyboards, the key to the left of the digit 1).  Use the Preview tab to check the formatting.

**Comment by VerstreuteSeele** [comment]
I apologize. Wasnt really awake when writing this report and just wanted to get it out, sorry.

Uhm, yeah issue seems that the path just doesn't exist. local\pyinstaller ain't a thing. Any idea on how to fix that issue?
