### ISSUE TITLE
I wrote a much smaller LZMA decoder for x86/x86_64.

### ISSUE THREAD

**Issue by ilyakurdyukov** [upx/upx#581]
Not a bug, but a suggestion.

I recently played Code Golf with writing the smallest LZMA decoder and ended up with a decoder of about 500 bytes (for compressed executables, standalone Linux version is 800+ bytes). Yours is ~2500 bytes, judging by the offsets in [amd64/lzma_d_cn.S](https://github.com/upx/upx/blob/devel/src/stub/src/arch/amd64/lzma_d_cn.S)

You can use [my work](https://github.com/ilyakurdyukov/micro-lzmadec), but my version should be slower on decompression (which you probably won't like at all).

**Comment by jreiser** [comment]
Thank you for your note.  Yes, the existing lzma decoder in ~2500 bytes is just the result of "gcc -S" and perhaps with "-Os".

I have a hand-written decoder for UPX lzma on amd64 that is close to 1000 bytes, and nearly the same speed as existing.  When the time comes for integration, then we can compare.  Meanwhile there is a development backlog for supporting executables with 4 PT_LOAD generated by recent binutils on ELF, MacOS and its security shananigans, and Android.  But I have more time for UPX than before, so progress is being made.  And from time to time there is agitation for Zstd, although so far it looks like nobody has paid attention to de-compression in standalone embedded environments (no malloc, etc.), or to specialization for each particular executable.

**Comment by jreiser** [comment]
UPX cannot use the software https://github.com/ilyakurdyukov/micro-lzmadec because of its poor quality: it is unmaintainable.  The documentation is absent, there are almost no comments relating to strategy, no explanation of how the space savings were achieved, constant values are bare integers with no symbolic names and no expressed inter-relationships, and there is no acknowledgement of the algorithm source (perhaps Igor Pavlov's original works?)
