### ISSUE TITLE
Rebuilding LZMA decompression stub

### ISSUE THREAD

**Issue by lunzima** [upx/upx#582]
## What's the problem (or question)?

Not a bug, but a question about lzma_d_cf.S and lzma_d_cs.S

## What should have happened?

lzma_d_cf.S should be the fast variant of the LZMA decompression stub, and lzma_d_cs.S should be the size variant of the LZMA decompression stub. But I see for amd64 and i386 arch the two stub are same

## Do you have an idea for a solution?

Could you provide an instruction of rebuilding them from lzma_d_c.c?

## How can we reproduce the issue?

Not revelant.

## Please tell us details about your environment.

UPX 3.96 release.

**Comment by jreiser** [comment]
Here are some hints.  [This is not a shell script; thinking is required.]

See `upx/README.SRC `paragraph `Tools` regarding LZMA SDK.
Create a directory `upx/src/lzma-sdk` and install your favorite SDK for LZMA.
The files in directory `lzma-sdk` are subdirectory `C`, `CPL.html`, and several `*.txt`: `7zC`, `7zFormat`, `history`, `LGPL`,` lzma`, `Methods`.
Consult `upx/src/stub/src/c` for `lzma_d_c.c `(which is under `git` control) and `Makevars.lzma`, which recommends SDK 4.4.3, although 4.4.9 may also work.  The log for git submodule` upx/.git/modules/src/lzma-sdk` begins
```
commit c6c2fc49e2ac6f3fc82762c6d3703969274d48de (HEAD -> master, origin/master, origin/HEAD)
Author: Markus F.X.J. Oberhumer <snipped>
Date:   Sat May 15 06:00:50 2021 +0200
```

Begin at `https://github.com/upx/upx-stubtools` to find the toolchains.
Install the upx tools into your `$PATH`, such as in `$USER/local/bin/bin-upx-20210104`, in order to access the compiler such as `amd64-linux-gcc-3.4.4`.
If you can re-compile `upx/src/compress_lzma.cpp` using `make` then you are on the right track.

Consult `upx/src/Makefile` to see `include $(top_srcdir)/src/stub/src/c/Makevars.lzma`.
Consult `upx/src/stub/src/arch/.../Makefile.extra` to see the same `include`.
Consult `upx/src/stub/src/arch/.../Makefile.extra` to see `STUBS += lzma_d_cf.S lzma_d_cs.S` which is the dependency to re-compile.

**Comment by lunzima** [comment]
Okay I rebuilt these stubs with ` make -f Makefile.extra ` and get expected results.
