### ISSUE TITLE
Please release new official release - 3.96 segmentation faults 

### ISSUE THREAD

**Issue by TBOpen** [upx/upx#588]
## What's the problem (or question)?

I had to move to 3.96 from I think 3.95 or maybe 3.94 due to updating gcc, but the Linux i686 binaries running at debian buster level segmentation faults.  This happens if I compress in Windows or Linux.

## What should have happened?

Just ran.

## Do you have an idea for a solution?
I build the latest on linux and tried that version, it works!!  but now I also need to get the Windows version updated.  It be so much easier if you had an official release available.  Maybe once a year would be good, especially in this case where the old 3.96 doesn't seem to work with the new binaries.

## How can we reproduce the issue?
Internet search with lots of people same issues or issues where they can't compress due to some HASH issue.

## Please tell us details about your environment.
The linux binaries are i686 build with debian buster version of gcc.  But I also had compressed ldconfig from buster and bullseye and both crashed with segmentation fault.  The latest version from github works.

**Comment by jreiser** [comment]
The description for this Issue contains no actionable facts.  You *MUST* upload (see "Attach files by ..." in the footer of any Comment entry pane on GitHub) or give the URL of actual input files (before compression by UPX) which fail to behave, and say how each one fails in each specific environment (which OS versions, etc.)  If I cannot reproduce the behavior that you see then I cannot "fix" it or explain workarounds, etc.  Compress uploads using gzip, zip, or .tgz in order to save space and pacify GitHub's filtering.

**Comment by markus-oberhumer** [comment]
New release is planned RSN.
