### ISSUE TITLE
IOException: not a regular file

### ISSUE THREAD

**Issue by caitou2019** [upx/upx#597]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/47804016/188254184-5cb3e368-f7d7-4e61-881f-41205fccf390.png">

error is "upx: ./gui: IOException: not a regular file -- skipped"

Package command is ".\\upx\\upx.exe --lzma ./release32/gopher.exe ./gui"

Finally, the compression is successful and the program can run normally, but there is this exception What should I do, please?

**Comment by jreiser** [comment]
Follow the template that the "New issue" button presents.  Give tthe data about which version of upx, the hardware architecture and which version of the OS (the host used for running UPX, the target used for running the compressed executable).  Show information about the file: its name, size, full path, "type", etc.  (Do not use screenshots.  Instead, use copy+paste of text.)  Show what happens when compressing and running some other file, such as a copy of Notepad.exe.

Upload the file (see "Attach files by ..." in the footer of any Comment entry dialog on GitHub()  or give a URL so that someone else can reproduce the behavior that you see.  (Compress any upload using gzip, zip, or .tgz.)

**Comment by markus-oberhumer** [comment]
Remove the "./gui" argument which is obviously a directory.
