### ISSUE TITLE
studio 2015 std::regex does not work after dll compression

### ISSUE THREAD

**Issue by assorted** [upx/upx#6]
std::regex and boost::regex does not work in packed dll, but in exe it works fine. I assume that the problem with TLS. This is a code example:

code: http://pastebin.com/qT5KV9Wu
bin: https://www.dropbox.com/s/bdegpkqkjh2b2a8/dll.rar

**Comment by markus-oberhumer** [comment]
Which upx version?

**Comment by assorted** [comment]
upx30590w and upx391w

**Comment by assorted** [comment]
There is a problem with tlsindex.

**Comment by mudlord** [comment]
I thought UPX already has a stub TLS index variable  :astonished:

**Comment by ml1050** [comment]
Can you also add an .exe which I can test this dll with?

**Comment by markus-oberhumer** [comment]
We now have automated builds of the devel branch - please download the current win32 version from

https://github.com/upx/upx-automatic-builds/tree/devel-20170115-120150-ac4b51-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by assorted** [comment]
You can use ollydbg to open, run and test this dll.

**Comment by Mattiwatti** [comment]
I couldn't reproduce this, even after eliminating each of the following variables:
- Your precompiled DLL vs one compiled by me from the same source;
- `std::regex` vs `boost::regex` (other than that special feeling of seething rage deep inside you that only Boost can induce);
- Some difference in UPX versions used - I tried both UPX 3.94 release and the current `devel` branch, on both x86 and x64;
- Some OS-dependent loader difference (if you have Windows 8.1 or 10 this would be more likely to affect you). I tried the DLLs on XP, 7, and 10 all with success.

Compiler used was VS2017. I tested the DLLs in x64dbg because I'm not a masochist, but I did try OllyDbg briefly to make sure it wasn't just Olly bug nr. 238593294, which would be much more likely :stuck_out_tongue:

You're right though that TLS is the most likely cause. Since I can't reproduce the bug, here's two things you can try to see if they work:
- Nuke the TLS directory using CFF Explorer (set both its RVA and size to 0). This will break the DLL's regex functionality, but apart from that it should still work without crashing (at least, it does for me). This obviously isn't an option for real code but it can quickly establish TLS as the culprit if it works.
- If you're an MSVC user like me, chances are good that you're using `/Zc:threadSafeInit` without being aware of this. One of `/std:c++14`, `/std:c++17` or `/std:c++latest` implies this (I forget which). Standards compliance is a nice goal, but in practice this switch is terrible for Windows users because it is implemented using TLS, and TLS in Windows is terrible in general. For your sample, I had a TLS directory placed in my DLL by the linker until I added `/Zc:threadSafeInit-` to the options, which made it disappear. (Note: this is only true for `std::regex`, if using Boost the switch predictably has no effect whatsoever and you get a TLS directory regardless.)

**Comment by assorted** [comment]
Thank you, I will get the details of this week.
