### ISSUE TITLE
Compressed shell script SEGFAULTs when too long

### ISSUE THREAD

**Issue by Harvie** [upx/upx#604]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

There is shell compressor, but on long shell script it creates binary that segfaults

## What should have happened?

Compressed shell script should work correctly.

## Do you have an idea for a solution?

Maybe some buffer is too small? Should allocate dynamicaly depending on script size.

## How can we reproduce the issue?

1. Download [comp.sh.txt](https://github.com/upx/upx/files/9707891/comp.sh.txt)
2. Rename to comp.sh
3. chmod +x comp.sh
4. upx comp.sh
5. ./comp.sh

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.96-git-d7ba31cab8ce+
* Host Operating System and version: ArchLinux 2022-10
* Host CPU architecture: amd64
* Target Operating System and version: i386-linux.elf.shell
* Target CPU architecture: linux.sh/i386

**Comment by jreiser** [comment]
After running `upx -f -o foo comp.sh`, then looking at the system calls made by running the compressed script:
```
$ strace -f ./foo
execve("./foo", ["./foo"], 0x7ffe05f8bbf8 /* 62 vars */) = 0
[ Process PID=529588 runs in 32 bit mode. ]
mmap(0x1468000, 690022, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1468000
open("/bin/sh", O_RDONLY)               = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\35\3\0\0\0\0\0"..., 512) = 512
execve("/bin/sh", ["./foo", "-c", "\necho lol\n\n\n#00000000: 7c06 ba29"..., "./foo"], \
     0xff890b2c /* 62 vars */) = -1 E2BIG (Argument list too long)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```
So after de-compressing, then an attempt is made to run `/bin/sh -c "<de-compressed_script>"` and this fails with `E2BIG` because the operating system has a limit on the total number of characters that it takes to describe the arguments to `execve`.  The current limit is something like 128KB, but in additon to `argv` that includes the environment variables and the pathname being exec'ed.

Once you hit `E2BIG` things get messy. Direct `execve` does not work.  Piping the de-compressed script into the shell requires another process, and tracking that other process (for using signals, death-of-a-child, etc.)  is problematic.  Writing the script to a temporary file requires space and permission, and removing the file at some point.  The `--force-execve` feature for some recalcitrant executables uses a file in `/tmp`, with forced removal after 3 seconds (via double-fork'ed child); this is a race because it assumes that the shell opens the file before then.  See also `bashx` in https://github.com/upx/upx/issues/590#issuecomment-1215891496 which relies on `bash` to attach arguments to a piped-in script (and suffers the problem of not-the-same-process).

Unless other suggestions arise, then it is likely that this Issue will become `won't fix`.

**Comment by Harvie** [comment]
> this Issue will become won't fix.

Perhaps you can at least prevent UPX from compressing such files?

**Comment by jreiser** [comment]
The above commit propagates any actual E2BIG, which avoids confusion with a shell that reports `hlt` as SIGSEGV.
The code also warns for size > 125KB, and uses style linux.exec/i386 instead, which works but requires more time because of another indirection.
```
$ upx.out -f -o foo comp.sh
        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: comp.sh: Likely E2BIG for size=690022
    690022 ->    424029   61.45% linux.exec/i386 foo                           

Packed 1 file.
$ ./foo
lol
```
