### ISSUE TITLE
macho/ppc32 stopped working with upx-3.95

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#627]
This is a companion to #626 , this time I compiled with `CC="gcc"` to get ppc32 binaries.

ATTACHED COMPILED BINARIES: [diffutils-3.8-powerpc32-macos10.5.8.tar.xz.zip](https://github.com/upx/upx/files/10025247/diffutils-3.8-powerpc32-macos10.5.8.tar.xz.zip)

All versions from upx-3.91 to upx-4.0.0 can compress the attached `cmp` binary.

But only the 3.91, 3.92, 3.93 and 3.94 packed exes actually do work on my mac g5 10.5.8.

**Comment by jreiser** [comment]
So far, this Issue is invalid because there is no report of observed actual behavior, just a claim that "packed exes [beginning with upx-3.95 ] do not work  on my mac gc 10.5.8."  What is the **evidence** of "does not work"?  And the suggestion "just run it; you will see" is explicitly forbidden because it does not enable comparison of supposedly reproducible results.

So far, the Issue template has not been followed:
```
## What's the problem (or question)?
<!--- If describing a bug, tell us what happens instead of the expected behavior -->

## What should have happened?
<!--- If you're describing a bug, tell us what should happen -->
```

If you wish to re-open this Issue then please report literal observed output, such as copy-and-paste of text from a Terminal session, or attach a file of re-directed output (annotated with the actual inputs) which exhibits the bad behavior; and identify the difference between the observed behavior and the expected behavior.  This is the Scientific Method: observe carefully, report what you observe, and analyze only **after** reporting the observed behavior.

**Comment by markus-oberhumer** [comment]
Extremely low priority, but a real issue.
