### ISSUE TITLE
UPX3.93 compression can not run on android7.0, reported "has no section headers", how should solve it?

### ISSUE THREAD

**Issue by y702332688** [upx/upx#65]
UPX3.93 compression can not run on android7.0, reported "has no section headers", how should solve it?

**Comment by jreiser** [comment]
I need documentation and an example (a file that does run, before and after code signing (version 2).)
Where does "has no section headers" appear?  Is this from a shell when trying to run the program, from a runtime shared library loader, from a utility that is processing the program (for code signing, etc.), or from the operating system kernel itself (and where does the message appear?)  If this is a new error code returned from execve(), then what is the code, and what exactly causes it?

Please build either of these two test programs (or their java equivalents, if necessary), and attach (create a .zip archive containing both files; upload to github) the ELF executable files, both before and after code signing.
```
int const x[10000] = {1, 2, 3};
int main(int argc, char *argv[]) { return x[1]; }
```
```
#include <stdio.h>
int main(int argc, char *argv[]) { printf("Hello!\n"); return 0; }
```

**Comment by armedpotato** [comment]
Any update here? I meet the same issue here.

**Comment by armedpotato** [comment]
Any update here? I also meet this issue.

**Comment by armedpotato** [comment]
I have  a so library to compress and then pack into an Android apk, please check the compress progress details:
`31276864 ->  21771468   69.61%    linux/arm    libgame.upx.so`

The APK with compressed so library can be launched on Android 5.0, but failed to launch on Android 7.0. Currently Im still check the compatibility for different version of Android OS.

The APK will crash on Android 7.0, adb logcat return following log:
`03-14 15:20:08.503 D/AndroidRuntime(13197): Shutting down VM
--------- beginning of crash
03-14 15:20:08.503 E/AndroidRuntime(13197): FATAL EXCEPTION: main
03-14 15:20:08.503 E/AndroidRuntime(13197): Process: com.upxtest.test, PID: 13197
03-14 15:20:08.503 E/AndroidRuntime(13197): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.upxtest.test/lib/arm/libgame.so" has no section headers
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at java.lang.Runtime.loadLibrary0(Runtime.java:994)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at java.lang.System.loadLibrary(System.java:1533)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at com.upxtest.test.<clinit>(TestActivity.java:263)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at java.lang.Class.newInstance(Native Method)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.os.Looper.loop(Looper.java:156)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at android.app.ActivityThread.main(ActivityThread.java:6524)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at java.lang.reflect.Method.invoke(Native Method)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
03-14 15:20:08.503 E/AndroidRuntime(13197): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
03-14 15:20:08.505 W/ActivityManager( 1033):   Force finishing activity com.upxtest.test/com.upxtest.test.TestActivity`

In my opinion the root cause should be the dlopen on Android 7.0。

**Comment by jreiser** [comment]
```
dlopen failed: "/data/app/com.upxtest.test/lib/arm/libgame.so" has no section headers
https://github.com/android/platform_bionic/blob/master/linker/linker_phdr.cpp
```
OK, so I interpret the complaint as: a shared library libgame.so that has been compressed by UPX does run on Android 5.0, but the same compressed libgame.so (with no further modifications, and without being re-built) does not run on Android 7.0.

What changed from Android 5.0 to Android 7.0 in regard to loading shared libraries?  Please chime in if you know or have pointers.

The diagnostic is correct, upx removes the ElfXX_Shdr table because up through Android 5.0 its contents were not necessary for execution.  What does the Android 7.0 linker use from ElfXX_Shdr? Inspecting the file linker_phdr.cpp, I see that it searches for SHT_STRTAB.  (Why not use DT_STRTAB instead?)  UPX can put back the ElfXX_Shdr, or at least the SHT_DYNAMIC and SHT_STRTAB, but will that be enough?  Discovering the usages one at a time might take a long time.

**Comment by armedpotato** [comment]
please ref to:
http://stackoverflow.com/questions/38585638/android-n-preview-dlopen-has-no-section-headers-error

**Comment by armedpotato** [comment]
@jreiser Could you please give me some hint about how to put back the ElfXX_Shdr. Although I cannot dig into this issue, but I can test whether can you solution work.

**Comment by armedpotato** [comment]
@jreiser 
Or we can leave or create  a section in UPX which only for passing the Android7 elf section check?

**Comment by jreiser** [comment]
@armedpotato Thank you for the link.  I will continue to look for more documentation, because keeping all the section headers takes a lot of space.  Perhaps it would be enough to keep only SHT_SYMTAB and SHT_STRTAB and SHT_DYNAMIC, for instance.

The UPX compressor deals with **extents**.  There is one extent for the ElfXX_Ehdr and ElfXX_Phdrs as a group, plus one extent for each PT_LOAD, plus one extent for each other interval of the file that is not headers or PT_LOAD.  The "other" intervals are preserved so that -d (decompressing) restores the original file. "Putting back the ElfXX_Shdrs" means that the ElfXX_Shdr records themselves, as well as the regions [.sh_offset, +.sh_size) that they designate, cannot be compressed.  And those regions do not have to be adjacent or in ascending order, and they probably will be relocated when the PT_LOAD get compressed.  So it's an ugly hairball of complication.

**Comment by armedpotato** [comment]
@jreiser 
How about write a dummy section in compressed library?

**Comment by jreiser** [comment]
Looking carefully via "grep -sr SHT_ platform_bionic" I see uses of SHT_DYNAMIC, SHT_DYNSYM, and SHT_STRTAB; plus SHT_ANDROID_REL and SHT_ANDROID_RELA (SHT_LOOS + 1, and +2).  Please verify that these are the only ones that are necessary.  Requiring such "linking view" info for a task [dlopen()] that previously need only "exeuction view" information, is a fundamental change in the ABI [search the 'net for "linking view execution view".]  Shame on the Android community for letting this slip through.  The non-LOOS SHT_* info is redundant with DT_SYMTAB, DT_STRTAB, DT_STRSZ in the PT_DYNAMIC; and the LOOS info should be covered by the DT_REL*.

**Comment by jreiser** [comment]
@armedpotato @y702332688 Please try the devel branch.  Some ElfXX_Shdr have been restored when packing.  However, I see nothing which indicates that a particular .so is specific to Android, so when packing you must use the command-line parameter '--android-shlib' to tell UPX.

**Comment by Qrilee** [comment]
@jreiser i have test the devel branch on some 7.0 devices,it works fine,thanks for update

**Comment by armedpotato** [comment]
@jreiser  I have also test the devel branch on 7.0 and 7.1 devices, it worked.
Good jobs!
BTW, when will you merge it to master?

**Comment by kaitian521** [comment]
@jreiser  thank you! my so can run on Android 8 now

**Comment by 751643992** [comment]
good
