### ISSUE TITLE
linking to upx compressed linux libraries is failing

### ISSUE THREAD

**Issue by satmandu** [upx/upx#659]
## What's the problem (or question)?
Built llvm 16.0.0-rc4 on x86_64 (and i386 and armv7l), and then compressed libraries with `upx --lzma`.

When then building mesa 23.0.0 against it I get this error (on x86_64, but roughly the same on armv7l as well):
```
[2179/2349] Linking target src/gallium/targets/lavapipe/libvulkan_lvp.so
samu: job failed: c++  -o src/gallium/targets/lavapipe/libvulkan_lvp.so src/gallium/targets/lavapipe/libvulkan_lvp.so.p/target.c.o -flto -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -[Wl,-soname,libvulkan_lvp.so](http://wl%2C-soname%2Clibvulkan_lvp.so/) -Wl,--whole-archive src/gallium/frontends/lavapipe/liblavapipe_st.a -Wl,--no-whole-archive -flto=auto src/gallium/auxiliary/pipe-loader/libpipe_loader_static.a src/loader/libloader.a src/util/libxmlconfig.a src/util/libmesa_util.a src/util/format/libmesa_format.a src/util/libmesa_util_sse41.a src/c11/impl/libmesa_util_c11.a src/gallium/auxiliary/libgallium.a src/compiler/nir/libnir.a src/compiler/libcompiler.a src/gallium/winsys/sw/wrapper/libwsw.a src/gallium/winsys/sw/dri/libswdri.a src/gallium/winsys/sw/null/libws_null.a src/gallium/winsys/sw/kms-dri/libswkmsdri.a src/gallium/drivers/llvmpipe/libllvmpipe.a src/gallium/drivers/softpipe/libsoftpipe.a src/vulkan/util/libvulkan_util.a src/vulkan/wsi/libvulkan_wsi.a src/vulkan/runtime/libvulkan_runtime.a -Wl,-Bsymbolic -Wl,--gc-sections -lLLVM-16 -pthread /usr/local/lib64/libz.so -lm /usr/local/lib64/libzstd.so -ldl /usr/local/lib64/libunwind.so /usr/local/lib64/libdrm.so /usr/local/lib64/libexpat.so -lLLVM-16 -lsensors -lLLVM-16 -lLLVM-16 /usr/local/lib64/libudev.so /usr/local/lib64/libxcb-dri3.so /usr/local/lib64/libwayland-client.so /usr/local/lib64/libxcb.so /usr/local/lib64/libX11-xcb.so /usr/local/lib64/libX11.so /usr/local/lib64/libxcb-present.so /usr/local/lib64/libxcb-xfixes.so /usr/local/lib64/libxcb-sync.so /usr/local/lib64/libxcb-randr.so /usr/local/lib64/libxcb-shm.so /usr/local/lib64/libxshmfence.so /usr/local/lib64/libXrandr.so -Wl,--end-group
mold: fatal: /usr/local/lib64/libLLVM-16.so: e_shoff or e_shnum corrupted: 88100980 34
collect2: error: ld returned 1 exit status
```

## What should have happened?
Successful compile?

The build succeeds after running `upx -d` on `/usr/local/lib64/libLLVM-16.so`.
(armv7l build after running `upx -d` on `/usr/local/lib/libLLVM-16.so` currently in progress.)

## How can we reproduce the issue?

Relevant binaries with `/usr/local/lib[64]/libLLVM-16.so`:

armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm/16.0.0-rc4_armv7l/llvm-16.0.0-rc4-chromeos-armv7l.tar.zst',
i686: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm/16.0.0-rc4_i686/llvm-16.0.0-rc4-chromeos-i686.tar.zst',
x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm/16.0.0-rc4_x86_64/llvm-16.0.0-rc4-chromeos-x86_64.tar.zst'

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
 upx --version
upx 4.0.3
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.9
Copyright (C) 1996-2023 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2023 Laszlo Molnar
Copyright (C) 2000-2023 John F. Reiser
Copyright (C) 2002-2023 Jens Medoch
Copyright (C) 1995-2022 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2021 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host/Target Operating System and version: ChromeOS Milestone 90/91
* Host/Target CPU architecture: x86_64, armv7l, and maybe i686

**Comment by jreiser** [comment]
UPX assumes that you are interested in executing the file.  A static linker such as `mold` assumes that you are interested in linking the file.  Those two uses conflict.  In particular, the ElfXX_Shdr are totally unnecessary for execution, so UPX gets rid of them. ( If you want them back, then apply `upx -d`.) Some of the fields in the ElfXX_Ehdr refer to _Shdr information, which might be useful to a module (main program or shared library)  which inspects itself during execution, which occurs `after` de-compression for execution by the UPX stubs (which produces a subset of command-line `upx -d`).  Because ordinary (non-self-reflective) execution never touches those fields, they are "don't care".  Bottom line: static linkers such as `mold` or `/usr/bin/ld` cannot deal with shared libraries that have been compressed by UPX.  So do all your static linking first, then compress.

Edit: And beside that, all the information in a shared library that is relevant to `dlopen` is contained in the ElfXX_Phdr with (.p_type == PT_DYNAMIC).  This is **exactly** all the same information that is relevant to static linking of that shared library for use with a main program or other shared library, just in a different format.  The ElfXX_Shdr are merely a representation that most static linkers such as `mold` find more convenient than the PT_DYNAMIC.  [In particular, the software package `libbfd`, which most static linkers rely on, ignores PT_DYNAMIC.]  In other words,  a static linker that gives up when not finding acceptable ElfXX_Shdr, but ignores good PT_DYNAMIC, is lazy for not using the PT_DYNAMIC.

**Comment by satmandu** [comment]
Thanks. I'll take this upstream with Mold.

**Comment by jreiser** [comment]
@satmandu Using `readelf --headers --dynamic libLLVM-16.so > readelf.out` for the various architectures, I see that the INIT_ARRAY information has more than 600 entries.  For example on x86_64:
```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [23] .init_array       INIT_ARRAY       0000000007c08438  07c06438
       0000000000001318  0000000000000000  WA       0     0     8

Dynamic section at offset 0x7540b68 contains 41 entries:        
  Tag        Type                         Name/Value 
 0x0000000000000019 (INIT_ARRAY)         0x7c08438
 0x000000000000001b (INIT_ARRAYSZ)       4888 (bytes)
```
and using a file dump, the beginning of the list of addresses of static initialization subroutines is:
```
0x107c06438:	0x000000000372bdf0	0x00000000038ebf30
0x107c06448:	0x0000000003920a00	0x0000000003981a30
0x107c06458:	0x00000000039b1160	0x00000000039b24b0
0x107c06468:	0x00000000039dd8e0	0x00000000039ed130
0x107c06478:	0x0000000003a20650	0x0000000003a2e920
0x107c06488:	0x0000000003a40040	0x0000000003a6c1a0
0x107c06498:	0x0000000003a6f4d0	0x0000000003a7d370
0x107c064a8:	0x0000000003a812b0	0x0000000003a8b080
0x107c064b8:	0x0000000003a9f6f0	0x0000000003adde80
0x107c064c8:	0x0000000003b29160	0x0000000003b62800
0x107c064d8:	0x0000000003b6c120	0x0000000003b77b00
0x107c064e8:	0x0000000003b7d880	0x0000000003b8d060
0x107c064f8:	0x0000000003bcb200	0x0000000003be0f00
0x107c06508:	0x0000000003be9cf0	0x0000000003bf4380
0x107c06518:	0x0000000003bf5e30	0x0000000003bfa430
0x107c06528:	0x0000000003c040f0	0x0000000003c09250
```
Notice that the subroutines are almost all on separate 4KiB pages.  This means that during initialization there will be 600 page faults.  You can save around 1 to 3 seconds by not having so many static initializers.  Find a .h header file that is #included into 600 *.o  compilation units, and which performs a static initialization that requires run-time execution, and get rid of the run-time execution.  For a simple variable you can do this by changing the .h file to say `extern`, and then creating a new .cpp file which actually uses a static init to set the value.  Other times it is necessary do a topological sort of all the static inits, figure out the nest of dependencies, then make a PREINIT function for the few initializers that will cover all the rest.

**Comment by satmandu** [comment]
I think you were looking at the upx compressed library.

https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm/16.0.0-rc4_x86_64/llvm-16.0.0-rc4-chromeos-x86_64.tar.zst should now point to the build without upx compression on the library files. 

Regardless, I do see similar information from readelf on this file:

```
readelf --headers --dynamic libLLVM-16.so | grep -3 INIT_ARRAYSZ
 0x0000000000000005 (STRTAB)             0x12caf8
 0x000000000000000a (STRSZ)              2552601 (bytes)
 0x0000000000000019 (INIT_ARRAY)         0x7c083f8
 0x000000000000001b (INIT_ARRAYSZ)       4888 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x7c083f0
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffff0 (VERSYM)             0x39be12
```

Maybe there's something wrong with the compilation process...

(But this definitely sounds like something which should be entered as a bug report to the llvm team if it persists. I'm not seeing any other binary builds of llvm 16 up for x86_64, otherwise I would compare...)

This is the major LLVM library, so this is probably due to something during the compilation process. I'll try switching from LTO=Thin to LTO=Full next week when (hopefully) the next build of llvm 16.0.0 gets released to see if that makes a difference.

**Comment by jreiser** [comment]
In 1992 (31 years ago), I presented **Static Initializers: Reducing the Value-Added Tax on Programs** at the USENIX C++ Technical Conference, Portland, Oregon, pp 171-180: [Conference Proceedings](https://archive.org/details/1992-proceedings-c-portland) and others.  Your current libLLVM-16.so definitely has this problem.  It is not a problem of compilation as such, but a problem of using _allocation hook_ initialization with a static class instance, in order to initialize the API.  Please read the paper; it is a thorough explanation, complete with  4 pages of quantitative diagrams.

**Comment by satmandu** [comment]
I have copied this post to the LLVM forums here: https://discourse.llvm.org/t/libllvm-16-so-suboptimally-creates-600-page-faults-during-initialization/69288

**Comment by satmandu** [comment]
@jreiser If you would be so kind as to respond to the LLVM folks on this, as there appears to be some interest in investigating this further:

https://discourse.llvm.org/t/libllvm-16-so-suboptimally-creates-600-page-faults-during-initialization/69288/4?u=satmandu
