### ISSUE TITLE
upx 4.02 compressed ARM Linux shared library will crash

### ISSUE THREAD

**Issue by csersoft** [upx/upx#689]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
When using upx 4.02 to compress the shared library of arm linux, the program trying to load the library will crash.
The same shared library, compressed with upx 3.96, everything works fine.

## What should have happened?
It should be the same as after upx 3.96 compression, it can work normally

## Do you have an idea for a solution?
No

## How can we reproduce the issue?
Download and unzip the attachment,
need to test under ARM Linux (armv7)
rename the shared library to libtest_lib.so that needs to be tested,
execute test_app.
Or directly use gdb to analyze the coredump file in the attachment.

## Please tell us details about your environment.
* UPX version used (`upx --version`): 4.02
* Host Operating System and version: Ubuntu 20.04
* Host CPU architecture: x86_64
* Target Operating System and version: Embedded ARM Linux 4.1
* Target CPU architecture: ARM Cortex-A9

[test arm linux so.zip](https://github.com/upx/upx/files/12194387/test.arm.linux.so.zip)

**Comment by jreiser** [comment]
Already fixed in branch `devel4`.  To get a build: See the Actions page https://github.com/upx/upx/actions , choose the most-recent successful build such as https://github.com/upx/upx/actions/runs/5677403930 , and scroll down to Artifacts to choose the upx for your host environment such as https://github.com/upx/upx/suites/14603450101/artifacts/827686037 .
