### ISSUE TITLE
Packed, and then unpacked EXE crashes

### ISSUE THREAD

**Issue by tonypdmtr** [upx/upx#75]
## What's the problem (or question)?

Unpacked and repacked EXE crashes

## What should have happened?

The repacked EXE should always work no matter how many times I unpack and repack the same EXE

## Do you have an idea for a solution?

I suspect the unpacking is NOT 100% accurate as the unpacked EXE does not compare equal to the original never-packed EXE

## How can we reproduce the issue?

1. Pack any Windows EXE
2. Unpack the same EXE
3. Repack the same EXE
4. Run, and it crashes

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.91w
* Operating System and version: Win7
* CPU architecture: Intel Celeron G1610 @ 2.60 GHz

**Comment by markus-oberhumer** [comment]
Please provide more concrete info about "any exe".

**Comment by tonypdmtr** [comment]
OK, what I meant by any .EXE is that it happens very often for me (as I usually unpack and repack with --brute option to get the best possible compression), and not with just one particular EXE file.  Actually, I don't remember one occasion it did not happen.  However, I'm not claiming it is 100% reproducible with any random EXE.

I noticed that if I compile some application (for example, the latest Lua interpreter) with Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86 and pack once, it works.  Unpack, and repack, it crashes.  I attach this Lua 5.3 example before any compression attempt for you to try.  Run it, it works. Pack once, run it, and it still works.  Unpack it, and then repack it (with or without the --brute option, no difference), and it will no longer start but crash.

Last minute update: Actually, I just tried once more, and it appears you don't even need to repack a second time to see the problem.  Simply unpack, and try to run it unpacked, and it still crashes,  So, the unpack operation does not work correctly in all cases (maybe with EXE produced by this particular MSVC version, I don't know -- because if I compile the same app with TinyC compiler, the problem is not there).

**Comment by tathanhdinh** [comment]
Could you please upload the sample to some online file hosting and give the link here?

**Comment by tonypdmtr** [comment]
Here it is (unpacked): [sample.exe](https://www.dropbox.com/s/4pfxxl0gtlg6wy1/sample.exe?dl=0)
It runs OK (Win7 console).
Pack it with: upx sample.exe
It still runs OK.
Unpack it with: upx -d sample.exe
It now crashes.

**Comment by tathanhdinh** [comment]
Many thanks @tonypdmtr, I can confirm this, in fact I have the same problem with the latest version `UPX 3.94` in unpacking any `PE` having `Dynamic base` in its `DLL Characteristics`.

@tonypdmtr @ml1050 : It seems to me that UPX, when does `unpack -d`, wipes away the relocation section of any PE compiled with `DYNAMIC BASE`. By tracing how the unpacking stub works, I found that the relocation has done correctly in the packed file but not in the unpacked file. 

For example, given an instruction (in some original PE file having dynamic base) containing a virtual address (abbr. VA):

    0x40567: mov eax, dword ptr [0x401234]

where the relocation section contains an entry which says that the VA `0x401234` in the instruction at `0x40567` will need to be relocated in loading time (given that the binary can be loaded at an arbitrary base address).

The in-memory unpacking stub knows this perfectly: after unpacking the instruction in the memory as the bytes:

    a1 34 12 40 00

it indeed does the relocation by rebasing the bytes `34 12 40 00` using the current base address. For example if the run-time base address is `0x80000` then these bytes will be modified into `34 12 80 00`, and the instruction is loaded correctly as:

    0x80567: mov eax, dword ptr [0x801234]

Since the unpacking stub knows where to rebase, it should use the relocation section somewhere.

But when we unpack the binary by `upx -d`, the relocation section of the original file is wiped out, concretely I found that this section in the unpacked file is zeroed. The relocation information is lost, but the binary is always dynamic base, and it will be loaded at an arbitrary base address when running, for example if the base address is `0x900000` then the instruction will be loaded as:

    0x90567: mov eax, dword ptr [0x401234]

and `0x401234` is not a valid address anymore.

**Comment by Massacre141** [comment]
I have confirmed that this bug is existing in UPX 3.07-3.94 and is non-existant in 2.03. Also there is a "workaround": compress and recompress with 2.03 and the result file does not crash when compressed and recompressed by 3.94. The affected file is WinMTR 0.92 32-bit (64-bit crashes too but there is no way to pack it with 2.03). It seems that file repacked this way remains fully functional.

BTW, this bug is almost year old and is not fixed yet. It seems only valid option for now is to use 2.03?

**Comment by dbjh** [comment]
I have the following compilers on my (64-bit) Windows 7 system:
- Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x64
- Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x86
- gcc (GCC) 6.4.0 [Cygwin 32-bit]
- gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0
- gcc.exe (GCC) 5.3.0 [DJGPP]

The problem of a crashing executable after using upx -d only happens with Microsoft's compilers (in combination with Microsoft (R) Incremental Linker Version 14.00.23506.0 (Visual Studio 2015 Update 1)). I have confirmed the behavior by compressing (upx --ultra-brute) and decompressing (upx -d) a "Hello world!" program with (the Windows build of) UPX version 3.91, 3.94 and 3.95.

I would like to know why this only happens with Microsoft's compilers. I would also like to know why this bug is labeled Windows 10.
