### ISSUE TITLE
App Crash with build with static lib

### ISSUE THREAD

**Issue by Lioncky** [upx/upx#820]
## What should have happened?
I build my dll with the mi-malloc static lib.

## Do you have an idea for a solution?
Build with dynamic lib will works well

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.91-4.2.3 (test 3.91 and 4.2.2 4.2.3)
* Host Operating System and version:Win11(22621.1702)
* Host CPU architecture: intel

**Comment by Lioncky** [comment]
Crash point:
![image](https://github.com/upx/upx/assets/73447685/84158ad9-e44c-44c3-9516-4aa7c3a73f25)

**Comment by jreiser** [comment]
0.  Please use copy+paste of text when communicating text (such as source code, disassembly, memory dump, transcript of console/Terminal/PowerShell, etc.).  A screenshot can be processed by eyeballs only.  Text can be processed by grep (Find+Replace), text editors, foreground/background color adjust, etc.  Printing a screenshot that has a black background requires at least 10 times as much expensive ink as text, and the printed paper cannot be annotated using pen or pencil. The only trick is how to Paste the copied text into GitHub.  For less than one line, then use a backtick at each end of the pasted text.  For more than one line, then surround the pasted paragraph with a line before and after that contains only three characters: three backticks.  (This is a common convention when using the Markdown tool.) A backtick has the character code hex 0x60, octal 0140, decimal 96; on most Western keyboards it is on the same key as tilde, just to the left of the digit '1'.
1. Which version of mi-malloc did you use, and how+where can I get a copy?
2. In order to diagnose and fix, then I need to reproduce the problem. Does a simple example `main() { return malloc(10);}' fail?  If not, then does cutting out major pieces of your program still fail?  Anything to reduce the size of the program wll help.  (Perhaps the problem appears only at certain sizes or sequences of malloc+free?)

**Comment by Lioncky** [comment]
The code crash by upx, I think you can find it by ASM scan in any version upx packaged library, sorry. 
I build the latest mi-malloc (clone .git).
