### ISSUE TITLE
Publish hashes of (Windows) binaries

### ISSUE THREAD

**Issue by apankrat** [upx/upx#822]
This issue tracker is **ONLY** used for requesting sensible features.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

No way to confirm the authenticity of release binaries. In particular, that of Windows versions.

More broadly, looking for a way to hedge against the risk of @markus-oberhumer account compromise as a release maintainer.

Markus, this is not to imply a lack of diligence on your part, just that it might be due to something outside of your control.

## What should have happened?

n/a

## Do you have an idea for a solution?

Ideally, it'd be nice to have them signed, but I understand that obtaining and using a signing cert can be an admin hassle and a financial burden.

In lieu of that, it'd be very helpful to have hashes of all binaries published along side with every release. Clearly these will need to be published either by a different project admin _or_ outside of Github.

## How can we reproduce the issue?

n/a

## Please tell us details about your environment.

n/a

**Comment by markus-oberhumer** [comment]
Well, there's not much we can do:
- Hashes for Windows binaries **ARE listed** in #437.
- If you don't trust our binaries then maybe you do trust your distribution (see badge below)
- If you don't trust your distribution then maybe you do trust our GitHub sources
- Otherwise I fear you have to give up

```sh
$ git clone https://github.com/upx/upx
$ cd upx
$ git checkout 3757579ffc6fa8710b4b7a1055529fea9dcaf149 # aka tag v4.2.4
$ git submodule update --init
$ make build/release
$ make build/extra/cross-windows-mingw32/release
$ make build/extra/cross-windows-mingw64/release
```


[![Packaging status](https://repology.org/badge/vertical-allrepos/upx.svg)](https://repology.org/project/upx/versions)

**Comment by apankrat** [comment]
>* Hashes for Windows binaries **ARE listed** in [[PINNED] False positive antivirus alerts of official UPX releases #437](https://github.com/upx/upx/issues/437).
> 

Missed this, sorry. Not ideal, but this will work. Thanks for the quick reply.

**Comment by jreiser** [comment]
Some additional assurance for a particular compressed executable can be shown by using the de-compressor (`upx -d`).  
1. The person who runs the compressor should check that de-compression produces an identical copy of the original never-compressed file, and then publish the checksum of the original file so that an end-user of a compressed file can compare after de-compression.
2. Run `upx --fileinfo foo.upx` to reveal which version of upx did the compression:
```
    49088 bytes, compressed by UPX 14, method 2, level 8, filter 0x49/0x08
```
Then use the oldest release of the same version (`UPX 14`) to perform de-compression, and compare the de-compressed output.  This helps to detect new attacks.  The UPX version is incremented whenever a new de-compressor must be used, such as when there is a change in the format of a compressed output.

[Edit] As a verification technique, de-compression is not foolproof; see https://github.com/upx/upx/discussions/739 "ELF Bin decompress issue: NotPackedException: not packed by UPX (although it is)"

The Internet Archive may be an additional resource for previous releases of UPX.

**Comment by jreiser** [comment]
> * our GitHub sources

Additional steps for re-building the de-compression stubs (`upx/src/stub/src/*.h`) are listed in `upx/README.SRC/"Developer quick start"` beginning at `4)  # Optional for re-building stubs:`

**Comment by apankrat** [comment]
@jreiser - my concern is how to ensure the authenticity of the copy of upx.exe that is made available via the Releases section here on GH.
