### ISSUE TITLE
Two segmentation faults in UPX

### ISSUE THREAD

**Issue by Heinzeen** [upx/upx#828]
## What's the problem?
While running tests on UPX, we found 2 crashing inputs. In detail:

1. Segmentation fault is received in function `invert_pt_dynamic`.
2. Segmentation fault is received in function `N_BELE_RTP::BEPolicy::get32`.

## What should have happened?

The program should not crash with a segmentation fault.

## Do you have an idea for a solution?

The complexity of the project makes it non-trivial to understand the codebase for people who have never worked on it, but we tried running some tests to help you in the analysis of the bugs we are reporting. We are summarizing here the results of our analysis:

1. checking a string terminator in [src/p_lx_elf.cpp:2096](https://github.com/upx/upx/blob/devel/src/p_lx_elf.cpp#L2096) results in a segmentation fault; analysis with a debugger reveals that both `strtab_max` and `strtab_beg` are equal to 0, so the index `[-1+ strtab_max + strtab_beg]` is evaluated to -1. To solve the issue, the initialization of those two variables might be checked to understand why they are set to 0.
2. in line [src/p_lx_elf.cpp:2372](https://github.com/upx/upx/blob/devel/src/p_lx_elf.cpp#L2372) the array `dynsym` is accessed through the function `get_te32()`. This memory read attempts to read outside any mapped region, resulting in a segmentation fault.

## How can we reproduce the issue?

In the [attached archive](https://github.com/user-attachments/files/15550042/upx-crashes.zip), you will find:

- the executable used for our tests 
- the testcase used to trigger the bugs

These bugs were found with experiments similar to the ones of issue #827. The same fuzzing harness was used, i.e. [test_packed_file_fuzzer](https://github.com/google/oss-fuzz/blob/master/projects/upx/fuzzers/test_packed_file_fuzzer.cpp), compiled with a main function that opens a file, reads its content and calls LLVMFuzzerTestOneInput with it. To observe the bugs, simply run the given binary with the testcases with a command similar to `./test_packed_file_fuzzer crashes/testcase1`.

## Please tell us details about your environment.
* UPX version used: commit hash 3495d1a, latest at the time of testing.
* Host Operating System and version: reproduced on both Ubuntu 22.04 and Ubuntu 20.04
* Host CPU architecture: x86_64
* Compiler: clang 18.0

**Comment by jreiser** [comment]
Thank you for providing the testcases.  It would be even more help to simplify the recipe to reproduce the bugs, by using `/path/to/upx` directly, instead of within `test_packed_file_fuzzer`.  One reason is that source-code paths reported by a debugger that is supervising `test_packed_file_fuzzer`  contain absolute paths such as `/src/upx/...` which require massaging for use by a maintainer.

However, in most cases it is a waste of time and electricity to fuzz the compression side of upx when it attempts to compress an executable for which `readelf --all` complains.  Yes, you may find bugs; and yes, we fix reasonable reports. But in these cases the increase to the value of upx is minuscule. Upx is a tool that is intended for use by a software developer to decrease the size of a valid executable.  There are no worthwhile consequences in compressing an executable that does not run even before it is compressed.  (It is possible for a bug detected by a fuzzed executable to be relevant for the compression of valid executables, but this is rare.)

In contrast, using a fuzzer to detect problems with the **de**-compression side of upx does tend to produce significant value.  Why?  Because system administrators want to have high confidence that `upx -d` is reliable so that it reveals the actual pre-compressed input, in order that tools which detect malware in a de-compressed file give valid answers. If a system  administrator does not have such confidence, then they are likely to prohibit **all** uses of upx.

**Comment by markus-oberhumer** [comment]
I fully agree with John - fuzzing uncompressed binaries basically has no practical value, and I'm not really interested into supporting such issues.

Please concentrate your efforts on problems with **compressed** binaries.

**Comment by markus-oberhumer** [comment]
@jreiser `wontfix`, but I can still merge your proposed branch if you prefer

**Comment by Heinzeen** [comment]
Hello,

Thanks for the overall feedback, we appreciate your effort in addressing our issues fast.

For the parts being tested, we chose the OSS-Fuzz harness with more security relevant bugs reported lately: `test_packed_file_fuzzer` prevailed over `decompress_packed_file_fuzzer` and `list_packed_file_fuzzer`. We completely understand the argument for prioritizing the decompression parts first. The fuzzing campaign we are doing for our project doesn’t delve into semantics, but we’ll keep this in mind when fuzzing upx again!

For the contextual information in the report, the OSS-Fuzz fuzzing harness is supposed to mimic the minimal context needed for the code as if one were executing the full binary. In this specific case, I see the harness calls `upx_main` with a fixed command line, which I assume could be used to drive the reproduction of the testcase inside the `upx` binary. We’ll keep this in mind for future reports to ease the work of maintainers.

Thanks,
Matteo

**Comment by markus-oberhumer** [comment]
I've merged the `jreiser-issue828` branch.
