### ISSUE TITLE
v8 doesn't work under UPX [MSVC]

### ISSUE THREAD

**Issue by BlobTheKat** [upx/upx#855]
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
An executable containing the v8 engine compresses successfully but crashes upon launch

## What should have happened?
Executable should work equally with upx as without

## How can we reproduce the issue?
1. Build v8_monolith according to https://v8.dev/docs/embed
2. Compile their hello world sample (you'll need to include at least `dbghelp.lib`, `advapi32.lib` and `winmm.lib` as v8 uses those)
3. Compress the executable with `upx --best main.exe`
4. Run the executable

## Please tell us details about your environment.
* UPX version used (`upx --version`): __**4.2.4**__
* Host Operating System and version: __**Windows 11**__
* Host CPU architecture: __**x86_64**__
* Target Operating System and version: Same
* Target CPU architecture: Same

## Stack trace
```
#
# Fatal error in , line 0
# Check failed: old_protection == PAGE_READWRITE || old_protection == PAGE_WRITECOPY.
#
#
#
#FailureMessage Object: 00000088E48FF230
==== C stack trace ===============================

        (No symbol) [0x00007FF687E762DB]
        (No symbol) [0x00007FF687E61DC7]
        (No symbol) [0x00007FF687EA14F7]
        (No symbol) [0x00007FF687E827C8]
        (No symbol) [0x00007FF687ECD6C0]
        (No symbol) [0x00007FF687E6CAFD]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF688F34820+15975296]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF688F35259+15977913]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF68911E478+17981400]
        BaseThreadInitThunk [0x00007FFA04CC257D+29]
        RtlUserThreadStart [0x00007FFA05F0AF08+40]
```

**Comment by jreiser** [comment]
You must give a `reproducible` recipe that requires minimal knowledge of "v8".  It is not reproducible to say only "you'll need to include at least ..."; you must specify complete literal paths or URLs.  Developers of UPX know nothing about "v8". Also, please "Paste, drop, or click to add files", or give downloadable URL, of an actual executable file which fails.  This helps remove any confusion about correctly following the recipe.

Separately: a common reason for failure of UPX-compressed "embedded" applications is the application assuming that it can access at runtime the original un-compressed executable (or portions of it.)  The only address space at runtime of a compressed executable is the de-compressed **code** (instructions), named `Resources`, and possibly an "`overlay`" that was recognized at time of compression by UPX.  Anything else has been stripped in order to save space.

**Comment by BlobTheKat** [comment]
> You must give a `reproducible` recipe that requires minimal knowledge of "v8". It is not reproducible to say only "you'll need to include at least ..."; you must specify complete literal paths or URLs. Developers of UPX know nothing about "v8". Also, please "Paste, drop, or click to add files", or give downloadable URL, of an actual executable file which fails. This helps remove any confusion about correctly following the recipe.

Clarification: add `dbghelp.lib advapi32.lib winmm.lib` at the end of the build command

**Comment by BlobTheKat** [comment]
Uploaded as zip because github, here is a reproducible example (before upx)
[main.exe](https://github.com/user-attachments/files/17451655/main.exe.zip)

**Comment by bitraid** [comment]
This program calls `VirtualProtect` to set the access of `.data` section to `PAGE_READONLY`, but also checks the old access protection (which is returned by VirtualProtect), and if it's not `PAGE_READWRITE` or `PAGE_WRITECOPY`, it throws an exception (which is the case when UPX is used, because it's `PAGE_EXECUTE_READWRITE`).

You should be able to use UPX by removing this line before building:
https://github.com/v8/v8/blob/037874e72ec91408e1dceac660602dae5f682200/src/base/platform/platform-win32.cc#L1074

Alternatively, you can open the executable (before compression) with a hex editor, search for bytes `8B 44 24 2C 83 F8 04 74 05`, and change `74` to `EB`. You can then use UPX, and it should work.

**Comment by partyblob** [comment]
> This program calls `VirtualProtect` to set the access of `.data` section to `PAGE_READONLY`, but also checks the old access protection (which is returned by VirtualProtect), and if it's not `PAGE_READWRITE` or `PAGE_WRITECOPY`, it throws an exception (which is the case when UPX is used, because it's `PAGE_EXECUTE_READWRITE`).
> 
> 
> 
> You should be able to use UPX by removing this line before building:
> 
> https://github.com/v8/v8/blob/037874e72ec91408e1dceac660602dae5f682200/src/base/platform/platform-win32.cc#L1074
> 
> 
> 
> Alternatively, you can open the executable (before compression) with a hex editor, search for bytes `8B 44 24 2C 83 F8 04 74 05`, and change `74` to `EB`. You can then use UPX, and it should work.

You're a hero, I will try this later

**Comment by BlobTheKat** [comment]
> This program calls `VirtualProtect` to set the access of `.data` section to `PAGE_READONLY`, but also checks the old access protection (which is returned by VirtualProtect), and if it's not `PAGE_READWRITE` or `PAGE_WRITECOPY`, it throws an exception (which is the case when UPX is used, because it's `PAGE_EXECUTE_READWRITE`).

Why does UPX set the protection to 
`PAGE_EXECUTE_READWRITE`? Isn't this a security concern?

**Comment by bitraid** [comment]
> Why does UPX set the protection to
> `PAGE_EXECUTE_READWRITE`? Isn't this a security concern?

It has to be `PAGE_EXECUTE_READWRITE`, because UPX has in one section the original sections compressed, along with the decompression code.
