### ISSUE TITLE
When I use UPX, some antivirus programs detect my application as a virus.

### ISSUE THREAD

**Issue by kabiri** [upx/upx#856]
When I use UPX, some antivirus programs (windows 32 bit) detect my application as a virus.

link : https://www.virustotal.com/gui/file/971c9b0a2ef08dcfd3d8e0a87cb9a0cdfdf2997926a5773ad04a5798d98adef1?nocache=1
![image](https://github.com/user-attachments/assets/b793b9a2-0f24-4558-b2ee-473a78d83add)

**Comment by jreiser** [comment]
You must have not seen, or chose to ignore, the [[PINNED] False positive antivirus alerts of official UPX rele...](https://github.com/upx/upx/issues/437) which appears at the top of https://github.com/upx/upx/issues .

Those reports are "**false positive**":  UPX has no virus, and compression by UPX creates no virus.  Any anti-virus program which clams a virus due to compression by UPX is DEFECTIVE.  *You* must work with the vendor of the anti-virus product to resolve the issue.  UPX co-operates with anti-virus detectors by having a de-compressor (`upx -d`) which reveals the original input to UPX, so that the anti-virus program can scan it.

**Comment by kabiri** [comment]
I know it's a false positive, but convincing my program's users of this is difficult. As the developer of UPX, you should resolve this issue with the antivirus programs, not me. Out of 70 antivirus programs, 10 detect it as a virus. I think this problem did not exist in version 3.4.0.0.

**Comment by jreiser** [comment]
NO, this is not a problem that belongs to UPX.  The problem belongs to you, your users, and the anti-virus vendor.  In particular, an anti-virus product which reports false positive has not learned from more than 25 years of history that UPX does not create malware.  For any particular executable in question, it is simple to detect 4 instances of "UPX" and/or the UPX copyright string, and if so then apply `upx -d` to de-compress, and if successful then to run the virus detector on the output.  If the anti-virus product does not do so, then that is a bug in the anti-virus product.  There will be no further discussion.

**Comment by jreiser** [comment]
For a WinPE file the initial tip-off of probable compression by UPX is Sections named "UPX0" and "UPX1", and the string "UPX!".
For an ELF file the initial tip-off is 2 to 4 instances of "UPX!" and usually the full copyright notice:
```
$Info: This file is packed with the UPX executable packer http://upx.sf.net $
$Id: UPX X.XX Copyright (C) 1996-20YY the UPX Team. All Rights Reserved. $
```
with 'X' and 'Y' numeric.
